<div class="row">
	<div class="col-xs-12">
		<?php if (count($list) < 1) { ?>
			<p>No suggestions</p>
		<?php } else { ?>
			<table class="table table-striped table-bordered table-hover">
				<tr>
					<th>Date</th>
					<th>Text</th>
					<th>User</th>
					<th>Votes</th>
				</tr>
				<?php foreach($list as $item) { ?>
					<tr>
						<td class="nobr"><?= date("m/d/Y H:i:s", strtotime($item->inserted)) ?></td>
						<td><?= $item->text ?></td>
						<td><?= $item->user ?></td>
						<td class="text-center"><?= $item->votes_count ?></td>
					</tr>
				<?php } ?>
			</table>
		<?php } ?>
	</div>
</div>
