<div class="row">
	<div class="col-xs-12">
		<?php if(count($list) < 1) { ?>
			<p>No suggestions</p>
		<?php } else { ?>
			<table class="table table-striped table-bordered table-hover">
				<tr>
					<th>Date</th>
					<th>Text</th>
					<th>User</th>
					<th>Actions</th>
				</tr>
				<?php foreach($list as $item) { ?>
					<tr>
						<td class="nobr"><?= date("m/d/Y H:i:s", strtotime($item->inserted)) ?></td>
						<td><?= $item->text ?></td>
						<td><?= $item->user ?></td>
						<td class="nobr">
							<a href="/suggestion/approve/<?= $item->id ?>" class="btn btn-xs btn-default" onclick="return confirm('Are you sure to approve?');"><span class="glyphicon glyphicon-ok"></span></a>
							<a href="/suggestion/discard/<?= $item->id ?>" class="btn btn-xs btn-default" onclick="return confirm('Are you sure to discard?');"><span class="glyphicon glyphicon-remove"></span></a>
						</td>
					</tr>
				<?php } ?>
			</table>
		<?php } ?>
	</div>
</div>
