<div class="row">
	<div class="col-xs-12">
		<h2><?= $survey->title ?></h2>
		<p>Total questions: <?= $results[0]->total ?></p>

		<table id="servicesTable" class="table">
			<tr>
				<th>Email</th>
				<th>Questions answered</th>
				<th>Completion</th>
			</tr>
			<?php foreach($results as $item) { ?>
				<tr>
					<td><?= $item->email ?></td><td><?= $item->choosen ?></td>
					<td>
						<div class="progress">
							<?php $p = number_format($item->choosen/$item->total*100,1) ?>
							<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?= $p ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?= $p ?>%">
								<span><?= $p ?>%</span>
							</div>
						</div>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
</div>
