<div class="row">
	<div class="col-xs-12">
		<a href="/survey/surveys" class="btn btn-default">&lt;&lt; Surveys</a><br/><br/>

		<?php if ($message!==false) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"> # <?= $survey->id ?> <?= $survey->title ?></h3>
			</div>
			<table id="servicesTable" class="table">
				<tbody>
					<?php foreach ($questions as $question): ?>
						<tr>
							<form action="/survey/surveyQuestions?option=setQuestion&survey=<?= $survey->id ?>&id=<?= $question->id?>" method="post">
								<input type="hidden" name="survey" value="<?= $survey->id ?>">
								<td><input class="form-control" name="surveyQuestionTitle" value="<?= $question->title ?>"></td>
								<td class="text-center"><input class="btn btn-default" type="submit" name="surveySubmit" value="Set"></td>
							</form>
							</td>
								<td class="text-center"><a class="btn btn-default" href="/survey/surveyQuestions?option=delQuestion&id=<?= $question->id ?>&survey=<?= $survey->id ?>" onclick="return confirm('Are you sure?');"><span class="glyphicon glyphicon-trash"></a>
							</td>
						</tr>
				<?php foreach($question->answers as $answer):?>
				<tr>
						<form action="/survey/surveyQuestions?option=setAnswer&survey=<?= $survey->id ?>&id=<?= $answer->id ?>" method="post">


							<td>
								<div class="input-group">
									<span class="input-group-addon"> <input type="radio" aria-label="..." disabled="true">
									</span> <input class="form-control" name="surveyAnswerTitle" placeholder="New answer title" value="<?= $answer->title ?>">

							</td>
							</div>
							<td class="text-center"><input class="btn btn-default" type="submit" name="surveySubmit" value="Set"></td>
						</form>
						<td class="text-center"><a class="btn btn-default" href="/survey/surveyQuestions?option=delAnswer&id=<?= $answer->id ?>&survey=<?= $survey->id ?>" onclick="return confirm('Are you sure?');"><span class="glyphicon glyphicon-trash"></span></a>
						</td>
					</tr>
				<?php endforeach ?>
				<tr>
						<form action="/survey/surveyQuestions?option=addAnswer&survey=<?= $survey->id ?>" method="post">
							<input type="hidden" name="question" value="<?= $question->id ?>">


							<td>
								<div class="input-group">
									<span class="input-group-addon"> <input type="radio" aria-label="..." disabled="true">
									</span> <input class="form-control" name="surveyAnswerTitle" placeholder="New answer">

							</td>
							</div>
							<td class="text-center"><input class="btn btn-default" type="submit" name="surveySubmit" value="+"></td>
						</form>
					</tr>
			<?php endforeach ?>
					<tr>
						<form action="/survey/surveyQuestions?option=addQuestion&survey=<?= $survey->id ?>" method="post">
							<input type="hidden" name="survey" value="<?= $survey->id ?>">
							<td>
								<div class="input-group">
									<span class="input-group-addon" id="basic-addon3">New question:</span> <input class="form-control" name="surveyQuestionTitle">
								</td>
								</div>
							<td class="text-center"><input class="btn btn-default" type="submit" name="surveySubmit" value="+"></td>
						</form>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
