<div class="row">
    <div class="col-xs-12">
        <h1>Ads Analytic</h1>
    </div>   
</div>

<div class="row">
    <div class="col-xs-12">
        <table id="adsTable" class="table">
			<thead>
				<th>Owner</th>
				<th class="text-center">Inserted Date</th>
				<th class="text-center">Tittle</th>
				<th class="text-center">Impressions</th>
				<th class="text-center">Day Paid</th>
				<th class="text-center">Expiration Date</th>
			</thead>
			<tbody>
			<?php foreach ($adsData as $data) { ?>
				<tr>
					<td class="text-center"><?php echo $data['owner']; ?></td>
					<td class="text-center"><?php echo $data['insetedDate']; ?></td>
					<td class="text-center"><?php echo $data['tittle']; ?></td>
					<td class="text-center"><?php echo $data['impressions']; ?></td>
					<td class="text-center"><?php echo $data['dayPaid']; ?></td>
					<td class="text-center"><?php echo $data['expiration']; ?></td>
				</tr>
			<?php } ?>
			</tbody>
        </table>
    </div>
</div>