<div class="row">
    <div class="col-xs-12">
        <h1>Ads Analytic</h1>
    </div>   
</div>

<div class="row">
    <div class="col-xs-12">
        <table id="adsTable" border="1" style="width:100%">
            <th>Owner</th>
            <th>Inserted Date</th>
            <th>Tittle</th>
            <th>Impressions</th>
            <th>Day Paid</th>
            <th>Expiration Date</th>
        </table>
    </div>
</div>