<div class="row">
	<div class="col-xs-6">
		<!-- WEEKLY GROSS TRAFFIC -->
		<div class="panel panel-default">
			<div class="panel-heading">Weekly gross traffic</div>
			<div class="panel-body">
				<div id="weeklyGrossTraffic" style="width:100%;"></div>
			</div>
		</div>
	</div>

	<div class="col-xs-6">
		<!-- MONTHLY GROSS TRAFFIC -->
		<div class="panel panel-default">
			<div class="panel-heading">Monthly gross traffic</div>
			<div class="panel-body">
				<div id="monthlyGrossTraffic" style="width:100%;"></div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-6">
		<!-- MONTHLY UNIQUE TRAFFIC -->
		<div class="panel panel-default">
			<div class="panel-heading">Unique traffic</div>
			<div class="panel-body">
				<div id="monthlyUniqueTraffic" style="width:100%;"></div>
			</div>
		</div>
	</div>

	<div class="col-xs-6">
		<!-- MONTHLY NEW USERS -->
		<div class="panel panel-default">
			<div class="panel-heading">New users</div>
			<div class="panel-body">
				<div id="monthlyNewUsers" style="width:100%;"></div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-3">
		<!-- LAST 30 DAYS ENVIRONMENT -->
		<div class="panel panel-default">
			<div class="panel-heading">Last 30 days of each environment</div>
			<div class="panel-body">
				<div id="last30EnvironmentUsage" style="width:100%;"></div>
			</div>
		</div>
	</div>

	<div class="col-xs-3">
		<!-- APP VERSIONS -->
		<div class="panel panel-default">
			<div class="panel-heading">Versions of the app</div>
			<div class="panel-body">
				<div id="appVersions" style="width:100%;"></div>
			</div>
		</div>
	</div>

	<div class="col-xs-3">
		<!-- LAST 30 SERVICE USAGE -->
		<div class="panel panel-default">
			<div class="panel-heading">Last 30 days of service usage</div>
			<div class="panel-body">
				<div id="last30DaysServiceUsage" style="width:100%;"></div>
			</div>
		</div>
	</div>

	<div class="col-xs-3">
		<!-- LAST 30 ACTIVE DOMAINS -->
		<div class="panel panel-default">
			<div class="panel-heading">Last 30 days active domains</div>
			<div class="panel-body">
				<div id="last30DaysActiveDomains" style="width:100%;"></div>
			</div>
		</div>
	</div>
</div>


<!-- JS TO LOAD CHARTS -->


<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// Weecly visitors
	google.setOnLoadCallback(weeklyGrossTraffic);
	function weeklyGrossTraffic() {
		var data = google.visualization.arrayToDataTable([
			['Day of the week', 'Received', 'Sent'],
			<?php foreach ($weeklyGrossTraffic as $data) { ?>
				['<?=$data['date']; ?>',<?=$data['received']; ?>,<?=$data['sent']; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('weeklyGrossTraffic'));
		chart.draw(data, {});
	}

	// Monthly visitors
	google.setOnLoadCallback(monthlyGrossTraffic);
	function monthlyGrossTraffic() {
		var data = google.visualization.arrayToDataTable([
			['Month and Year', 'Received', 'Sent'],
			<?php foreach ($monthlyGrossTraffic as $data) { ?>
				['<?=$data['date']; ?>',<?=$data['received']; ?>,<?=$data['sent']; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyGrossTraffic'));
		chart.draw(data, {});
	}

	// MONTHLY UNIQUE TRAFFIC
	google.setOnLoadCallback(monthlyUniqueTraffic);
	function monthlyUniqueTraffic() {
		var data = google.visualization.arrayToDataTable([
			['Month and Year', 'New Users'],
			<?php foreach ($monthlyUniqueTraffic as $data) { ?>
				['<?= $data['date'] ?>','<?= $data['visitors'] ?>'],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyUniqueTraffic'));
		chart.draw(data, {colors:['orange','green']});
	}

	// MONTHLY NEW USERS
	google.setOnLoadCallback(monthlyNewUsers);
	function monthlyNewUsers() {
		var data = google.visualization.arrayToDataTable([
			['Month and Year', 'New Users'],
			<?php foreach ($montlyNewUsers as $data) { ?>
				['<?= $data['date'] ?>','<?= $data['visitors'] ?>'],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyNewUsers'));
		chart.draw(data, {colors:['orange','green']});
	}

	// Last 30 days Environment
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(last30EnvironmentUsage);
	function last30EnvironmentUsage() {
		var data = google.visualization.arrayToDataTable([
			['Environment', 'Usage'],
			<?php foreach ($last30EnvironmentUsage as $data) { ?>
				['<?= $data['environment'] ?>', <?= $data['number'] ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('last30EnvironmentUsage'));
		chart.draw(data, options);
	}

	// App versions
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(appVersions);
	function appVersions() {
		var data = google.visualization.arrayToDataTable([
			['Version', 'People'],
			<?php foreach ($appVersions as $data) { ?>
				['<?= $data['version'] ?>',<?=$data['people'] ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('appVersions'));
		chart.draw(data, options);
	}

	// Last 30 days service usage
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(last30DaysServiceUsage);
	function last30DaysServiceUsage() {
		var data = google.visualization.arrayToDataTable([
			['Service', 'Usage'],
			<?php foreach ($last30DaysServiceUsage as $data) { ?>
				['<?= $data['service'] ?>', <?= $data['usage'] ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('last30DaysServiceUsage'));
		chart.draw(data, options);
	}

	// Last 30 days domains usage
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(last30DaysActiveDomains);
	function last30DaysActiveDomains() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($last30DaysActiveDomains as $data) { ?>
				['<?=$data['domain']; ?>',<?=$data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('last30DaysActiveDomains'));
		chart.draw(data, options);
	}
</script>
