<div class="row">
	<div class="col-xs-12">
		<h1>Analytics</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<h2>Weecly incoming emails</h2>
		<img class="fullscreen" src="<?php echo $visitorsWeecly->getUrl(); ?>" />

		<h2>Monthly incoming emails</h2>
		<img class="fullscreen" src="<?php echo $visitorsMonthly->getUrl(); ?>" />

		<h2>Monthly new users</h2>
		<img class="fullscreen" src="<?php echo $newUsers->getUrl(); ?>" />

		<h2>Current number of users</h2>
		<p><?php echo $currentNumberOfActiveUsers; ?></p>

		<h2>Monthly services usage</h2>
		<img src="<?php echo $servicesUsageMonthly->getUrl(); ?>" />

		<h2>Monthly active domains</h2>
		<img src="<?php echo $activeDomainsMonthly->getUrl(); ?>" />

		<h2>Monthly bounce rate</h2>
		<p class="small">Emails received only once a month</p>
		<img class="fullscreen" src="<?php echo $bounceRateMontly->getUrl(); ?>" />

		<h2>Monthly bounce rate</h2>
		<p class="small">Emails received only once a month</p>
		<img class="fullscreen" src="<?php echo $updatedProfilesMontly->getUrl(); ?>" />

		<h2>Current number of running ads</h2>
		<p><?php echo $currentNumberOfRunningaAds; ?></p>
	</div>
</div>
