<div class="row">
	<div class="col-xs-12">
		<h1>Analytics</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-3">
		<p>Gauge #1</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #2</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #3</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #4</p>
	</div>
</div>

<div class="row">
	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Menu</div>
			<div class="panel-body">
				<a href="analytics/audience">Audience</a><br/>
				<a href="analytics/profile">Profile</a><br/>
				<a href="analytics/profilesearch">Profile Search</a><br/>
				<a href="analytics/services">Services</a><br/>
				<a href="analytics/ads">Ads</a><br/>
			</div>
		</div>
	</div>

	<div class="col-xs-8">
		<p>Stuff to add later</p>
	</div>
</div>
