<div class="row">
	<div class="col-xs-12">
		<h1>A shitty header</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-6">
		<p>Some shit here</p>
	</div>
	<div class="col-xs-6">
		<p>Even more shit here</p>
	</div>
</div>

<div class="row">
	<div class="col-xs-3">
		<p>Shit</p>
	</div>
	<div class="col-xs-3">
		<p>Shit</p>
	</div>
	<div class="col-xs-3">
		<p>Shit</p>
	</div>
	<div class="col-xs-3">
		<p>Shit</p>
	</div>
</div>