<div class="row">
	<div class="col-xs-12">
		<h1>Analytics</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<h2>Users with profile vs users without profile</h2>
		<div id="chart_pie_profiles" style="width: 300px; height: 300px;"></div>

		<h2>Profile completion</h2>
		<table class="table">
			<thead>
				<tr>
					<th>Caption</th>
					<th class="text-center">Number</th>
					<th class="text-center">Percent</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($profilesData as $data) { ?>
				<tr>
					<td><?php echo $data['caption']; ?></td>
					<td class="text-center"><?php echo $data['number']; ?></td>
					<td class="text-center"><?php echo $data['percent']; ?>%</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>

		<h2>Number of profiles per province</h2>
		<div id="chart_map_profiles" style="width: 900px; height: 500px;"></div>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// users with profiles vs users without profiles
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			['Users with profile', <?php echo $usersWithProfile; ?>],
			['Users without profile', <?php echo $usersWithoutProfile; ?>]
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('chart_pie_profiles'));
		chart.draw(data, options);
	}

	// profiles by province
	google.load('visualization', '1', {'packages': ['geochart']});
	google.setOnLoadCallback(drawRegionsMap);
	function drawRegionsMap() {
		var data = google.visualization.arrayToDataTable([
			['Province', 'Profiles'],
			<?php foreach ($profilesPerProvince as $provinces) { ?>
				['<?php echo $provinces['region']; ?>',<?php echo $provinces['profiles']; ?>],
			<?php } ?>
		]);
		var options = {
			region: 'CU',
			resolution: 'provinces',
			displayMode: 'regions'
		};
		var chart = new google.visualization.GeoChart(document.getElementById('chart_map_profiles'));
		chart.draw(data, options);
	};
</script>
