<div class="row">
    <div class="col-xs-12">
	<h1>Search for a Person</h1>
    </div>
</div>
<?php 
	if( ! empty($searchError))
	{
?>
	<br/>
	<div class="alert alert-danger"><?php echo $searchError; ?></div>
<?php
	}
?>
<div>
    <div class="col-xs-12">
        <form method="post">
            <input type="text" name="email" placeholder="Email" />
            <input type="submit" name="profilesearch" value="Search">
        </form>
    </div>
</div>

<div>
    <div class="col-xs-12">
        <label for="personImage">Image</label>
        <?php	
			if(!empty($email))
			{
				if($email != 1)
					"<img id='personImage' src='../public/profile/'" . $email . "'>";
				else
					echo "No image available";
			}
		?>
    </div>
    
    <div class="col-xs-12">
        <label for="personFirstName">Fist Name: </label>
        <p id="personFirstName" <?php if(!empty($firstName)) { ?> >
			<?php
				if($firstName != 1)
					echo $firstName;
				else
					echo "No First Name available";
			?>
		</p <?php } ?> >
    </div>
	
	<div class="col-xs-12">
        <label for="personMiddleName">Middle Name: </label>
        <p id="personMiddleName" <?php if(!empty($middleName)) { ?> >
			<?php 
				if($middleName != 1)
					echo $middleName;
				else
					echo "No Middle Name available";
			?>
		</p <?php } ?> >
    </div>
	
	<div class="col-xs-12">
        <label for="personLastName">Last Name: </label>
		<p id="personLastName" <?php if(!empty($lastName)) { ?> >
			<?php
				if($lastName != 1)
					echo $lastName;
				else
					echo "No Last Name available";
			?>
		</p <?php } ?> >
    </div>
	
	<div class="col-xs-12">
        <label for="personMotherName">Mother Name: </label>
        <p id="personMotherName" <?php if(!empty($motherName)) { ?> >
			<?php
					if($motherName != 1)
						echo $motherName;
					else
						echo "No Mother Name available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="DoB">Date of Birth: </label>
        <p id="DoB" <?php if(!empty($dob)) { ?> >
			<?php 
				if($dob != 1)
					echo $dob;
				else
					echo "No Date of Birth available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personAge">Age: </label>            
        <p id="personAge" <?php if(!empty($age)) { ?> >
			<?php
				if($age != 1)
					echo $age;
				else
					echo "No Age available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personGender">Gender: </label>
        <p id="personGender" <?php if(!empty($gender)) { ?> >
			<?php
				if($gender != 1)
					echo $gender;
				else
					echo "No gender available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="phoneNumber">Phone Number: </label>
        <p id="phoneNumber" <?php if(!empty($phone)) { ?> >
			<?php
				if($phone != 1)
					echo $phone;
				else
					echo "No Phone Number available";
			?>
		</p>
    </div <?php } ?> >
    
    <div class="col-xs-12">
        <label for="eyesColor">Eyes Color: </label>
        <p id="eyesColor" <?php if(!empty($eyes)) { ?> >
			<?php
				if($eyes != 1)
					echo $eyes;
				else
					echo "No eyes available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="skinColor">Skin Color: </label>
        <p id="skinColor" <?php if(!empty($skin)) { ?> >
			<?php
				if($skin != 1)
					echo $skin;
				else
					echo "No Skin is available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="bodyType">Body Type: </label>
        <p id="bodyType" <?php if(!empty($body)) { ?> >
			<?php
				if($body != 1)
					echo $body;
				else
					echo "No Body Type available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="hairColor">Hair Color: </label>
        <p id="hairColor" <?php if(!empty($hair)) { ?> >
			<?php
				if($hair != 1)
					echo $hair;
				else
					echo "No Hair Color available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personCity">City: </label>
        <p id="personCity" <?php if(!empty($city)) { ?> >
			<?php
				if($city != 1)
					echo $city;
				else
					echo "No City available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personProvince">Province: </label>
        <p id="personProvince" <?php if(!empty($province)) { ?> >
			<?php
				if($province != 1)
					echo $province;
				else
					echo "No province available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personAboutMe">About Me: </label>
        <p id="personAboutMe" <?php if(!empty($aboutMe)) { ?> >
			<?php
				if($aboutMe != 1)
					echo $aboutMe;
				else
					echo "No About Me available";
			?>
		</p <?php } ?> >
    </div>
    
    <div class="col-xs-12">
        <label for="personCredit">Credit: </label>
        <p id="personCredit" <?php if(!empty($credit)) { ?> >
			<?php
				if($credit != 1)
					echo $credit;
				else
					echo "No credit available";
			?>
		</p <?php } ?> >
    </div>
</div>

