<div class="row">
    <div class="col-xs-12">
	<h1>Search for a Person</h1>
    </div>
</div>

<div>
    <div class="col-xs-12">
        <form>
            <input type="text" name="email" placeholder="Email" />
            <input type="submit" name="searchPerson" placeholder="Search">
        </form>
    </div>
</div>

<div>
    <div class="col-xs-12">
        <label for="personImage">Image</label>
        <img id="personImage" />
    </div>
    
    <div class="col-xs-12">
        <label for="personName">Name: </label>
        <p id="personName"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="DoB">Date of Birth: </label>
        <p id="DoB"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personAge">Age: </label>            
        <p id="personAge"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personGender">Gender: </label>
        <p id="personGender"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="phoneNumber">Phone Number: </label>
        <p id="phoneNumber"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="eyesColor">Eyes Color: </label>
        <p id="eyesColor"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="skinColor">Skin Color: </label>
        <p id="skinColor"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="bodyType">Body Type: </label>
        <p id="bodyType"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="hairColor">Hair Color: </label>
        <p id="hairColor"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personCity">City: </label>
        <p id="personCity"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personProvince">Province: </label>
        <p id="personProvince"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personAboutMe">About Me: </label>
        <p id="personAboutMe"></p>
    </div>
    
    <div class="col-xs-12">
        <label for="personCredit">Credit: </label>
        <p id="personCredit"></p>
    </div>
</div>

