<div class="row">
    <div class="col-xs-12">
		<h1>Services Analytics</h1>
    </div>
</div>

<div class="row">
	<div class="col-xs-12">
		<table id="servicesTable" class="table">
			<thead>
				<tr>
					<th>Service Description</th>
					<th class="text-center">Creator</th>
					<th class="text-center">Category</th>
					<th class="text-center">Deploy Key</th>
					<th class="text-center">Insertion Date</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($servicesData as $data) { ?>
				<tr>
					<td><?php echo $data['description']; ?></td>
					<td class="text-center"><?php echo $data['creator']; ?></td>
					<td class="text-center"><?php echo $data['category']; ?></td>
					<td class="text-center"><?php echo $data['deployKey']; ?></td>
					<td class="text-center"><?php echo $data['insertionDate']; ?></td>
					<td class="text-center"><input type="submit" id="runService" /></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
