<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" href="/nodes">Output emails</a>
		<a class="btn btn-small btn-default" href="/nodes/input">Input emails</a>
		<a class="btn btn-small btn-default" href="/nodes/queque">Waiting Queque</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<div class="panel panel-default">
			<form action="/nodes/delivery" method="get">
				<div class="input-group">
					<input required type="email" class="form-control" name="email" id="email" value="<?=$email?>" placeholder="Search by email" data-error="Bruh, that email address is invalid" title="Insert the email of the user">
					<span class="input-group-btn">
						<button type="submit" class="btn btn-success">Search</button>
 					 </span>
 					 <div class="help-block with-errors"></div>
				</div>
			</form>
		</div>

		<h2>Emails received (Last 100)</h2>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Date</th>
					<th>Received At</th>
					<th>Subject</th>
					<th>ID</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($received as $email) { ?>
				<tr>
					<td><?=date("m/d h:i A", strtotime($email->inserted))?></td>
					<td><?=$email->mailbox?></td>
					<td><?=$email->subject?></td>
					<td><?=$email->id?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>

		<h2>Emails sent (Last 100)</h2>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Date</th>
					<th>Sent From</th>
					<th>Subject</th>
					<th>Group</th>
					<th>Origin</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($sent as $email) { ?>
				<tr>
					<td><?=date("m/d h:i A", strtotime($email->inserted))?></td>
					<td><?=str_replace(['>','<'], '', $email->mailbox)?></td>
					<td><?=$email->subject?></td>
					<td><?=$email->group?></td>
					<td><?=$email->origin?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.table').DataTable();
	});
</script>
