<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" href="/nodes/save"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Email</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">From</th>
					<th class="text-center">Limit</th>
					<th class="text-center">Total Sent</th>
					<th class="text-center">Last Sent</th>
					<th class="text-center">Status</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($nodes as $node) { ?>
				<?php if($currentNode != $node->node) { ?>
				<tr>
					<td class="success text-center" colspan="6">
						<a href="http://<?=$node->ip?>" target="_blank"><?=$node->name?></a>
					</td>
				</tr>
				<?php $currentNode = $node->node; ?>
				<?php } ?>
				<tr>
					<td class="text-center"><?=$node->email?></td>
					<td class="text-center"><span <?php if($node->daily == $node->limit) echo 'style="color:#CD3853;"'; ?>><?=$node->daily?>/<b><?=$node->limit?></b></span></td>
					<td class="text-center"><?=$node->sent?></td>
					<td class="text-center"><?=$node->last_sent?></td>
					<td class="text-center">
						<?php
							if(empty($node->active)) echo "<span class='glyphicon glyphicon-remove alert-danger' title='Account is inactive' aria-hidden='true'></span>";
							elseif($node->paused) echo "<span class='glyphicon glyphicon-time alert-warning' title='Active at {$node->blocked_until}' aria-hidden='true'></span>";
							elseif($node->daily >= $node->limit) echo "<span class='glyphicon glyphicon-alert alert-info' title='Daily limit reached' aria-hidden='true'></span>";
							else echo "<span class='glyphicon glyphicon-ok alert-success' title='Running' aria-hidden='true'></span>";
						?>
					</td>
					<td class="text-center">
						<nobr>
							<?php if(empty($node->active) || $node->paused) { ?>
								<a class="btn btn-xs btn-default" href="/nodes/statusSubmit?status=1&email=<?=$node->email?>"><span class="glyphicon glyphicon-play" aria-hidden="true"></span></a>
							<?php } else { ?>
								<a class="btn btn-xs btn-default" href="/nodes/statusSubmit?status=0&email=<?=$node->email?>"><span class="glyphicon glyphicon-pause" aria-hidden="true"></span></a>
							<?php } ?>
							<a class="btn btn-xs btn-default" href="/nodes/save?email=<?=$node->email?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
						</nobr>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
