<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" data-toggle="modal" data-target="#newInputEmail"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Email</a>
		<a class="btn btn-small btn-default" href="/nodes">Output emails</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Email</th>
					<th class="text-center">Received</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($emails as $email) { ?>
				<tr>
					<td class="text-center"><?=$email->email?></td>
					<td class="text-center"><?=$email->received?></td>
					<td class="text-center">
						<a class="btn btn-xs btn-danger" onclick="return confirm('Are you sure? There is no way back!');" href="/nodes/deleteInputSubmit?email=<?=$email->email?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal to add/edit a can response -->
<div id="newInputEmail" class="modal fade" role="dialog">
	<form action="/nodes/saveInputSubmit" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">New input email</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="email">Input email</label>
						<input id="email" type="email" name="email" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>
