<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" href="/nodes">Output emails</a>
		<a class="btn btn-small btn-default" href="/nodes/input">Input emails</a>
		<a class="btn btn-small btn-default" href="/nodes/delivery">Delivery</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">ID</th>
					<th class="text-center">From</th>
					<th class="text-center">Subject</th>
					<th class="text-center">Tries</th>
					<th class="text-center">Received</th>
					<th class="text-center">Error</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($emails as $email) { ?>
				<tr>
					<td class="text-center"><?=$email->id?></td>
					<td class="text-center"><?=$email->user?></td>
					<td class="text-center"><?=substr($email->subject,0,30)?></td>
					<td class="text-center"><?=$email->tries?></td>
					<td class="text-center"><nobr><?=date("M d h:i A", strtotime($email->inserted))?></nobr></td>
					<td class="text-center"><?=$email->message?></td>
					<td class="text-center nobr">
						<a class="btn btn-xs btn-default" href="/nodes/sendFromQuequeSubmit?id=<?=$email->id?>"><span class="glyphicon glyphicon-send" aria-hidden="true"></span></a>
						<a class="btn btn-xs btn-default" href="/nodes/removeFromQuequeSubmit?id=<?=$email->id?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal to add/edit a can response -->
<div id="newInputEmail" class="modal fade" role="dialog">
	<form action="/nodes/saveInputSubmit" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">New input email</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="email">Input email</label>
						<input id="email" type="email" name="email" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>
