<style type="text/css">
	.form-group{
		margin-top: 20px;
	}
</style>

<div class="row">
	<div class="col-xs-12">
		<form id="form" role="form" action="saveSubmit" method="POST">
			<!-- EMAIL -->
			<div class="form-group">
				<label for="email">Email</label>
				<input id="email" type="email" value="<?=$email?>" class="form-control" name="email" required />
			</div>

			<!-- NODE -->
			<div class="form-group">
				<label for="node">Node</label>
				<select id="node" name="node" class="form-control">
					<?php foreach($nodes as $n) { ?>
						<option value="<?=$n->key?>" <?php if($node==$n->key) echo 'selected="selected"'; ?>><?=$n->name?></option>
					<?php } ?>
				</select>
			</div>

			<!-- HOST -->
			<div class="form-group">
				<label for="host">Host</label>
				<input id="host" type="text" value="<?=$host?>" class="form-control" name="host" required />
			</div>

			<!-- USERNAME -->
			<div class="form-group">
				<label for="user">Username</label>
				<input id="user" type="text" value="<?=$user?>" class="form-control" name="user" required />
			</div>

			<!-- PASSWORD -->
			<div class="form-group">
				<label for="pass">Password</label>
				<input id="pass" type="text" value="<?=$pass?>" class="form-control" name="pass" required />
			</div>

			<!-- LIMIT -->
			<div class="form-group">
				<label for="limit">Daily limit</label>
				<input id="limit" type="number" value="<?=$limit?>" class="form-control" name="limit" required />
			</div>

			<!-- GROUP -->
			<div class="form-group">
				<label for="group">Group</label>
				(<small>apretaste, support, campaign, etc.</small>)
				<input id="group" type="text" value="<?=$group?>" class="form-control" name="group" required />
			</div>

			<div class="form-group">
				<input type="hidden" name="id" value="<?=$email?>"/>
				<a class="btn btn-default" href="/nodes">Cancel</a>
				<?php if($email) { ?>
					<a class="btn btn-danger" onclick="return confirm('Are you sure? There is no way back!');" href="/nodes/deleteSubmit?email=<?=$email?>">Delete</a>
				<?php } ?>
				<button class="btn btn-primary" type="submit">Submit</button>
			</div>
		</form>
	</div>
</div>
