<div class="row">
	<div class="col-xs-12">
		<?php if (isset($message) && $message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>
	</div>
</div>

<form action ="/contests/addPost" method="POST">
	<div class="row">
		<div class="col-xs-12">
			<div class="form-group">
				<label for="title">Title:</label>
				<input required type="text" class="form-control text" name="title" id="title" placeholder="title" title="Insert title">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-6">
			<div class="form-group" id="data_1">
				<label for="end_date">End date:</label>
				<div class="input-group date">
					<input id="end_date" type="hidden" name="end_date">
					<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
					<input id="end_date" type="text" class="form-control" value="<?= date("Y-m-d") ?>" name = "end_date">
				</div>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="form-group">
				<label for="end_hour">End hour:</label>
				<div class="input-group clockpicker" data-autoclose="true">
					<input id="end_hour" name="end_hour" type="text" class="form-control" value="08:00" >
					<span class="input-group-addon">
						<span class="fa fa-clock-o"></span>
					</span>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<div class="form-group">
				<label for="prize">Prize 1:</label>
				<input type="text" class="form-control text" name="prize1" id="prize1" placeholder="prize 1" title="Insert prize">
			</div>

			<div class="form-group">
				<label for="prize">Prize 2:</label>
				<input type="text" class="form-control text" name="prize2" id="prize2" placeholder="prize 2" title="Insert prize">
			</div>

			<div class="form-group">
				<label for="prize">Prize 3:</label>
				<input type="text" class="form-control text" name="prize3" id="prize3" placeholder="prize 3" title="Insert prize">
			</div>

			<div class="form-group">
				<label for="content">Explanation</label><br/>
				<textarea id="body" name="body"></textarea>
			</div>

			<div class="form-group">
				<a class="btn btn-default" href="/contests">Cancel</a>
				<button class="btn btn-primary" type="submit" onclick="return getcontent();">Save</button>
			</div>
		</div>
	</div>
</form>


<!-- SCRIPTS -->


<style type="text/css">
	.form-group{margin-top: 20px;}
</style>

<link href="/css/clockpicker.css" rel="stylesheet">
<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/clockpicker.js"></script>
<script src="/js/bootstrap-datepicker.js"></script>
<script>
	tinymce.init({
		selector: '#body',
		height: 500,
		theme: 'modern',
		setup : function(ed) {
			ed.on('keydown',function(ed, evt) {
				if ( tinymce.get('body').getContent().length + 1 > 100 * 1024){ // > 100 Kb
					return false;
				}
			});
		},
		plugins: [
			'advlist autolink lists link image charmap print preview hr anchor pagebreak',
			'searchreplace wordcount visualblocks visualchars code fullscreen',
			'insertdatetime media nonbreaking save table contextmenu directionality',
			'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc bdesk_photo'
		],
		toolbar1: 'undo redo | insert | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link emoticons codesample'
	});

	$(function(){
		$('#data_1 .input-group.date').datepicker({
			todayBtn: "linked",
			keyboardNavigation: false,
			forceParse: false,
			format: "yyyy-mm-dd",
			calendarWeeks: true,
			autoclose: true
		});

		$('.clockpicker').clockpicker();
	});
</script>
