<div class="row">
	<div class="col-xs-12">
		<?php if (isset($message) && $message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<form action ="/contests/editPost/<?= $contest->id ?>" method="POST">
			<div class="form-group">
				<label for="title">Title:</label>
				<input required type="text" class="form-control text" name="title" id="title" placeholder="title" title="Insert title" value="<?= $contest->title ?>">
			</div>

			<div class="row">
				<input id="end_date" type="hidden" name="end_date">
				<!-- datepicker -->
				<div class="col-lg-6">
					<div class="form-group" id="data_1">
						<label for="end_date">End date:</label>
						<div class="input-group date">
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
							<input id="end_date" type="text" class="form-control" value="<?= $contest->end_date ?>" name = "end_date">
						</div>
					</div>
				</div>

				<div class="col-lg-6">
					<div class="form-group">
						<label for="end_hour">End hour:</label>
						<div class="input-group clockpicker" data-autoclose="true">
							<input id="end_hour" name="end_hour" type="text" class="form-control" value="<?= $contest->hour ?>" >
							<span class="input-group-addon">
								<span class="fa fa-clock-o"></span>
							</span>
						</div>
					</div>
				</div>
			</div>

			<div class="form-group">
				<label for="prize">Prize 1:</label>
				<input type="text" class="form-control text" name="prize1" id="prize1" placeholder="prize 1" title="Insert prize" value="<?= $contest->prize1 ?>">
			</div>
			<div class="form-group">
				<label for="prize">Prize 2:</label>
				<input type="text" class="form-control text" name="prize2" id="prize2" placeholder="prize 2" title="Insert prize" value="<?= $contest->prize2 ?>">
			</div>
			<div class="form-group">
				<label for="prize">Prize 3:</label>
				<input type="text" class="form-control text" name="prize3" id="prize3" placeholder="prize 3" title="Insert prize" value="<?= $contest->prize3 ?>">
			</div>

			<div class="form-group">
				<label for="content">Explanation</label><br/>
				<textarea id="body" name="body"><?= $contest->body ?></textarea>
			</div>

			<div class="form-group">
				<label for="prize">Winner 1:</label>
				<input type="text" class="form-control text" name="winner1" id="winner1" placeholder="email of the winner" title="Insert winner" value="<?= $contest->winner1 ?>">
			</div>

			<div class="form-group">
				<label for="prize">Winner 2:</label>
				<input type="text" class="form-control text" name="winner2" id="winner2" placeholder="email of the winner" title="Insert winner" value="<?= $contest->winner2 ?>">
			</div>

			<div class="form-group">
				<label for="prize">Winner 3:</label>
				<input type="text" class="form-control text" name="winner3" id="winner3" placeholder="email of the winner" title="Insert winner" value="<?= $contest->winner3 ?>">
			</div>

			<div class="form-group">
				<a class="btn btn-default" href="/contests">Cancel</a>
				<button class="btn btn-primary" type="submit" onclick="return getcontent();">Save</button>
			</div>
		</form>
	</div>
</div>


<!-- SCRIPTS -->


<style type="text/css">
	.form-group{
		margin-top: 20px;
	}
</style>


<link href="/css/clockpicker.css" rel="stylesheet">
<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/clockpicker.js"></script>
<script src="/js/bootstrap-datepicker.js"></script>
<script>
	tinymce.init({
		selector: '#body',
		height: 500,
		theme: 'modern',
		plugins: [
			'advlist autolink lists link image charmap print preview hr anchor pagebreak',
			'searchreplace wordcount visualblocks visualchars code fullscreen',
			'insertdatetime media nonbreaking save table contextmenu directionality',
			'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc bdesk_photo'
		],
		toolbar1: 'undo redo | insert | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link emoticons codesample'
	});

	$(function(){
		$('#data_1 .input-group.date').datepicker({
			todayBtn: "linked",
			keyboardNavigation: false,
			forceParse: false,
			format: "yyyy-mm-dd",
			calendarWeeks: true,
			autoclose: true
		});

		$('.clockpicker').clockpicker();
	});
</script>
