<div class="row">
	<div class="col-xs-12">
		<?php if (isset($message) && $message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Title</th>
					<th>End date</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($contests as $contest) { ?>
				<tr>
					<td><?= $contest->title ?></td>
					<td><?= $contest->end_date ?></td>
					<td class="text-right">
						<a class="btn btn-xs btn-default" href="/contests/view/<?= $contest->id ?>"><span class="glyphicon glyphicon-zoom-in"></span></a>
						<a class="btn btn-xs btn-default" href="/contests/edit/<?= $contest->id ?>"><span class="glyphicon glyphicon-pencil"></span></a>
						<a class="btn btn-xs btn-default" onclick ="return confirm('Are you sure?');" href="/contests/delete/<?= $contest->id ?>"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
</div>
