<div class="row">
	<div class="col-xs-12">
		<!-- COUPONS USAGE -->
		<div id="couponsUsage" style="width:100%; margin-bottom:50px;"></div>

		<!-- MANAGE COUPONS -->
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Coupon</th>
					<th class="text-center">New Users</th>
					<th class="text-center">Expires</th>
					<th class="text-center">Limit</th>
					<th class="text-center">Credits</th>
					<th class="text-center">Inserted</th>
					<th class="text-center"></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($coupons as $c) { ?>
				<tr>
					<td class="text-center"><?= $c->coupon ?></td>
					<td class="text-center"><?= $c->rule_new_user ?></td>
					<td class="text-center"><?= $c->rule_deadline ?></td>
					<td class="text-center"><?= $c->rule_limit ?></td>
					<td class="text-center"><?= $c->prize_credits ?></td>
					<td class="text-center"><?= $c->inserted ?></td>
					<td class="text-center"><a class="btn btn-xs btn-default" onclick="return confirm('Are you sure to delete?');" href="/admin/submitDeleteCoupon?coupon=<?=$c->coupon?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>


<!-- MODALS -->


<div id="newCoupon" class="modal fade" role="dialog">
	<form action="/admin/submitNewCoupon" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">New coupon</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="coupon">Coupon</label>
						<input id="coupon" type="text" name="coupon" class="form-control" required />
					</div>

					<div class="form-group">
						<label for="rule_new_user">Only valid for new users?</label>
						<select id="rule_new_user" name="rule_new_user" class="form-control">
							<option value="0">No</option>
							<option value="1">Yes</option>
						</select>
					</div>

					<div class="form-group">
						<label for="rule_deadline">Expiration date (if any)</label>
						<input id="rule_deadline" type="date" name="rule_deadline" class="form-control" />
					</div>

					<div class="form-group">
						<label for="rule_limit">Max number of coupons that can be used</label>
						<input id="rule_limit" type="text" name="rule_limit" value="0" class="form-control" required />
					</div>

					<div class="form-group">
						<label for="prize_credits">Amount of credit as reward</label>
						<input id="prize_credits" type="number" name="prize_credits" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>


<!-- SCRIPT -->


<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(couponsUsage);
	function couponsUsage() {
		var data = google.visualization.arrayToDataTable([
			['Coupon', 'Number', {role: 'annotation'}],
			<?php foreach ($numberCouponsUsed as $data) { ?>
				['<?=$data['coupon']; ?>',<?=$data['usage']; ?>,<?=$data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.BarChart(document.getElementById('couponsUsage'));
		chart.draw(data, options);
	}
</script>
