<div class="row">
	<div class="col-xs-12">
		<form action="#" method="get">
			<div class="input-group">
				<input required type="email" class="form-control" name="email" value="<?=$email?>" placeholder="Email">
				<span class="input-group-btn">
					<button type="submit" class="btn btn-success">Search</button>
				</span>
			</div>
		</form>

		<?php if(empty($delivery) && $email) { ?>
			<p style="color:#B4524B; margin-top:20px;">User <?=$email?> do not exist.</p>
		<?php } ?>

		<?php if($delivery) { ?>
		<br/><br/>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Date</th>
					<th>Service</th>
					<th>Environment</th>
					<th>Sent code</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($delivery as $d) { ?>
				<tr>
					<td class="nobr"><?=date("m/d h:i A", strtotime($d->request_date))?></td>
					<td><?=$d->request_service?> <?=$d->request_subservice?> <?=$d->request_query?></td>
					<td><?=$d->environment?></td>
					<td><?=$d->delivery_code?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		<?php } ?>
	</div>
</div>
