<div class="row">
	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Email</th>
					<th class="text-center">Password</th>
					<th class="text-center">Limits</th>
					<th class="text-center">Last</th>
					<th class="text-center">Auth</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($gmails as $gmail) { ?>
				<tr style='background-color:<?= $gmail->active ? "" : "#FFB0A2" ?>'>
					<td class="text-center"><?=$gmail->email?></td>
					<td class="text-center"><?=$gmail->password?></td>
					<td class="text-center"><?=$gmail->sent?>/<?=$gmail->limit?></td>
					<td class="text-center"><?=date('m/d/Y H:i:s', strtotime($gmail->last_sent))?></td>
					<td class="text-center">
						<?php if($gmail->auth) { ?>
							<a class="btn btn-xs btn-primary" target="_blank" href="<?=$gmail->auth?>">Auth</a>
						<?php } ?>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>


<!-- MODALS -->


<div id="addCode" class="modal fade" role="dialog">
	<form action="/admin/gmailSubmit" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add Gmail authorization code</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="email">Email</label>
						<input id="email" type="email" name="email" class="form-control" required />
					</div>
					<div class="form-group">
						<label for="code">Code</label>
						<input id="code" type="text" name="code" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>
