<!-- Location: Core/app/views/admin/index.phtml -->

<div class="row">
	<div class="col-xs-12">
		<h1>Admin</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-3">
		<p>Gauge #1</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #2</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #3</p>
	</div>
	<div class="col-xs-3">
		<p>Gauge #4</p>
	</div>
</div>

<div class="row">
	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Menu</div>
			<div class="panel-body">
				<a href="raffle">Raffle</a><br/>
				<a href="ads">Ads</a><br/>
				<a href="jumper">Jumper</a><br/>
			</div>
		</div>
	</div>
</div>
