<div class="row">
	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Email</th>
					<th class="text-center">Received</th>
					<th class="text-center">Environment</th>
					<th class="text-center"></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($emails as $email) { ?>
				<tr>
					<td class="text-center"><?=$email->email?></td>
					<td class="text-center"><?=$email->received?></td>
					<td class="text-center"><?=$email->environment?></td>
					<td class="text-center"><a class="btn btn-xs btn-default" onclick="return confirm('Are you sure to delete?');" href="/admin/submitDeleteInputEmail?email=<?=$email->email?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>


<!-- MODALS -->


<div id="newInputEmail" class="modal fade" role="dialog">
	<form action="/admin/submitNewInputEmail" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">New input email</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="email">Email</label>
						<div class="input-group">
							<input id="email" type="text" name="email" class="form-control" required />
							<span class="input-group-addon">@gmail.com</span>
						</div>
					</div>
					<div class="form-group">
						<label for="environment">Environment</label>
						<input id="environment" type="text" name="environment" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>
