<div class="row">
    <div class="col-xs-12">
        <h1>Jumper</h1>
    </div>   
</div>

<div class="row">
    <div class="col-xs-12">
        <table id="adsTable" class="table">
			<thead>
				<th>Email</th>
				<th class="text-center">Last Usage</th>
				<th class="text-center">Emails Sent</th>
				<th class="text-center">Errors</th>
				<th class="text-center">Block Domains</th>
				<th class="text-center"></th>
			</thead>
			<tbody>
			<?php 
				if(! empty($jumperData)){
				foreach ($jumperData as $jumperView){ ?>
				<tr <?php if($jumperView['active'] == 0) echo 'class="danger"'; ?>>
					<td><?php echo $jumperView['email']; ?></td>
					<td class="text-center"><?php echo $jumperView['lastUsage']; ?></td>
					<td class="text-center"><?php echo $jumperView['emailsSent']; ?></td>
					<td class="text-center"><?php echo $jumperView['errors']; ?></td>
					<td class="text-center">
						<?php  
							$blockDomain = explode(",",$jumperView['blockDomains']);
							foreach($blockDomain as $blockDomainItem)
								echo $blockDomainItem.", ";
						?>
					</td>
					<td class="text-center"><a class="btn btn-xs btn-default" onclick="return confirm('Toggle status?');" href="toggleStatus?email=<?php echo $jumperView['email']; ?>">Toggle status</a></td>
				</tr>
			<?php }} ?>
			</tbody>
        </table>
    </div>
</div>
