<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($createraffleError)) { ?>
			<br/>
			<div class="alert alert-danger"><?php echo $createraffleError; ?></div>
		<?php } ?>

		<?php if( ! empty($createraffleMesssage)) { ?>
			<br/>
			<div class="alert alert-success"><?php echo $createraffleMesssage; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h1>Insert Raffle</h1>
    </div>   
</div>

<div class="row">
	<div class="col-xs-12">
		<form role="form" action="submitRaffle" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<h2>Upload Picture of the Raffle</h2>
				<input type="file" name="pictureRaflle" >
				<p class="help-block">Picture .png and size:600px by 100px</p>
			</div>
			<div class="form-group">
				<h4>Description of the Raffle<h4>
						<input type="text" name="raffleDescription" size="35"/>
			</div>
			<div class="form-group">
				<input type="date" name="raffleStartDate" placeholder="From"/>
				<input type="date" name="raffleFinishDate" placeholder="To"/>
			</div>
			
			<button type="submit" class="btn btn-default">Create Raffle</button>
		</form>
	</div>
</div>