<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($adsError)) { ?>
			<br/>
			<div class="alert alert-danger"><?php echo $adsError; ?></div>
		<?php } ?>

		<?php if( ! empty($adsMesssage)) { ?>
			<br/>
			<div class="alert alert-success"><?php echo $adsMesssage; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h1>Insert Raffle</h1>
    </div>   
</div>

<div class="row">
	<div class="col-xs-12">
		<form role="form" action="submitRaffle" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<h4>Description of the Rafflo<h4>
						<input type="text" name="raffleDescription" size="35"/>
			</div>
			<div class="form-group">
				<input type="date" name="raffleStartDate" placeholder="From"/>
				<input type="date" name="raffleFinishDate" placeholder="To"/>
			</div>
		</form>
	</div>
</div>