<div class="row">
	<div class="col-xs-12">
		<table id="servicesTable" class="table">
			<thead>
				<tr>
					<th>Details</th>
					<th class="text-center">Category</th>
					<th class="text-center">Inserted</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($services as $service) {
				?>
				<tr>
					<td>
						<b><?=$service->name?></b>
						<?php if(empty($service->listed)) echo '<span class="label label-default">hidden</span>'; ?>
						<br/>
						<?=$service->creator_email?>
					</td>
					<td class="text-center"><?=$service->category?></td>
					<td class="text-center"><?=date("Y/m/d H:i:s", strtotime($service->insertion_date))?></td>
					<td class="text-center">
						<a class="btn btn-default" target="_blank" href="/run/display?subject=<?=$service->name?>">Run</a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
