ALTER TABLE _escuela_course
  ADD COLUMN category
  ENUM('SOCIEDAD','NEGOCIOS','MEDICINA','INFORMATICA',
       'INGENIERIA','LETRAS','ARTES','FILOSOFIA','SALUD',
       'POLITICA','TECNICA','OTRO');
