<div class="row">
	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Owner</th>
					<th class="text-center">Paid</th>
					<th class="text-center">Title</th>
					<th class="text-center">Clicks</th>
					<th class="text-center">Impressions</th>
					<th class="text-center">Inserted</th>
					<th class="text-center">Expires</th>
					<th class="text-right"></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($ads as $ad) { ?>
				<tr>
					<td class="text-left"><?= $ad->owner ?></td>
					<td class="text-center"><?= $ad->paid ?></td>
					<td><?= $ad->icon ?> <?= $ad->title ?></td>
					<td class="text-center"><?= $ad->clicks ?></td>
					<td class="text-center"><?= $ad->impressions ?></td>
					<td class="text-center"><?= date("m/d H:i", strtotime($ad->inserted)) ?></td>
					<td class="text-center"><?= date("m/d H:i", strtotime($ad->expires)) ?></td>
					<td class="text-center">
						<a class="btn btn-default" target="_blank" href="/run/display?subject=PUBLICIDAD VER <?= $ad->id ?>">View</a>
						<!-- <a class="btn btn-default" href="/advertisement/report?id=<?= $ad->id ?>">Report</a> -->
						<a class="btn btn-default" href="/advertisement/update?id=<?= $ad->id ?>">Edit</a>
						<a class="btn btn-danger" href="/advertisement/delete?id=<?= $ad->id ?>">Stop</a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
