<?php if ( ! empty($message)): ?>
	<div class="alert alert-success" role="alert"><?= $message; ?></div>
<?php endif; ?>

<div id="error-captcha" class="alert alert-danger" style="display:none;" role="alert">El texto que escribi&oacute; no es el mismo de la imagen.</div>

<div class="row">
	<div class="col-xs-6">
		<form action="invitar/process" method="POST" data-toggle="validator" role="form">
			<div class="form-group">
				<label class="control-label" for="name">Su nombre, para sepan quien les invita</label>
				<input required id="name" class="form-control" type="text" name="name" placeholder="Escriba su nombre"/>
			</div>

			<div class="form-group">
				<label class="control-label" for="email">Su email, para enviarte una confirmaci&oacute;n</label>
				<input required id="email" class="form-control" type="email" name="email" placeholder="Escriba su email" data-error="Email invalido"/>
			</div>

			<div id="guest-group" class="form-group">
				<label class="control-label" for="guest">El email de la persona a invitar</label>
				<input required id="guest" class="form-control" type="email" name="guest" placeholder="Email de su amigo en Cuba" data-error="Email invalido"/>
			</div>

			<div class="form-group">
				<label class="control-label" for="captcha">Escriba el texto que ve en la imagen</label>
				<div class="input-group">
					<input required id="captcha" class="form-control" type="text" name="captcha" style="height: 42px;">
					<span class="input-group-addon" style="padding: 0px;"><img class="rounded" style="margin: 0px;" id="captchaimg" style="margin: 5px;" src="invitar/captcha"></span>
					<span class="input-group-btn">
						<button style="height: 42px;" class="btn btn-default" type="button" onclick="$('#captchaimg').attr('src','invitar/captcha?rand='+mt_rand(1,9000));$('#captcha').val('');">
							<span class="glyphicon glyphicon-refresh"></span>
						</button>
					</span>
				</div>
			</div>

			<div class="text-center">
				<button class="btn btn-success btn-lg" type="submit" onclick="return checkCaptcha();">Enviar invitaci&oacute;n</button>
			</div>
		</form>
	</div>

	<div class="col-xs-6">
		<p>Apretaste permite acceder a Internet mediante el email, y es &uacute;til para aquellas personas que viven en lugares de escasa conectividad. Seguramente tienes amigos que viven en lugares como estos, como por ejemplo Cuba, y quisieras mejorarle sus vidas cuando usen Apretaste. Pues mediante este formulario puedes invitarlos. Solo debes ingresar los siguientes datos:</p>
	</div>
</div>

<!-- new element that will be created to add new emails -->
<div id="guest-clone" class="form-group" style="display:none;">
	<div class="input-group">
		<input required class="form-control" type="email" name="guest" placeholder="Tiene mas amigos? Esciba su email aqui" data-error="Email invalido"/>
		<span class="input-group-btn">
			<button class="btn btn-default btn-remove" type="button" onclick="$(this).parents('.form-group').remove();">
				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
			</button>
		</span>
	</div>
</div>

<script>
	$(document).ready(function(){
		// add another email automatically
		$("#guest").keyup(addGuest);
	});

	//add another email automatically
	function addGuest(){
		var guestclone = $('#guest-clone').clone().removeAttr('id');
		var email = $(this).val();
		if(checkEmail(email)) {
			$(this).parents('.form-group').after(guestclone);
			guestclone.slideDown('slow');
			guestclone.find('input').keyup(addGuest);
			$(this).unbind('keyup');
		}
	}

	// check email
	function checkEmail(email) {
		return email.match(/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/);
	}

	// return random number for the captcha
	function mt_rand(min,max) {
		var argc=arguments.length;
		if(argc===0) {
			min=0;
			max=2147483647;
		}else if(argc===1) {
			throw new Error('Warning: mt_rand() expects exactly 2 parameters, 1 given');
		}
		return Math.floor(Math.random()*(max-min+1))+min;
	}

	// check if the captcha is valid by Ajax
	function checkCaptcha() {
		var ret = false;
		var text = $('#captcha').val();
		$.ajax({
			url: "invitar/check?text="+text,
			async: false
		}).done(function(data) {
			ret = $.trim(data) == "true";
			if( ! ret) $('#error-captcha').show();
		});	
		return ret;
	}
</script>