<?php 
	$wwwhttp = $this->di->get('path')['http'];
	if( ! isset($name)) $name = ""; 
	if( ! isset($email)) $email = "";
	if(isset($message)) echo '<div class="alert alert-success" role="alert">Gracias por traer a sus amigos y familia en Cuba a disfrutar la internet. <b>Sus contactos han sido invitados correctamente.</b> Le hemos mandado un email de agradecimiento. Si&eacute;ntase libre de invitar incluso m&aacute;s personas usando este formulario.</div>'; 
	if(isset($already)) echo '<div class="alert alert-warning" role="alert">La persona que usted invit&oacute; ya usa Apretaste. Si&eacute;ntase libre de invitar m&aacute;s amigos o familia usando este formulario.</div>';
?>
<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Invite a su gente en Cuba a usar internet</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Tiene amigos y familia en Cuba? Nosotros les conectamos a la internet! Invitelo a traves de esta pagina.">
		<meta name="author" content="Salvi Pascual">
		<link rel="icon" href="<?= $wwwhttp; ?>/images/apretaste.icon.png">

		<!-- Open Graph data -->
		<meta property="og:url" content="https://apretaste.com/invitar" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="Invite su gente en Cuba a la internet" />
		<meta property="og:description" content="Tiene amigos y familia en Cuba? Nosotros les conectamos a la internet! Invitelo a traves de esta pagina." />
		<meta property="og:image" content="<?php echo $wwwhttp; ?>/images/internet.jpg" />

		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary">
		<meta name="twitter:site" content="@apretaste">
		<meta name="twitter:title" content="Invite su gente en Cuba a la internet">
		<meta name="twitter:description" content="Tiene amigos y familia en Cuba? Nosotros les conectamos a la internet! Invitelo a traves de esta pagina.">
		<meta name="twitter:creator" content="@apretaste">
		<meta name="twitter:image" content="<?php echo $wwwhttp; ?>/images/internet.jpg">

		<!-- jQuery -->
		<script src="<?= $wwwhttp; ?>/js/jquery.js"></script>

		<!-- Bootstrap Core CSS -->
		<link href="<?= $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap.min.js"></script>

		<!-- Bootstrap plugins -->
		<script src="<?= $wwwhttp; ?>/js/validator.min.js"></script>

		<!-- Font awesome -->
		<link rel="stylesheet" href="<?= $wwwhttp; ?>/font-awesome/css/font-awesome.min.css">

		<!-- Custom stylesheets -->
		<link href="<?= $wwwhttp; ?>/css/basics.css" rel="stylesheet">
		<style>
			body {
				margin: 40px 0px;
			}

			.control-label {
				font-weight: normal;
				text-transform: uppercase;
				font-size: large;
				margin-top: 30px;
			}
			
			.label-support {
				color: gray;
				font-size: small;
			}
		</style>
	</head>

	<body>
		<!-- Load Facebook SDK for JavaScript -->
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1790556551215273";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

		<!-- Load Twitter SDK-->
		<script>window.twttr = (function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0],
		    t = window.twttr || {};
		  if (d.getElementById(id)) return t;
		  js = d.createElement(s);
		  js.id = id;
		  js.src = "https://platform.twitter.com/widgets.js";
		  fjs.parentNode.insertBefore(js, fjs);
		  t._e = [];
		  t.ready = function(f) {t._e.push(f);};
		  return t;
		}(document, "script", "twitter-wjs"));</script>

		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<img src="<?= $wwwhttp ?>/images/apretaste.logo.big.transp.png" alt="Logo de Apretaste" style="width:200px;">
					<p class="lead">INVITE A SU GENTE EN CUBA <br class="hidden-sm hidden-md hidden-lg"> A <a onclick="$('#how').slideDown();" href="#">NAVEGAR POR INTERNET</a></p>
					<p id="how" class="label-support" style="display:none;"><a href="https://apretaste.com/bienvenido" target="_blank">Apretaste</a> permite utilizar Google, Wikipedia, Noticias, Redes Sociales y m&aacute;s de 40 otras websites desde Cuba, usando Nauta.</p>
				</div>

				<div class="col-xs-12">
					<form action="<?= $wwwhttp ?>/invitar/process" method="POST" data-toggle="validator" role="form">
						<div class="form-group">
							<label class="control-label" for="name"><b>Paso #1:</b> Escriba su nombre</label>
							<p class="label-support">Usaremos su nombre para firmar la invitaci&oacute;n</p>
							<input required id="name" class="form-control" type="text" name="name" value="<?= $name ?>" placeholder="Periquito Perez"/>
						</div>
			
						<div class="form-group">
							<label class="control-label" for="email"><b>Paso #2:</b> Escriba su email</label>
							<p class="label-support">Usaremos su email para mandarle una confirmaci&oacute;n</p>
							<input required id="email" class="form-control" type="email" name="email" value="<?= $email ?>" placeholder="yo@gmail.com" data-error="Email invalido"/>
						</div>
			
						<div id="guest-group" class="form-group">
							<label class="control-label" for="guest"><b>Paso #3:</b> Email del invitado en Cuba</label>
							<p class="label-support">Este es la persona que recibir&aacute; acceso a internet</p>
							<input required id="guest" class="form-control" type="email" name="guest" placeholder="invitado@nauta.cu" data-error="Email invalido"/>
						</div>
			
						<div class="form-group">
							<label class="control-label" for="captcha"><b>Paso #4:</b> Escriba el texto en la imagen</label>
							<p id="error-captcha" class="label-support" style="display:none; color:#A94455;">El texto que escribi&oacute; no es el mismo de la imagen.</p>
							<div class="input-group">
								<input required id="captcha" class="form-control" type="text" name="captcha" style="height: 42px;">
								<span class="input-group-addon" style="padding: 0px;"><img class="rounded" style="margin: 0px;" id="captchaimg" style="margin: 5px;" src="<?= $wwwhttp ?>/invitar/captcha"></span>
								<span class="input-group-btn">
									<button style="height: 42px;" class="btn btn-default" type="button" onclick="$('#captchaimg').attr('src','invitar/captcha?rand='+mt_rand(1,9000));$('#captcha').val('');">
										<span class="glyphicon glyphicon-refresh"></span>
									</button>
								</span>
							</div>
						</div>
			
						<div class="text-center">
							<button id="submitBtn" class="btn btn-success btn-lg" type="submit" onclick="return checkCaptcha();">Enviar invitaci&oacute;n</button>
						</div>
					</form>
					<br/><br/><br/>
				</div>
				
				<div class="col-xs-12 text-center">
					<p class="lead">AY&Uacute;DENOS A REGAR LA VOZ</p>
					<p class="label-support">Comparta en Facebook y Twitter y ayude a miles de Cubanos a conocer la internet.</p>
				</div>

				<div class="col-xs-6 text-right">
					<!-- Facebook share button-->
					<div class="fb-share-button" data-href="https://apretaste.com/invitar" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https//apretaste.com/invitar&src=sdkpreparse">Compartir</a></div>
				</div>
				<div class="col-xs-6 text-left">
					<!-- Twitter share button-->
					<a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Lo ultimo que trajo el barco! Invita a tu familia y amigos a conectarse gratis a la internet desde Cuba" data-size="large">Tweet</a>
				</div>
			</div>
		</div>

		<script type="text/javascript">
			// return random number for the captcha
			function mt_rand(min,max) {
				var argc=arguments.length;
				if(argc===0) {
					min=0;
					max=2147483647;
				}else if(argc===1) {
					throw new Error('Warning: mt_rand() expects exactly 2 parameters, 1 given');
				}
				return Math.floor(Math.random()*(max-min+1))+min;
			}

			// check if the captcha is valid by Ajax
			function checkCaptcha() {
				// check if the captcha is right
				var ret = false;
				var text = $('#captcha').val();
				$.ajax({
					url: "<?= $wwwhttp ?>/invitar/check?text="+text,
					async: false
				}).done(function(data) {
					ret = $.trim(data) == "true";
					if( ! ret) $('#error-captcha').show();
				});	

				// if right, show loading
				if(ret) {
					$('#submitBtn').html("Invitando ...");
				}

				return ret;
			}
		</script>
	</body>
</html>

