<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<p class="lead">GRACIAS POR SU COMPRA</p>

			<p>Su compra de <b><?= $credits ?> cr&eacute;ditos</b> por un valor de $<?= $amount ?> ha sido procesada correctamente, y los cr&eacute;ditos agregados a su cuenta. Con estos cr&eacute;ditos, puede comprar en la app de Apretaste, as&iacute; como en las apps de Piropazo y Pizarra y otros servicios de nuestra plataforma.</p>

			<p>Le hemos mandado un email de confirmaci&aacute;n, que tambi&eacute;n le servir&aacute; como recibo. Si tiene alguna duda, por favor pongase en contacto con nuestro <a href="mailto:soporte@apretaste.org">equipo de soporte</a>, o escribamos por <a href="https://www.facebook.com/apretaste">facebook</a> o <a href="https://twitter.com/apretaste">twitter</a>.</p>

			<a class="btn btn-success" href="/topup">Atr&aacute;s</a>
		</div>
	</div>
</div>