<div class="row">
	<div class="col-xs-12">
		<?php if (isset($message) && $message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Code</th>
					<th>Name</th>
					<th>Price</th>
					<th>Shipping price</th>
					<th>Credits</th>
					<th>Agency</th>
					<th>Owner</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($products as $product) { ?>
					<tr id = "<?= $product->code ?>">
						<td><?= $product->code ?></td>
						<td><?= $product->name ?></td>
						<td><?= $product->price ?></td>
						<td><?= $product->shipping_price ?></td>
						<td><?= $product->credits ?></td>
						<td><?= $product->agency ?></td>
						<td><a href="mailto:<?= $product->owner ?>"><?= $product->owner ?></a></td>
						<td class="text-right">
							<?php if ($product->active) {?>
								<a onclick="toggleActivation('<?= $product->code ?>');" class="btn btn-xs btn-default"><span class="toggle-active-icon glyphicon glyphicon-check"></span></a>
							<?php } else {?>
								<a onclick="toggleActivation('<?= $product->code ?>');" class="btn btn-xs btn-default"><span class="toggle-active-icon glyphicon glyphicon-unchecked"></span></a>
							<?php } ?>
							<a href="/market/marketDetail/<?= $product->code ?>" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-pencil"></span></a>
							<a onclick ="return confirm('Are you sure?');" href="/market/marketDelete/<?= $product->code ?>" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-trash"></span></a>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>


<!-- MODALS -->


<!-- New product modal form -->
<div id="newProductForm" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">New product</h4>
			</div>
			<form role="form" action = "/market/marketNewProduct" method = "post" enctype="multipart" data-toggle="validator">
				<div class="modal-body">
					<div class="form-group">
						<label for="edtName">Name</label>
						<input required type="text" class="form-control text" name="edtName" id="edtName" placeholder="name of the product" title="Insert name of the product">
					</div>

					<div class="form-group">
						<label for="edtDesc">Description</label>
						<textarea class="form-control" name="edtDesc" id="edtDesc"></textarea>
					</div>

					<div class="form-group">
						<label for="edtCategory">Category</label>
						<select required class="form-control" name="edtCategory" id="edtCategory">
							<option value="mobile">Mobile</option>
							<option value="accessory">Accessory</option>
							<option value="computer">Computer</option>
							<option value="peripheral">Peripheral</option>
							<option value="clothe">Clothe</option>
							<option value="service">Service</option>
						</select>
					</div>
					<div class="form-group">
						<label for="edtPrice">Pricing</label>
						<table>
							<tr>
								<td><span>Price:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtPrice" id="edtPrice"></td>
								<td><span>&nbsp;Shipping:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtShippingPrice" id="edtShippingPrice"></td>
								<td><span>&nbsp;Credits:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtCredits" id="edtCredits"></td>
						</table>
					</div>

					<div class="form-group">
						<label for="edtAgency">Agency</label>
						<input required type="text" class="form-control text" name="edtAgency" id="edtAgency" placeholder="name of the agency" title="Insert name of the product">
					</div>

					<div class="form-group">
						<label for="edtOwner" class="control-label">Owner</label>
						<input required type="email" class="form-control" name="edtOwner" id="edtOwner"placeholder="Email" data-error="Bruh, that email address is invalid" title="Insert the email of the product's owner">
						<div class="help-block with-errors"></div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="submit" name="btnInsert" class="btn btn-primary">Insert</button>
				</div>
			</form>
		</div>
	</div>
</div>


<script>
	function toggleActivation(code)
	{
		jQuery.ajax({
			url: "/market/marketToggleActivation",
			type: "POST",
			async: false,
			data: {code: code},
			complete: function(res, status){
				if ( status == "success" || status == "notmodified" ){
					if (res.responseText == '1')
					{
						$("#"+code+" span.toggle-active-icon").attr('class', 'toggle-active-icon glyphicon glyphicon-check');
						$("#"+code).attr('class', 'product-active');
						$.notify({
							icon: 'glyphicon glyphicon-check',
							message: 'The product <b>'+ code + '</b> was activated'
						},
						{
							type: 'success',
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
					}
					else
					{
						$("#"+code+" span.toggle-active-icon").attr('class', 'toggle-active-icon glyphicon glyphicon-unchecked');
						$("#"+code).attr('class', 'product-non-active');
						$.notify({
							icon: 'glyphicon glyphicon-unchecked',
							message: 'The product  <b>'+ code + '</b> was deactivated'
						},
						{
							type: 'success',
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
					}
				}
			}
		});
	}
</script>
