<!-- Bio #1 - Salvi Pascual -->
<section id="salviPascual">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/salvi-pascual-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Salvi Pascual, Executive Director</p>
				<p><a href="mailto:salvi@apretaste.com">salvi@apretaste.com</a></p>
				<p class="lead big gray">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and strives to not be the worst pool player in the world.</p>
			</div>
		</div>
	</div>
</section>

<!-- Bio #2 - Ibis Arrastia -->
<section id="ibisArrastia">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/ibis-arrastia-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Ibis Arrastia, Program Manager</p>
				<p><a href="mailto:ibis@apretaste.com">ibis@apretaste.com</a></p>
				<p class="lead big gray">Ibis is an out-of-the-box thinker with more than two decades of software development experience, with an emphasis in product innovation and eCommerce.</p>
				<p class="lead big gray">As a speaker, educator, developer, entrepreneur, and local tech community leader, Ibis works to inspire others to innovate, invent, and reach new heights within the technology industry.</p>
				<p class="lead big gray">She is a strong advocate for more women in IT and plays an active role in training women and increasing the South Florida technical workforce.</p>
				
			</div>
		</div>
	</div>
</section>

<!-- Bio #3 - Daniella Bonilla -->
<section id="daniellaBonilla">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/daniella-bonilla-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Daniella Bonilla, Development Manager</p>
				<p><a href="mailto:daniella@apretaste.com">daniella@apretaste.com</a></p>
				<p class="lead big gray">
				A strong woman wears the look of confidence on her face,<br>
				Always doing whatever it takes to finish, seeking only first place,<br>
				The woman of strength competes with a sense of grace,<br>
				Understanding it's important to run a determination filled race. 
				</p>
				<p class="lead big gray">
				A strong woman works out every day,<br>
				Pride in her appearance she portrays,<br>
				And a woman of strength knows the way,<br>
				to keep in shape, conquering today. 
				</p>			
			</div>
		</div>
	</div>
</section>