<!-- Bio #1 - Salvi Pascual -->
<section id="salviPascual">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/salvi-pascual-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Salvi Pascual, Executive Director</p>
				<p><a href="mailto:salvi@apretaste.com">salvi@apretaste.com</a></p>
				<p class="lead big gray">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and strives to not be the worst pool player in the world.</p>
			</div>
		</div>
	</div>
</section>

<!-- Bio #2 - Ibis Arrastia -->
<section id="ibisArrastia">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/ibis-arrastia-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Ibis Arrastia, Program Manager</p>
				<p><a href="mailto:ibis@apretaste.com">ibis@apretaste.com</a></p>
				<p class="lead big gray">Ibis is an out-of-the-box thinker with more than two decades of software development experience, with an emphasis in product innovation and eCommerce.</p>
				<p class="lead big gray">As a speaker, educator, developer, entrepreneur, and local tech community leader, Ibis works to inspire others to innovate, invent, and reach new heights within the technology industry.</p>
				<p class="lead big gray">She is a strong advocate for more women in IT and plays an active role in training women and increasing the South Florida technical workforce.</p>
				
			</div>
		</div>
	</div>
</section>

<!-- Bio #3 - Daniella Bonilla -->
<section id="daniellaBonilla">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/team/daniella-bonilla-apretaste.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Daniella Bonilla, Development Manager</p>
				<p><a href="mailto:daniella@apretaste.com">daniella@apretaste.com</a></p>
				<p class="lead big gray">
				Daniella  is an urban planner and design professional, who has worked to improve the quality of life for many residents in South Florida. She has recently transitioned into the private sector, where she now specializes in wireless telecommunications infrastructure, and is hoping to expand her knowledge of wireless technology to further improve Apretaste's operations.
				</p>
				<p class="lead big gray">
				Daniella earned a Master’s Degree in Urban Planning from New York University, where she developed interests in economic development, sustainability, environmental justice and public art in urban revitalization. She is adamant about the advancement of human rights in the world, and has partnered with local non-profits to progress this objective. 
				</p>
				<p class="lead big gray">
				Daniella loves experiencing new cultures, exotic cuisine, archery, film and being ridiculously good at pool.	
				</p>
			</div>
		</div>
	</div>
</section>
