<!DOCTYPE html>
<html lang="en">
<head>
	<title>About Us | Apretaste</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Devoted activists working to connect thousands of Cubans to the Internet each month via accessible, effective and legal ways">
	<meta name="author" content="Salvi Pascual">

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary">
	<meta name="twitter:site" content="@apretaste">
	<meta name="twitter:title" content="We are connecting Cubans to the Web">
	<meta name="twitter:description" content="Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways">
	<meta name="twitter:creator" content="@apretaste">
	<meta name="twitter:image" content="<?php echo $wwwhttp; ?>/images/background.jpg">

	<!-- Open Graph data -->
	<meta name="fb:app_id" content="285099284865702" />
	<meta name="og:url" content="https://apretaste.com" />
	<meta name="og:type" content="website" />
	<meta name="og:locale" content="en_US" />
	<meta name="og:locale:alternate" content="es_ES" />
	<meta name="og:site_name" content="Apretaste" />
	<meta name="og:title" content="We are connecting Cubans to the Web" />
	<meta name="og:description" content="Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways" />
	<meta name="og:image" content="<?php echo $wwwhttp; ?>/images/background.jpg" />

	<link rel="icon" href="<?php echo $wwwhttp; ?>/images/apretaste.icon.png">
	<link rel="canonical" href="https://apretaste.com/aboutus.phtml">

	<!-- Bootstrap Core CSS -->
	<link href="<?php echo $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="<?php echo $wwwhttp; ?>/css/welcome.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="<?php echo $wwwhttp; ?>/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55b53cc3acee4add" async="async"></script>
	
	<!-- Navigation -->
	<a id="menu-toggle-language" href="bienvenido" class="btn btn-dark btn-lg toggle"><i class="fa fa-flag"></i></a>
	<a id="menu-donate" href="#donate" class="btn btn-dark btn-lg toggle"><i class="fa fa-life-ring"></i> Donate</a>
	<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>

	<nav id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
			<li class="sidebar-brand"><a href="#top">Apretaste</a></li>

			<li><a href="#problem">Problem</a></li>
			<li><a href="#idea">Solution</a></li>
			<li><a href="#mission">Mission</a></li>
			<li><a href="#services">Services</a></li>
			<li><a href="#testimonials">Testimonials</a></li>
			<li><a href="#donate">Donate</a></li>
			<li><a href="#contact">Contact Us</a></li>
			<li><a href="aboutus">About Us</a></li>
			<li><a href="http://apretasteen.wordpress.com" target="_blank">Blog</a></li>
		</ul>
	</nav>

	<!-- Header -->
	<header id="top" class="header">
		<div class="text-vertical-center">
			<div style="margin-top:-200px">
				<img id="main-logo-image" src="<?php echo $wwwhttp; ?>/images/apretaste.logo.big.transp.png" alt="Apretaste"><br/>
				<div id="motto">
					<h3 class="contrast">Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways</h3>
				</div>
				<br>
				<a href="#problem" class="btn btn-dark btn-lg">Find Out More</a>
				<a href="http://www.meetup.com/HeyCuba-Software-Developer-Meetup/" target="_blank" class="btn btn-light btn-lg">Be a Social Hacker</a>
			</div>
		</div>
	</header>

	<!-- Bio #1 - Salvi Pascual -->
	<section id="salviPascual">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/salvi-pascual-apretaste.png">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note">Salvi Pascual, Executive Director</p>
					<p class="lead big gray hidden-sm hidden-xs">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and strives to not be the worst pool player in the world.</p>
				</div>
			</div>
		</div>
	</section>

	<!-- Bio #2 - Ibis Arrastia -->
	<section id="ibisArrastia">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/ibis-arrastia-apretaste.png">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note">Ibis Arrastia, Program Manager</p>
					<p class="lead big gray hidden-sm hidden-xs">Ibis is an out-of-the-box thinker with more than two decades of software development experience, with an emphasis in product innovation and eCommerce.</p>
					<p class="lead big gray hidden-sm hidden-xs">
					As a speaker, educator, developer, entrepreneur, and local tech community leader, Ibis works to inspire others to innovate, invent, and reach new heights within the technology industry.</p>
					<p class="lead big gray hidden-sm hidden-xs">
					She is a strong advocate for more women in IT and plays an active role in training women and increasing the South Florida technical workforce.</p>
				</div>
			</div>
		</div>
	</section>

	<!-- Bio #3 - Daniella Bonilla -->
	<section id="daniellaBonilla">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/daniella-bonilla-apretaste.png">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note">Daniella Bonilla, Development Manager</p>
					<p class="lead big gray hidden-sm hidden-xs">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and strives to not be the worst pool player in the world.</p>
				</div>
			</div>
		</div>
	</section>


	<!-- Map -->
	<section id="contact" class="map">
		<img style="width:100%;" src="<?php echo $wwwhttp; ?>/images/map.png" alt="We are located at The LAB Miami"/>
	</section>

	<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h1>Contact Us</h1>
					<hr class="small">
					<p><b>Apretaste</b> at The LAB Miami</p>
					<p>400 Northwest 26th Street<br>Miami, FL 33127</p>
					<ul class="list-unstyled">
						<li><i class="fa fa-phone fa-fw"></i> (305) 457-1656</li>
						<li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:support@apretaste.com">support@apretaste.com</a></li>
					</ul>
					<br>
					<ul class="list-inline">
						<li>
							<a href="https://www.facebook.com/apretaste" target="_blank"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://twitter.com/apretaste" target="_blank"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
						</li>
					</ul>
					
					<br/>
					<p class="small">A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES BY CALLING TOLL-FREE WITHIN THE STATE 1-800-HELPFLA, OR VIA THE INTERNET AT WWW.800HELPFLA.COM. REGISTRATION DOES NOT IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY THE STATE.</p>
				</div>
			</div>
		</div>
	</footer>

	<form id="stripePaymentInfo" action="welcome/pay" method="post">
		<input type="hidden" id="stripeAmountInput" name="amount" value="10000" />
		<input type="hidden" id="stripeEmailInput" name="email" value="" />
		<input type="hidden" id="stripeTokenInput" name="stripeToken" value="" />
	</form>

	<!-- jQuery -->
	<script src="<?php echo $wwwhttp; ?>/js/jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="<?php echo $wwwhttp; ?>/js/bootstrap.min.js"></script>

	<!-- Stripe -->
	<script src="https://checkout.stripe.com/checkout.js"></script>

	<!-- Custom Theme JavaScript -->
	<script>
	// Closes the sidebar menu
	$("#menu-close").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Opens the sidebar menu
	$("#menu-toggle").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Scrolls to the selected menu item on the page
	$(function() {
		$('a[href*=#]:not([href=#])').click(function() {
			if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

				var target = $(this.hash);
				target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
				if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 1000);
					return false;
				}
			}
		});

		$('.tooltip-image').tooltip();
	});

	// Starts a payment with Stripe
	var handler = StripeCheckout.configure({
		key: '<?php echo $stripePushibleKey; ?>',
		image: 'https://s3.amazonaws.com/stripe-uploads/acct_16M6gnLYuWaxX6xTmerchant-icon-1436316635694-apretaste.icon.big.png',
		token: function(token) {
			// Using the token and amount to create the charge with a server-side script.
			$('#stripeTokenInput').val(token.id);
			$('#stripeEmailInput').val(token.email);
			$('#stripePaymentInfo').submit();
		}
	});

	// Donate $10
	$('#paymentBtn10').on('click', function(e) {
		$('#stripeAmountInput').val(1000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 1000
		});
		e.preventDefault();
	});

	// Donate $30
	$('#paymentBtn30').on('click', function(e) {
		$('#stripeAmountInput').val(3000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 3000
		});
		e.preventDefault();
	});

	// Donate $50
	$('#paymentBtn50').on('click', function(e) {
		$('#stripeAmountInput').val(5000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 5000
		});
		e.preventDefault();
	});

	// Donate $100
	$('#paymentBtn100').on('click', function(e) {
		$('#stripeAmountInput').val(10000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 10000
		});
		e.preventDefault();
	});

	// Donate $500
	$('#paymentBtn500').on('click', function(e) {
		$('#stripeAmountInput').val(50000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 50000
		});
		e.preventDefault();
	});

	// Close Checkout on page navigation
	$(window).on('popstate', function() {
		handler.close();
	});
	</script>

	<?php require_once "$wwwroot/lib/googleAnalyticsTracking.php"; ?>
</body>
</html>