<!DOCTYPE html>
<html lang="en">
<head>
	<title>Welcome to Apretaste</title>
	<link rel="icon" href="/images/apretaste_icon_16x16.png" sizes="16x16" type="image/png"/>
	<link rel="icon" href="/images/apretaste_icon_32x32.png" sizes="32x32" type="image/png"/>
	<link rel="icon" href="/images/apretaste_icon_64x64.png" sizes="64x64" type="image/png"/>
	<link rel="canonical" href="https://apretaste.com">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Access the internet via email. Social Network, News, Web, Entertaining y much more.">
	<meta name="author" content="Salvi Pascual">

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary">
	<meta name="twitter:site" content="@apretaste">
	<meta name="twitter:title" content="Conéctate a la internet por Nauta">
	<meta name="twitter:description" content="Revisa las Redes Sociales, Noticias, Web, Entretenimiento y mucho más. Todo desde la comodidad de tu casa, y gratuitamente.">
	<meta name="twitter:creator" content="@apretaste">
	<meta name="twitter:image" content="/images/FeatureGraphic.png">

	<!-- Open Graph data -->
	<meta name="fb:app_id" content="285099284865702" />
	<meta name="og:url" content="https://apretaste.com" />
	<meta name="og:type" content="website" />
	<meta name="og:locale" content="es_ES" />
	<meta name="og:locale:alternate" content="en_US" />
	<meta name="og:site_name" content="Apretaste" />
	<meta name="og:title" content="Conéctate a la internet por Nauta." />
	<meta name="og:description" content="Revisa las Redes Sociales, Noticias, Web, Entretenimiento y mucho más. Todo desde la comodidad de tu casa, y gratuitamente." />
	<meta name="og:image" content="/images/FeatureGraphic.png" />

	<!-- Bootstrap Core CSS -->
	<link href="/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="/css/welcome.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
	<!-- Navigation -->
	<a id="menu-toggle-language" href="bienvenido" class="btn btn-dark btn-lg toggle">ES</a>
	<a id="menu-download" href="#download" class="btn btn-dark btn-lg toggle"><i class="fa fa-android"></i> Download</a>
	<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>

	<nav id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
			<li class="sidebar-brand"><a href="#top">Apretaste</a></li>

			<li><a href="#problem">Problem</a></li>
			<li><a href="#idea">Solution</a></li>
			<li><a href="#mission">Mission</a></li>
			<li><a href="#services">Services</a></li>
			<li><a href="#testimonials">Testimonials</a></li>
			<li><a href="#team">Our Team</a></li>
			<li><a href="#download">Download</a></li>
			<li><a href="#contact">Contact Us</a></li>
			<li><a href="https://www.meetup.com/heycuba/" target="_blank">Do you code? <i class="fa fa-medkit"></i></a></li>
			<li><a href="http://blog.apretaste.com">Blog <i class="fa fa-bullhorn"></i></a></li>
			<li><a href="bienvenido">Espa&ntilde;ol</a></li>
		</ul>
	</nav>

	<!-- Header -->
	<header id="top" class="header">
		<div class="text-vertical-center">
			<div style="margin-top:-200px">
				<img id="main-logo-image" src="/images/apretaste_logo_500x180.png" alt="Apretaste"><br/>
				<div id="motto">
					<h3 class="contrast">Connecting thousands of Cubans to the internet using accessible, effective and legal ways</h3>
				</div>
				<br>
				<a href="#problem" class="btn btn-dark btn-lg">Find Out More</a>
				<a href="https://www.meetup.com/heycuba/" target="_blank" class="btn btn-light btn-lg">Wanna Help?</a>
			</div>
		</div>
	</header>

	<!-- The Problem -->
	<section id="problem">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive" src="/images/internet-in-cuba.png"/>
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note"><span class="green">2,800,000</span> Cubans only access email<br/>while only <span class="red">560,000</span> can surf the Web</p>
					<p class="lead big gray ">Most Cubans can only connect to a government email server (webmail.nauta.cu). All other webs are blocked from inside.</p>
				</div>
			</div>
		</div>
	</section>

	<!-- A great idea -->
	<section id="idea" class="idea bg-customized">
		<div class="container">
			<div class="row inner-space-vertical" style="padding-bottom:0px;">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<p class="lead high-note">Our App let's them access the internet using email</p>
					<ul class="lead">
						<li>Information travels inside an email</li>
						<li>Emails are encrypted to protect the user</li>
					</ul>
					<div class="blank-space-divider"></div>
					<a href="#download" class="btn btn-light"><i class="fa fa-android"></i> Download App</a>&nbsp;
					<button class="btn btn-dark" onclick="checkVideo();"><i class="fa fa-youtube-play"></i> Check Video</button>
				</div>

				<div class="blank-space-divider"></div>

				<div class="col-lg-7 col-md-7 col-sm-6 text-center">
					<img src="/images/ap-app.png">
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- try it-->
	<section id="tryit" class="tryit tryit-show" style="display:none;">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>Our service in motion</h2>
					<hr class="small">
					<div class="videoWrapper">
						<iframe id="youtubevideo" src="" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider visible-xs tryit-show" style="display:none;"></div>
	<hr class="featurette-divider hidden-xs tryit-show" style="display:none; margin-bottom:40px;">

	<!-- First Featurette -->
	<section id="mission" class="mainfeature">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>We are on a mission</h2>
					<hr class="small">
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-plug fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Connect isolated people to a new world of opportunities opening online</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-book fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Educate Cubans on the use of internet and the latests trends of technology</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-bullhorn fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Offer alternative information to those who only access the "official" media</p>
				</div>
			</div>

			<hr class="small">

			<div class="row">
				<div id="member" class="col-xs-12 text-center">
					<span class="lead">Do you share our goals?
						<a href="https://www.meetup.com/heycuba/" target="_blank" class="btn btn-dark btn-md">Become a member!</a>
					</span>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- Services -->
	<section id="services" class="services bg-customized">
		<div class="container">
			<div class="row text-center">
				<div class="col-lg-10 col-lg-offset-1">
					<h2>Most Popular Services</h2>
					<p style="color:#c1c1c1;">Out of more than 40 other services</p>
					<hr class="small">
					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/pizarra" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-users fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Social Net</strong></h4>
									<p>Allow people to share content</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/vuelos" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-plane fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Flights</strong></h4>
									<p>Aerial activity in Cuba</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="http://piropazo.com" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-heart fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Dating</strong></h4>
									<p>Help finding your other half</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/google" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-globe fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Web</strong></h4>
									<p>Browse the web openly</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/mapas" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-compass fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Maps</strong></h4>
									<p>Maps of locations and addresses</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/wikipedia" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-book fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Wikipedia</strong></h4>
									<p>Search the greatest encyclopedia</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<a href="/escuela" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-graduation-cap fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Education</strong></h4>
									<p>Online classes from your phone</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<a href="/traductor" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-language fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Translation</strong></h4>
									<p>Translate words and paragraphs</p>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xs-12" style="margin-top:15px;">
					<a class="btn btn-light btn-lg" target="_blank" href="/servicios">Enjoy Our Services!</a>
				</div>
			</div>
		</div>
	</section>

	<!-- Users -->
	<section id="users" style="background-color:#C1C1C1;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1 class="lead high-note black">Along the last years we have been<br class="hidden-xs"/> working hard to connect more Cubans</h1>
					<div id="visitors" style="width:100%;"></div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-center">
					<h3 class="black lead">With <?= number_format($visitorsPerMonth) ?> visitors per month, we believe we are on the right track</h3>
					<br/>
				</div>
			</div>
		</div>
	</section>

	<!-- Portfolio -->
	<section id="testimonials" class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-lg-offset-1 text-center">
					<h2>What people are saying</h2>
					<hr class="small">
					<div class="row">
							<div class="col-md-4 col-sm-6 text-left hidden-xs">
								<div class="bubble">Muchas gracias, que bueno que todavia hay personas que se preocupan por nosotros.</div>
								<p class="bubble-name">Danays</p>
							</div>
						<div class="col-md-4 col-sm-6 text-left">
							<div class="bubble">Apretaste es una gran oportunidad para quienes no disponemos de una coneccion activa, sino tan solo el correo y el telefono.</div>
							<p class="bubble-name">Miguel</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
							<div class="bubble">Me gusta Apretaste por su sinceridad y buena forma para optener información de conocimiento sobre consultas a enciclopedia compras y ventas + buenas relaciones entre usuarios.</div>
							<p class="bubble-name">Eusebio</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
							<div class="bubble">Gracias por existir y darnos esta oportunidad a los cubanos de a pie, espero que su trabajo se mantenga y que en Cuba no los bloqueen, sería una gran pérdida.</div>
							<p class="bubble-name">Carlos</p>
						</div>
						<div class="col-md-4 hidden-sm hidden-xs text-left">
							<div class="bubble">La posibilidad de usar los servicios de Apretaste me ha dejado frio. Ahora puedo acceder con facilidad a servicios q nosotros no podiamos, nuevamente gracias y que dios los bendiga.</div>
							<p class="bubble-name">Eladio</p>
						</div>
					</div>

					<div class="blank-space-divider"></div>

					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.miamiherald.com/news/business/technology/article65196697.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/miamiherald.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://event.on24.com/wcc/r/1237558/E17397506918D1078847DF56BBA25D2E" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/oreilly.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.telemundo51.com/noticias/cuba/Concurso-Hey-Cuba-Hackaton_TLMD---Miami-368985671.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/telemundo.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.sun-sentinel.com/business/small-business/fl-cuba-internet-company-20151130-story.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/sunsentinel.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.miaminewtimes.com/news/miami-company-helps-cubans-access-the-internet-through-their-email-8351534" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/newtimesmiami.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.jump-in.com.au/show/60minutes/stories/2014/september/a-cuban-revolution/" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/60minutes.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.elnuevoherald.com/noticias/mundo/america-latina/cuba-es/article64126537.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/nuevoherald.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://motherboard.vice.com/read/this-workaround-lets-26-million-cubans-surf-the-web" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/motherboard.png">
								</a>
							</div>
						</div>

						<?php /* hidden press to show on click */ ?>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.elmundo.es/economia/2016/02/15/56c192b0268e3ef5758b45bd.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/elmundo.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.martinoticias.com/content/apretaste-servicio-clasificados-por-email/31982.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/martinoticias.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.bizjournals.com/southflorida/news/2016/03/10/miami-hackathon-aims-to-improve-cuba-s-web-access.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/southflobizjournal.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.diariolasamericas.com/4842_locales/3628715_organizan-encuentro-programadores-miami-internet-cuba.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/diariolasamericas.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.14ymedio.com/blogs/generacion_y/Apretaste_7_1537716214.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/14ymedio.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.diariodecuba.com/cuba/1449255436_18591.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/diariodecuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="https://www.cubanet.org/noticias/cubano-organiza-hackathon-en-miami-por-mejorar-acceso-a-internet-en-la-isla/" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/cubanet.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.14ymedio.com/blogs/generacion_y/Apretaste_7_1537716214.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/generaciony.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="https://www.cibercuba.com/noticias/14ymedio/2016-02-15-una-hackathon-en-miami-para-facilitar-acceso-internet-cubanos" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/cibercuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://raicesblog.blogspot.com/2014/02/roots-of-hope-hosts-first-ever.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/hackathonforcuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://martinoticias.org/archive/one_thousand_800_online/14/97/129.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/1800online.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://hispz14.sched.org/event/d586fcd1fadff0e5b84fc2995eccfd20#.VCh10vnxqTU" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/hispanicize.png">
								</a>
							</div>
						</div>
					</div>

					<div class="row" id="morepressbtn">
						<div class="col-xs-12 text-center" style="margin-bottom: 30px">
							<button class="btn btn-dark btn-lg" onclick="$('.showmorepress').slideDown(); $('#morepressbtn').remove();">Even More Press</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Team -->
	<section id="team" class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-lg-offset-1 text-center">
					<h2>Meet our team</h2>
					<hr class="small">
					<div class="row">
						<div class="img-team col-md-4 col-sm-4 col-xs-6">
							<img class="img-circle team-member" src="/images/team/salvi.jpg"/>
							<h4>Salvi Pascual</h4>
							<p>Executive Director<br/><a href="mailto:salvi@apretaste.org">salvi@apretaste.org</a></p>
							<img src="/images/flags/us.png"/>
                            <a href="https://www.linkedin.com/in/salvipascual/"><img src="/images/linkedin.png"/></a>
						</div>
						<div class="img-team col-md-4 col-sm-4 col-xs-6">
							<img class="img-circle team-member" src="/images/team/ivon.jpg"/>
							<h4>Ivon Ramos</h4>
							<p>Director of Marketing<br/><a href="mailto:ivon@apretaste.org">ivon@apretaste.org</a></p>
							<img src="/images/flags/ve.png"/>
                            <a href="https://www.linkedin.com/in/iv%C3%B3n-ramos-aa648a177"><img src="/images/linkedin.png"/></a>
						</div>
						<div class="img-team col-md-4 col-sm-4 col-xs-12">
							<img class="img-circle team-member" src="/images/team/alex.jpg"/>
							<h4>Alex Maestre</h4>
							<p>Director of Technology<br/><a href="mailto:alex@apretaste.org">alex@apretaste.org</a></p>
							<img src="/images/flags/ve.png"/>
						</div>
					</div>

					<div class="row" style="margin: 20px; padding-bottom: 30px;">
						<div class="col-xs-12 text-center">
							<a class="btn btn-dark btn-lg" href="/team">More About Us</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Call to Action -->
	<section id="download" class="call-to-action bg-customized">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1>Download our App</h1>
					<hr class="small">
					<p class="lead">Install our app in your phone, or use our web version.</p>
				</div>

				<div class="col-sm-12 text-center">
					<a href="https://play.google.com/store/apps/details?id=com.apretaste.apretaste" target="_blank" class="btn btn-lg btn-light btn-fized-size"><i class="fa fa-android"></i> Play Store</a>
					<a href="https://itunes.apple.com/us/app/apretaste/id1388113023" target="_blank" class="btn btn-lg btn-light btn-fized-size"><i class="fa fa-apple"></i> iTunes</a>
					<a class="btn btn-lg btn-dark btn-fized-size" target="_blank" href="/servicios"><i class="fa fa-chrome"></i> Web Version</a>

					<p style="margin-top:15px;">Download <a class="whitelink" href="http://piropazo.com" target="_blank"><b>Piropazo</b>, our dating app</a></p>
				</div>
			</div>
		</div>
	</section>

	<!-- Map -->
	<section id="contact" class="map">
		<img style="width:100%;" src="/images/map.png" alt="We are located at the Miami Entrepreneurship Center"/>
	</section>

	<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h1>Contact Us</h1>
					<hr class="small">
					<p><b>Apretaste</b> at the Miami Entrepreneurship Center</p>
					<p>261 NE 1st Street, 5th Floor<br>Miami, FL 33132</p>
					<ul class="list-unstyled">
						<li><i class="fa fa-phone fa-fw"></i> (305) 457-1656</li>
						<li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:salvi@apretaste.org">salvi@apretaste.org</a></li>
					</ul>
					<br>
					<ul class="list-inline">
						<li>
							<a href="https://www.facebook.com/apretaste" target="_blank"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://twitter.com/apretaste" target="_blank"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://www.youtube.com/channel/UCdoAdQE6OVvmEqdLM4XACmQ" target="_blank"><i class="fa fa-youtube fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://www.instagram.com/apretaste" target="_blank"><i class="fa fa-instagram fa-fw fa-3x"></i></a>
						</li>
					</ul>
					<hr class="small">
					<p>We also serve Cubans living in United States, Canada, Colombia, Venezuela and Spain. Few other locations can apply.</p>
					<br>
					<p class="small">A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES BY CALLING TOLL-FREE WITHIN THE STATE 1-800-HELPFLA, OR VIA THE INTERNET AT WWW.800HELPFLA.COM. REGISTRATION DOES NOT IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY THE STATE.</p>
					<p><a href="/privacy" title="Privacy Policy">Privacy Policy</a></p>
				</div>
			</div>
		</div>
	</footer>

	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55b53cc3acee4add" async="async"></script>

	<!-- jQuery -->
	<script src="/js/jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="/js/bootstrap.min.js"></script>

	<!-- google graph -->
	<script type='text/javascript' src='https://www.google.com/jsapi'></script>

	<!-- Custom Theme JavaScript -->
	<script type='text/javascript'>
	// Visitors
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['Day of the week', 'Email'],
			<?php foreach ($visitors as $data) { ?>
				['<?= $data['date'] ?>',<?= $data['emails'] ?>],
			<?php } ?>
		]);
		var options = {backgroundColor: '#C1C1C1', legend: 'none'};
		var chart = new google.visualization.AreaChart(document.getElementById('visitors'));
		chart.draw(data, options);
	});

	// Closes the sidebar menu
	$("#menu-close").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Opens the sidebar menu
	$("#menu-toggle").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Scrolls to the selected menu item on the page
	$(function() {
		$('a[href*=#]:not([href=#])').click(function() {
			if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

				var target = $(this.hash);
				target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
				if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 1000);
					return false;
				}
			}
		});

		$('.tooltip-image').tooltip();
	});

	function checkVideo(){
		$('#youtubevideo').attr('src', 'https://www.youtube.com/embed/le-GIUhk0to?version=2&vq=hd720');
		$('.tryit-show').slideDown('slow');
		$('html,body').animate({
			scrollTop: $('#tryit').offset().top
		}, 1000);
	}

	// Close Checkout on page navigation
	$(window).on('popstate', function() {
		handler.close();
	});
	</script>

	<?php require_once "$wwwroot/lib/googleAnalyticsTracking.php" ?>
</body>
</html>
