<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bienvenido a Apretaste</title>

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Conéctate a la internet por Nauta. Redes Sociales, Noticias, Web, Entretenimiento y mucho más.">
	<meta name="author" content="Salvi Pascual">

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary">
	<meta name="twitter:site" content="@apretaste">
	<meta name="twitter:title" content="Conéctate a la internet por Nauta">
	<meta name="twitter:description" content="Revisa las Redes Sociales, Noticias, Web, Entretenimiento y mucho más. Todo desde la comodidad de tu casa, y gratuitamente.">
	<meta name="twitter:creator" content="@apretaste">
	<meta name="twitter:image" content="/images/FeatureGraphic.png">

	<!-- Open Graph data -->
	<meta name="fb:app_id" content="285099284865702" />
	<meta name="og:url" content="https://apretaste.com" />
	<meta name="og:type" content="website" />
	<meta name="og:locale" content="es_ES" />
	<meta name="og:locale:alternate" content="en_US" />
	<meta name="og:site_name" content="Apretaste" />
	<meta name="og:title" content="Conéctate a la internet por Nauta." />
	<meta name="og:description" content="Revisa las Redes Sociales, Noticias, Web, Entretenimiento y mucho más. Todo desde la comodidad de tu casa, y gratuitamente." />
	<meta name="og:image" content="/images/FeatureGraphic.png" />

	<link rel="icon" href="/images/apretaste.icon.png">
	<link rel="canonical" href="https://apretaste.com">

	<!-- Bootstrap Core CSS -->
	<link href="/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="/css/welcome.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
	<!-- Navigation -->
	<a id="menu-toggle-language" href="welcome" class="btn btn-dark btn-lg toggle">EN</a>
	<a id="menu-download" href="#download" class="btn btn-dark btn-lg toggle"><i class="fa fa-android"></i> Descargar</a>
	<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>

	<nav id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
			<li class="sidebar-brand"><a href="#top">Apretaste</a></li>

			<li><a href="#problem">Problema</a></li>
			<li><a href="#idea">Soluci&oacute;n</a></li>
			<li><a href="#mission">Misi&oacute;n</a></li>
			<li><a href="#services">Servicios</a></li>
			<li><a href="#testimonials">Testimonios</a></li>
			<li><a href="#team">Con&oacute;zcanos</a></li>
			<li><a href="#download">Descargar</a></li>
			<li><a href="#contact">Cont&aacute;ctanos</a></li>
			<li><a href="https://www.meetup.com/heycuba/" target="_blank">&iquest;Sabes programar? <i class="fa fa-medkit"></i></a></li>
			<li><a href="http://blog.apretaste.com">Blog <i class="fa fa-bullhorn"></i></a></li>
			<li><a href="welcome">English</a></li>
		</ul>
	</nav>

	<!-- Header -->
	<header id="top" class="header">
		<div class="text-vertical-center">
			<div style="margin-top:-200px">
				<img id="main-logo-image" src="/images/apretaste.logo.big.transp.png" alt="Apretaste"><br/>
				<div id="motto">
					<h3 class="contrast">Conectando a miles de cubanos a la internet por v&iacute;as efectivas, accesibles y legales</h3>
				</div>
				<br>
				<a href="#problem" class="btn btn-dark btn-lg">Leer M&aacute;s</a>
				<a href="/invitar" class="btn btn-light btn-lg">Invite a un Cubano</a>
			</div>
		</div>
	</header>

	<!-- The Problem -->
	<section id="problem">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive" src="/images/internet-in-cuba.png">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note"><span class="green">2,800,000</span> en Cuba abren solo email,<br/>apenas <span class="red">560,000</span> navegan la Web</p>
					<p class="lead big gray ">En Cuba, la mayor&iacute;a solo puede conectarse a un servidor email del gobierno (webmail.nauta.cu). Otras webs est&aacute;n bloqueadas.</p>
				</div>
			</div>
		</div>
	</section>

	<!-- A great idea -->
	<section id="idea" class="idea bg-customized">
		<div class="container">
			<div class="row inner-space-vertical" style="padding-bottom:0px;">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<p class="lead high-note">Nuestra App permite acceder a la internet usando email</p>
					<ul class="lead">
						<li>La informaci&oacute;n viaja dentro del email</li>
						<li>Los emails son encriptados y minificados</li>
					</ul>
					<div class="blank-space-divider"></div>
					<a href="#download" class="btn btn-light"><i class="fa fa-android"></i> Descargar App</a>&nbsp;
					<button class="btn btn-dark" onclick="checkVideo();"><i class="fa fa-youtube-play"></i> Mirar Video</button>
				</div>

				<div class="blank-space-divider"></div>

				<div class="col-lg-7 col-md-7 col-sm-6 text-center">
					<img src="/images/ap-app.png">
				</div>
			</div>

		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- try it-->
	<section id="tryit" class="tryit tryit-show" style="display:none;">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>Nuesto servicio en vivo</h2>
					<hr class="small">
					<div class="videoWrapper">
						<iframe id="youtubevideo" src="" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider visible-xs tryit-show" style="display:none;"></div>
	<hr class="featurette-divider hidden-xs tryit-show" style="display:none; margin-bottom:40px;">

	<!-- First Featurette -->
	<section id="mission" class="mainfeature">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>Tenemos una misi&oacute;n</h2>
					<hr class="small">
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-plug fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Conectar cubanos aislados al mundo de oportunidades que ofrece internet</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-book fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Educar a los cubanos en el uso de internet y las &uacute;ltimas tecnolog&iacute;as</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-bullhorn fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Ofrecer informaci&oacute;n alternativa a quienes solo revisan la prensa "oficial"</p>
				</div>
			</div>

			<hr class="small">

			<div class="row">
				<div id="member" class="col-xs-12 text-center">
					<span class="lead">&iquest;Compartes nuestros objetivos?
						<a href="https://www.meetup.com/heycuba/" class="btn btn-dark btn-md">&Uacute;nete a nuestros miembros</a>
					</span>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- Services -->
	<section id="services" class="services bg-customized">
		<div class="container">
			<div class="row text-center">
				<div class="col-lg-10 col-lg-offset-1">
					<h2>Servicios m&aacute;s populares</h2>
					<p style="color:#c1c1c1;">Escogidos de entre m&aacute;s de 40 otros servicios</p>
					<hr class="small">
					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/pizarra" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-users fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Red Social</strong></h4>
									<p>Permite compartir contenido</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/vuelos" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-plane fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Vuelos</strong></h4>
									<p>Actividad aérea en Cuba</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="http://piropazo.com" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-heart fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Amor</strong></h4>
									<p>Ayuda buscando su media naranja</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/google" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-globe fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Web</strong></h4>
									<p>Navega la web abiertamente</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/mapas" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-compass fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Mapas</strong></h4>
									<p>Mapas de lugares y direcciones</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<a href="/wikipedia" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-book fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Wikipedia</strong></h4>
									<p>Busca en la enciclopedia global</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<a href="/escuela" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-graduation-cap fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Educaci&oacute;n</strong></h4>
									<p>Clases en l&iacute;nea desde tu tel&eacute;fono</p>
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<a href="/traductor" target="_blank" class="iconlink">
									<span class="fa-stack fa-4x">
										<i class="fa fa-circle fa-stack-2x"></i>
										<i class="fa fa-language fa-stack-1x text-success"></i>
									</span>
									<h4><strong>Traducci&oacute;n</strong></h4>
									<p>Traduce palabras y p&aacute;rrafos</p>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xs-12" style="margin-top:15px;">
					<a class="btn btn-light btn-lg" target="_blank" href="/servicios">Disfruta Nuestros Servicios</a>
				</div>
			</div>
		</div>
	</section>

	<!-- Users -->
	<section id="users" style="background-color:#C1C1C1;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1 class="lead high-note black">A lo largo de los &uacute;ltimos a&ntilde;os hemos<br class="hidden-xs"/> trabajado duro para conectar m&aacute;s cubanos</h1>
					<div id="visitors" style="width:100%;"></div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-center">
					<h3 class="black lead">Con <?= number_format($visitorsPerMonth) ?> visitantes al mes, creo que vamos por buen camino</h3>
					<br/>
				</div>
			</div>
		</div>
	</section>

	<!-- Portfolio -->
	<section id="testimonials" class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-lg-offset-1 text-center">
					<h2>Lo que dice la gente</h2>
					<hr class="small">
					<div class="row">
							<div class="col-md-4 col-sm-6 text-left hidden-xs">
							    <div class="bubble">Muchas gracias, que bueno que todavia hay personas que se preocupan por nosotros.</div>
							    <p class="bubble-name">Danays</p>
							</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Apretaste! es una gran oportunidad para quienes no disponemos de una coneccion activa, sino tan solo el correo y el telefono.</div>
						    <p class="bubble-name">Miguel</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Me gusta Apretaste! por su sinceridad y buena forma para optener información de conocimiento sobre consultas a enciclopedia compras y ventas + buenas relaciones entre usuarios.</div>
						    <p class="bubble-name">Eusebio</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Gracias por existir y darnos esta oportunidad a los cubanos de a pie, espero que su trabajo se mantenga y que en Cuba no los bloqueen, sería una gran pérdida.</div>
						    <p class="bubble-name">Carlos</p>
						</div>
						<div class="col-md-4 hidden-sm hidden-xs text-left">
						    <div class="bubble">La posibilidad de usar los servicios de Apretaste! me ha dejado frio. Ahora puedo acceder con facilidad a servicios q nosotros no podiamos, nuevamente gracias y que dios los bendiga.</div>
						    <p class="bubble-name">Eladio</p>
						</div>
					</div>

					<div class="blank-space-divider"></div>

					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.miamiherald.com/news/business/technology/article65196697.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/miamiherald.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://event.on24.com/wcc/r/1237558/E17397506918D1078847DF56BBA25D2E" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/oreilly.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.telemundo51.com/noticias/cuba/Concurso-Hey-Cuba-Hackaton_TLMD---Miami-368985671.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/telemundo.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.sun-sentinel.com/business/small-business/fl-cuba-internet-company-20151130-story.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/sunsentinel.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.miaminewtimes.com/news/miami-company-helps-cubans-access-the-internet-through-their-email-8351534" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/newtimesmiami.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.jump-in.com.au/show/60minutes/stories/2014/september/a-cuban-revolution/" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/60minutes.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.elnuevoherald.com/noticias/mundo/america-latina/cuba-es/article64126537.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/nuevoherald.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://motherboard.vice.com/read/this-workaround-lets-26-million-cubans-surf-the-web" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/motherboard.png">
								</a>
							</div>
						</div>

						<?php /* hidden press to show on click */ ?>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.elmundo.es/economia/2016/02/15/56c192b0268e3ef5758b45bd.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/elmundo.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.martinoticias.com/content/apretaste-servicio-clasificados-por-email/31982.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/martinoticias.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.bizjournals.com/southflorida/news/2016/03/10/miami-hackathon-aims-to-improve-cuba-s-web-access.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/southflobizjournal.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.diariolasamericas.com/4842_locales/3628715_organizan-encuentro-programadores-miami-internet-cuba.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/diariolasamericas.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.14ymedio.com/blogs/generacion_y/Apretaste_7_1537716214.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/14ymedio.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.diariodecuba.com/cuba/1449255436_18591.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/diariodecuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="https://www.cubanet.org/noticias/cubano-organiza-hackathon-en-miami-por-mejorar-acceso-a-internet-en-la-isla/" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/cubanet.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://www.14ymedio.com/blogs/generacion_y/Apretaste_7_1537716214.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/generaciony.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="https://www.cibercuba.com/noticias/14ymedio/2016-02-15-una-hackathon-en-miami-para-facilitar-acceso-internet-cubanos" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/cibercuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://raicesblog.blogspot.com/2014/02/roots-of-hope-hosts-first-ever.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/hackathonforcuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://martinoticias.org/archive/one_thousand_800_online/14/97/129.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/1800online.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 showmorepress">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top">
								<a href="http://hispz14.sched.org/event/d586fcd1fadff0e5b84fc2995eccfd20#.VCh10vnxqTU" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="/images/media/hispanicize.png">
								</a>
							</div>
						</div>
					</div>

					<div class="row" id="morepressbtn">
						<div class="col-xs-12 text-center" style="margin-bottom: 30px">
							<button class="btn btn-dark btn-lg" onclick="$('.showmorepress').slideDown(); $('#morepressbtn').remove();">Incluso m&aacute;s Prensa</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Team -->
	<section id="team" class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-lg-offset-1 text-center">
					<h2>Conozca nuestro equipo</h2>
					<hr class="small">
					<div class="row">
						<div class="img-team col-md-4 col-sm-4 col-xs-6">
							<img class="img-circle team-member" src="/images/team/salvi.jpg"/>
							<h4>Salvi Pascual</h4>
							<p>Director Ejecutivo<br/><a href="mailto:salvi@apretaste.org">salvi@apretaste.org</a></p>
							<img src="/images/flags/us.png"/>
						</div>
						<div class="img-team col-md-4 col-sm-4 col-xs-6">
							<img class="img-circle team-member" src="/images/team/ivon.jpg"/>
							<h4>Ivon Ramos</h4>
							<p>Director de Marketing<br/><a href="mailto:ivon@apretaste.org">ivon@apretaste.org</a></p>
							<img src="/images/flags/ve.png"/>
						</div>
						<div class="img-team col-md-4 col-sm-4 col-xs-12">
							<img class="img-circle team-member" src="/images/team/alex.jpg"/>
							<h4>Alex Maestre</h4>
							<p>Director de Technology<br/><a href="mailto:alex@apretaste.org">alex@apretaste.org</a></p>
							<img src="/images/flags/ve.png"/>
						</div>
					</div>

					<div class="row" style="margin: 20px; padding-bottom: 30px;">
						<div class="col-xs-12 text-center">
							<a class="btn btn-dark btn-lg" href="/team">M&aacute;s Sobre Nosotros</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Call to Action -->
	<section id="download" class="call-to-action bg-customized">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1>Descarga nuestra App</h1>
					<hr class="small">
					<p class="lead">Instala nuestra app en tu tel&eacute;fono, o navega v&iacute;a web.</p>
				</div>

				<div class="col-sm-12 text-center">
					<a href="https://play.google.com/store/apps/details?id=com.apretaste.apretaste" target="_blank" class="btn btn-lg btn-light btn-fized-size"><i class="fa fa-android"></i> Play Store</a>
					<a href="https://itunes.apple.com/us/app/apretaste/id1388113023" target="_blank" class="btn btn-lg btn-light btn-fized-size"><i class="fa fa-apple"></i> iTunes</a>
					<a class="btn btn-lg btn-dark btn-fized-size" target="_blank" href="/servicios"><i class="fa fa-chrome"></i> Modo Web</a>

					<p style="margin-top:15px;">Descarga <a class="whitelink" href="http://piropazo.com" target="_blank"><b>Piropazo</b>, nuestra app de citas</a></p>
				</div>
			</div>
		</div>
	</section>

	<!-- Map -->
	<section id="contact" class="map">
		<img style="width:100%;" src="/images/map.png" alt="Estamos ubicados en el Miami Entrepreneurship Center"/>
	</section>

	<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h1>Cont&aacute;ctanos</h1>
					<hr class="small">
					<p><b>Apretaste</b>, ubicado en el Miami Entrepreneurship Center</p>
					<p>261 NE 1st Street, 5th Floor<br>Miami, FL 33132</p>
					<ul class="list-unstyled">
						<li><i class="fa fa-phone fa-fw"></i> (305) 457-1656</li>
						<li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:salvi@apretaste.org">salvi@apretaste.org</a></li>
					</ul>
					<br>
					<ul class="list-inline">
						<li>
							<a href="https://www.facebook.com/apretaste" target="_blank"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://twitter.com/apretaste" target="_blank"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://www.youtube.com/channel/UCdoAdQE6OVvmEqdLM4XACmQ" target="_blank"><i class="fa fa-youtube fa-fw fa-3x"></i></a>
						</li>
					</ul>
					<hr class="small">
					<p>También servimos a Cubanos que viven en Estados Unidos, Canada, Colombia, Venezuela y España. Otros paises pueden aplicar.</p>
					<br>
					<p class="small">A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES BY CALLING TOLL-FREE WITHIN THE STATE 1-800-HELPFLA, OR VIA THE INTERNET AT WWW.800HELPFLA.COM. REGISTRATION DOES NOT IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY THE STATE.</p>
					<p><a href="/privacy" title="P&oacute;liza de Privacidad">P&oacute;liza de Privacidad</a></p>
				</div>
			</div>
		</div>
	</footer>

	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55b53cc3acee4add" async="async"></script>

	<!-- jQuery -->
	<script src="/js/jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="/js/bootstrap.min.js"></script>

	<!-- google graph -->
	<script type='text/javascript' src='https://www.google.com/jsapi'></script>

	<!-- Custom Theme JavaScript -->
	<script type='text/javascript'>
	// Visitors
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['Day of the week', 'Email'],
			<?php foreach ($visitors as $data) { ?>
				['<?= $data['date'] ?>',<?= $data['emails'] ?>],
			<?php } ?>
		]);
		var options = {backgroundColor: '#C1C1C1', legend: 'none'};
		var chart = new google.visualization.AreaChart(document.getElementById('visitors'));
		chart.draw(data, options);
	});

	// Closes the sidebar menu
	$("#menu-close").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Opens the sidebar menu
	$("#menu-toggle").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Scrolls to the selected menu item on the page
	$(function() {
		$('a[href*=#]:not([href=#])').click(function() {
			if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

				var target = $(this.hash);
				target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
				if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 1000);
					return false;
				}
			}
		});

		$('.tooltip-image').tooltip();
	});

	function checkVideo(){
		$('#youtubevideo').attr('src', 'https://www.youtube.com/embed/le-GIUhk0to?version=2&vq=hd720');
		$('.tryit-show').slideDown('slow');
		$('html,body').animate({
			scrollTop: $('#tryit').offset().top
		}, 1000);
	}

	// Close Checkout on page navigation
	$(window).on('popstate', function() {
		handler.close();
	});
	</script>

	<?php require_once "$wwwroot/lib/googleAnalyticsTracking.php" ?>
</body>
</html>
