<!-- Bio #1 - Salvi Pascual -->
<section id="salvipascual">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/salvi-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Salvi Pascual <img src="/images/flags/us.png"/></p>
				<p>Executive Director - <a href="mailto:salvi@apretaste.com">salvi@apretaste.com</a></p>
				<p class="lead big gray">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and strives to not be the worst pool player in the world.</p>
			</div>
		</div>
	</div>
</section>

<!-- Bio #2 - Kuma Hacker -->
<section id="kumahacker">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/kuma-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Kuma Hacker <img src="/images/flags/cu.png"/></p>
				<p>Chief Technology Officer - <a href="mailto:salvi@apretaste.com">salvi@apretaste.com</a></p>
				<p class="lead big gray">Kuma es un programador freelancer, desarrollador de software y arquitecto de sistemas. Obtuvo su Ingeniería en Informática en Cuba y continúa aplicando sus concimientos para ayudar a otros a acercarse a la tecnología y a romper las barreras ideo-tecnológicas. A Kuma le encanta encriptar hasta lo que no ve, y normalmente vive en la nube.</p>
			</div>
		</div>
	</div>
</section>

<!-- Bio #3 - Alex Maestre -->
<section id="alexmaestre">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/alex-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Alex Maestre <img src="/images/flags/ve.png"/></p>
				<p>Master of all Trades - <a href="mailto:salvi@apretaste.com">salvi@apretaste.com</a></p>
				<p class="lead big gray">Alexander Maestre tiene muchos pseudo títulos que incluyen cocinero, consultista vocacional y modelo de lencería. Como amante incondicional del aprendizaje, ha gastado gran parte de su vida en intentar conocer el mundo que lo rodea. Actualmente estudia Ingeniería Electrónica en Computación en su país de nacimiento, Venezuela.</p>
			</div>
		</div>
	</div>
</section>

<!-- Bio #4 - Ibis Arrastia -->
<section id="ibisarrastia">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/ibis-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Ibis Arrastia <img src="/images/flags/us.png"/></p>
				<p>Program Manager - <a href="mailto:ibis@apretaste.com">ibis@apretaste.com</a></p>
				<p class="lead big gray">Ibis is an out-of-the-box thinker with more than two decades of software development experience, with an emphasis in product innovation and eCommerce. As a speaker, educator, developer, entrepreneur, and local tech community leader, Ibis works to inspire others to innovate, invent, and reach new heights within the technology industry. She is a strong advocate for more women in IT and plays an active role in training women and increasing the South Florida technical workforce.</p>
			</div>
		</div>
	</div>
</section>
