<!-- Salvi Pascual -->
<section id="salvipascual">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/salvi-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Salvi Pascual <img src="/images/flags/us.png"/></p>
				<p>Executive Director - <a href="mailto:salvi@apretaste.org">salvi@apretaste.org</a></p>
				<p class="lead big gray">Salvi Pascual is a university professor, an experienced software developer, a systems architect, and a technology trailblazer for social good through his open source project, Apretaste. His work has an immediate and positive affect on thousands of people internationally, and he has been nationally recognized by the press and media as a technology innovator. He earned his master degree in Computer Science from Florida International University and continues to teach and inspire future technology creators. Salvi loves traveling and tasting local beers.</p>
			</div>
		</div>
	</div>
</section>

<!-- Alex Maestre -->
<section id="alexmaestre">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/alex-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Alex Maestre <img src="/images/flags/ve.png"/></p>
				<p>Director of Technology - <a href="mailto:alex@apretaste.org">alex@apretaste.org</a></p>
				<p class="lead big gray">Alexander Maestre tiene muchos pseudo títulos que incluyen cocinero, consultista vocacional y modelo de lencería. Como amante incondicional del aprendizaje, ha gastado gran parte de su vida en intentar conocer el mundo que lo rodea. Actualmente estudia Ingeniería Electrónica en Computación en su país de nacimiento, Venezuela.</p>
			</div>
		</div>
	</div>
</section>

<!-- Ivon Ramos -->
<section id="ivonramos">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/ivon-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Ivon Ramos <img src="/images/flags/ve.png"/></p>
				<p>Director of Marketing - <a href="mailto:ivon@apretaste.org">ivon@apretaste.org</a></p>
				<p class="lead big gray">Comunity Manager y Fotógrafa enfocada en la comunicación e investigación, amante de la tecnología,el turismo,los deportes y el aprendizaje, con firmes intenciones de lograr grandes cosas en el mundo, a través del conocimiento y la pasión que me impulsa a convertir cada meta en una realidad constructora de una mejor sociedad.</p>
			</div>
		</div>
	</div>
</section>

<!-- Edgar Hernández -->
<section id="edgarhernandez">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/edgar-large.png">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Edgar Hernández <img src="/images/flags/ve.png"/></p>
				<p>Customer Support Representative - <a href="mailto:edgar@apretaste.org">edgar@apretaste.org</a></p>
				<p class="lead big gray">Entusiasta de la tecnología, en búsqueda de la tranquilidad y amante del Outdoor. Bastante minucioso y meticuloso, algo estresado. Buscando una mina de Mithril desde 1998. Fiel creyente de "Jack of All Trades Master of Some".</p>
			</div>
		</div>
	</div>
</section>

<!-- Kuma Hacker -->
<section id="kumahacker">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/kuma-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Kuma Hacker <img src="/images/flags/cu.png"/></p>
				<p>Lead Programmer - <a href="mailto:kuma@apretaste.org">kuma@apretaste.org</a></p>
				<p class="lead big gray">Kuma es un programador freelancer, desarrollador de software y arquitecto de sistemas. Obtuvo su Ingeniería en Informática en Cuba y continúa aplicando sus concimientos para ayudar a otros a acercarse a la tecnología y a romper las barreras ideo-tecnológicas. A Kuma le encanta encriptar hasta lo que no ve, y normalmente vive en la nube.</p>
			</div>
		</div>
	</div>
</section>

<!-- Ibis Arrastia -->
<section id="ibisarrastia">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/ibis-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Ibis Arrastia <img src="/images/flags/us.png"/></p>
				<p>Program Manager - <a href="mailto:ibis@apretaste.org">ibis@apretaste.org</a></p>
				<p class="lead big gray">Ibis is an out-of-the-box thinker with more than two decades of software development experience, with an emphasis in product innovation and eCommerce. As a speaker, educator, developer, entrepreneur, and local tech community leader, Ibis works to inspire others to innovate, invent, and reach new heights within the technology industry. She is a strong advocate for more women in IT and plays an active role in training women and increasing the South Florida technical workforce.</p>
			</div>
		</div>
	</div>
</section>

<!-- Geysell Cisneros -->
<section id="geysellcisneros">
	<div class="container">
		<div class="row inner-space-vertical">
			<div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
				<img class="img-responsive full-screen" src="/images/team/geysell-large.jpg">
			</div>
			<div class="col-lg-8 col-md-7 col-sm-6 col-xs-12">
				<p class="high-note no-margin">Geysell Cisneros <img src="/images/flags/us.png"/></p>
				<p>Marketing Geek - <a href="mailto:geysell@apretaste.org">geysell@apretaste.org</a></p>
				<p class="lead big gray">Periodista que sueña con cosas imposibles. De La Habana a Quito y desde esos dos destinos a Miami. Reconstruyendo historias a través de la memoria y los sentidos. Enfocada en hacer una mejor Cuba desde esta orilla, y por suerte, ha encontrado con quiénes hacerlo. Su deseos es servir a través de su oficio, y por eso cree firmemente en el valor de la palabra.</p>
			</div>
		</div>
	</div>
</section>
