<!DOCTYPE html>
<html lang="en">
<head>
	<title>Welcome to Apretaste</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways">
	<meta name="author" content="Salvi Pascual">

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary">
	<meta name="twitter:site" content="@apretaste">
	<meta name="twitter:title" content="We are connecting Cubans to the Web">
	<meta name="twitter:description" content="Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways">
	<meta name="twitter:creator" content="@apretaste">
	<meta name="twitter:image" content="<?php echo $wwwhttp; ?>/images/background.jpg">

	<!-- Open Graph data -->
	<meta name="fb:app_id" content="285099284865702" />
	<meta name="og:url" content="https://apretaste.com" />
	<meta name="og:type" content="website" />
	<meta name="og:locale" content="en_US" />
	<meta name="og:locale:alternate" content="es_ES" />
	<meta name="og:site_name" content="Apretaste" />
	<meta name="og:title" content="We are connecting Cubans to the Web" />
	<meta name="og:description" content="Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways" />
	<meta name="og:image" content="<?php echo $wwwhttp; ?>/images/background.jpg" />

	<link rel="icon" href="<?php echo $wwwhttp; ?>/images/apretaste.icon.png">
	<link rel="canonical" href="https://apretaste.com">

	<!-- Bootstrap Core CSS -->
	<link href="<?php echo $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="<?php echo $wwwhttp; ?>/css/welcome.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="<?php echo $wwwhttp; ?>/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55b53cc3acee4add" async="async"></script>
	
	<!-- Navigation -->
	<a id="menu-toggle-language" href="bienvenido" class="btn btn-dark btn-lg toggle"><i class="fa fa-flag"></i></a>
	<a id="menu-donate" href="#donate" class="btn btn-dark btn-lg toggle"><i class="fa fa-life-ring"></i> Donate</a>
	<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>

	<nav id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
			<li class="sidebar-brand"><a href="#top">Apretaste</a></li>

			<li><a href="#problem">Problem</a></li>
			<li><a href="#idea">Solution</a></li>
			<li><a href="#mission">Mission</a></li>
			<li><a href="#services">Services</a></li>
			<li><a href="#testimonials">Testimonials</a></li>
			<li><a href="#donate">Donate</a></li>
			<li><a href="#contact">Contact Us</a></li>
		</ul>
	</nav>

	<!-- Header -->
	<header id="top" class="header">
		<div class="text-vertical-center">
			<div style="margin-top:-200px">
				<img id="main-logo-image" src="<?php echo $wwwhttp; ?>/images/apretaste.logo.big.transp.png" alt="Apretaste"><br/>
				<div id="motto">

					<h3 class="contrast">Connecting thousands of Cubans to the Internet each month via accessible, effective and legal ways</h3>
				</div>
				<br>
				<a href="#problem" class="btn btn-dark btn-lg">Find Out More</a>
			</div>
		</div>
	</header>

	<!-- The Problem -->
	<section id="problem">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<div class="blank-space-divider hidden-lg hidden-xs"></div>
					<img class="img-responsive full-screen" src="<?php echo $wwwhttp; ?>/images/internet-in-cuba.png">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<p class="lead high-note"><span class="green">2,600,000</span> Cubans can only access email, while only <span class="red">400,000</span> can surf the Web without restrictions</p>
					<p class="lead big gray hidden-sm hidden-xs">This is the strategy of the Cuban government to report large number of users online without actually granting them access to information on the web</p>
				</div>
			</div>
		</div>
	</section>

	<!-- A great idea -->
	<section id="idea" class="idea bg-customized">
		<div class="container">
			<div class="row inner-space-vertical">
				<div class="col-lg-5 col-md-5 col-sm-6">
					<p class="lead high-note">Our solution was to provide Cubans with the ability to surf the Web via Email</p>
					<ul class="lead hidden-xs">
						<li>Email is fast, legal and cheap. It is perfect for slow networks</li>
						<li>Email is not centralized, which makes it very hard to censor</li>
					</ul>
				</div>
				<div class="col-lg-7 col-md-7 col-sm-6">
					<img class="full-screen img-responsive" src="<?php echo $wwwhttp; ?>/images/how-apretaste-works.png">
				</div>
			</div>
			<div id="tryit-button" class="row text-center">
				<button class="btn btn-light btn-lg" onclick="$('.tryit-show').slideDown('slow'); $('#tryit-button').slideUp('fast');">Do not just take my word for it. <b>Try it!</b></button>
			</div>
		<div class="blank-space-divider"></div>
		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- try it-->
	<section id="tryit" class="tryit tryit-show" style="display:none;">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>Access Wikipedia from your Email</h2>
					<hr class="small">
					<div class="videoWrapper">
					<iframe src="https://www.youtube.com/embed/xz_lxXz-Cqs?version=2&vq=hd720" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider visible-xs tryit-show" style="display:none;"></div>
	<hr class="featurette-divider hidden-xs tryit-show" style="display:none; margin-bottom:40px;">

	<!-- First Featurette -->
	<section id="mission" class="mainfeature">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h2>We are on a mission</h2>
					<hr class="small">
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-plug fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Connect isolated people to the Internet and show them a whole new world of opportunities</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-book fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Educate the Cubans on the use of Internet to ensure a smooth transition when the time comes</p>
				</div>
				<div class="col-sm-4 col-xs-12 text-center mission-item-xs">
					<div class="service-item">
						<span class="fa-stack fa-4x">
							<i class="fa fa-circle fa-stack-2x apretaste-green"></i>
							<i class="fa fa-bullhorn fa-stack-1x white"></i>
						</span>
					</div>
					<p class="lead">Grant alternative sources of information to people who can only access ones chosen by the "official" media</p>
				</div>
			</div>
			
			<hr class="small">

			<div class="row">
				<div id="member" class="col-xs-12 text-center">
					<span class="lead">Do you share our goals? Then </span>
					<script type="text/javascript" src="//app.mailerlite.com/data/webforms/37189/f1z0x0.js?v2"></script>
				</div>
			</div>
		</div>
	</section>

	<div class="blank-space-divider"></div>

	<!-- Services -->
	<section id="services" class="services bg-customized">
		<div class="container">
			<div class="row text-center">
				<div class="col-lg-10 col-lg-offset-1">
					<h2>Most Popular Services</h2>
					<hr class="small">
					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-shopping-cart fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Store</strong></h4>
								<p>Connect buyers and sellers</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-compass fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Maps</strong></h4>
								<p>Maps of locations and addresses</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-book fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Encyclopedia</strong></h4>
								<p>Access Wikipedia from your email</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-cloud fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Weather</strong></h4>
								<p>Check the weather forecast</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-gamepad fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Entertaiment</strong></h4>
								<p>Puzzles, word games and jokes</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-language fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Translation</strong></h4>
								<p>Translate words and paragraphs from/to almost any language</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-comments fa-stack-1x text-success"></i>
							</span>
								<h4><strong>SMS</strong></h4>
								<p>Send SMSs to Cuba and abroad for up to 90% less than the official price</p>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="service-item">
								<span class="fa-stack fa-4x">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-ticket fa-stack-1x text-success"></i>
							</span>
								<h4><strong>Raffle</strong></h4>
								<p>Raffle three prizes every month</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="blank-space-divider"></div>

			<div class="row">
				<div class="col-lg-12 text-center">
					<p class="lead">We will include more useful services within the next year</p>
					<span class="label label-primary custom-label">SOCIAL NETWORK</span>
					<span class="label label-primary custom-label">NEWSPAPER</span>
					<span class="label label-primary custom-label">APPS MARKET</span>
					<span class="label label-primary custom-label">WEB PUBLISHING</span>
					<span class="label label-primary custom-label">PHONE GUIDE</span>
					<span class="label label-primary custom-label">WEBSITE DOWNLOAD</span>
					<span class="label label-primary custom-label">SPORTS NEWS</span>
					<span class="label label-primary custom-label">REDDIT</span>
					<span class="label label-primary custom-label">SOCIAL NEWS</span>
					<span class="label label-primary custom-label">TV GUIDE</span>
					<span class="label label-primary custom-label">DICTIONARY</span>
					<span class="label label-primary custom-label">SURVEYS</span>
					<span class="label label-primary custom-label">TECH THREADS</span>
					<span class="label label-primary custom-label">GOOGLE SEARCH</span>
				</div>
			</div>
		</div>
	</section>
	
	<!-- Users -->
	<section id="users" style="background-color:#C1C1C1;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h1 class="lead high-note black">Along the last two years we have been<br class="hidden-xs"/> working hard to connect more Cubans</h1>
					<img id="users-graph" src="<?php echo $wwwhttp; ?>/images/apretaste-users-2014.png" alt="Apretaste users for 2014"/>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-center">
					<h3 class="black lead">With more than 70K Visitors/Month, we believe we are on the right track</h3>
					<br/>
				</div>
			</div>
		</div>
	</section>

	<!-- Portfolio -->
	<section id="testimonials" class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-lg-offset-1 text-center">
					<h2>What people are saying</h2>
					<hr class="small">
					<div class="row">
							<div class="col-md-4 col-sm-6 text-left hidden-xs">
							    <div class="bubble">Muchas gracias, que bueno que todavia hay personas que se preocupan por nosotros.</div>
							    <p class="bubble-name">Danays</p>
							</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Apretaste es una gran oportunidad para quienes no disponemos de una coneccion activa, sino tan solo el correo y el telefono.</div>
						    <p class="bubble-name">Miguel</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Me gusta Apretaste por su sinceridad y buena forma para optener información de conocimiento sobre consultas a enciclopedia compras y ventas + buenas relaciones entre usuarios.</div>
						    <p class="bubble-name">Eusebio</p>
						</div>
						<div class="col-md-4 col-sm-6 text-left">
						    <div class="bubble">Gracias por existir y darnos esta oportunidad a los cubanos de a pie, espero que su trabajo se mantenga y que en Cuba no los bloqueen, sería una gran pérdida.</div>
						    <p class="bubble-name">Carlos</p>
						</div>
						<div class="col-md-4 hidden-sm hidden-xs text-left">
						    <div class="bubble">La posibilidad de usar los servicios de Apretaste me ha dejado frio. Ahora puedo acceder con facilidad a servicios q nosotros no podiamos, nuevamente gracias y que dios los bendiga.</div>
						    <p class="bubble-name">Eladio</p>
						</div>
					</div>

					<div class="blank-space-divider"></div>

					<div class="row">
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We won a prize on the First Hackathon for Cuba, organized by Roots of Hope and Knights Foundation">
								<a href="http://raicesblog.blogspot.com/2014/02/roots-of-hope-hosts-first-ever.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/hackathonforcuba.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We were invited to talk on 1800 Online, a very popular Latin Radio Station about technology">
								<a href="http://martinoticias.org/archive/one_thousand_800_online/14/97/129.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/1800online.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We had the pleasure of work as a panelist at Hispanicize 2014, one of the most notable events about technology for Latinos on the Unites States">
								<a href="http://hispz14.sched.org/event/d586fcd1fadff0e5b84fc2995eccfd20#.VCh10vnxqTU" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/hispanicize.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="Yoani Sanchez, Cuban nobel prize nominated, wrote about Apretaste on the newspaper she founded">
								<a href="http://www.14ymedio.com/blogs/generacion_y/Apretaste_7_1537716214.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/14ymedio.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We were invited to speak on the radio station El Revoltillo, belonging to Radio Marti">
								<a href="http://www.martinoticias.com/media/video/26576.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/radiomarti.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="The Australian TV Channel 60 Minutos displayed Apretaste on a very controversial documentary about Cuba">
								<a href="http://www.jump-in.com.au/show/60minutes/stories/2014/september/a-cuban-revolution/" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/60minutes.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We had a publication on the very followed online newspaper Marti Noticias">
								<a href="http://www.martinoticias.com/content/apretaste-servicio-clasificados-por-email/31982.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/martinoticias.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We had the pleasure to speak at the online radio station PFunk">
								<a href="https://soundcloud.com/pfunk-media/9414-pfunkcast-grow-yo-and-apretastes" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/pfunk.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="The technology and society magazine Motherboard mentioned us">
								<a href="http://motherboard.vice.com/read/this-workaround-lets-26-million-cubans-surf-the-web" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/motherboard.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We were at the Sun-Sentinel's website and hardcopy. At the cover page of the business section, and above the fold">
								<a href="http://www.sun-sentinel.com/business/small-business/fl-cuba-internet-company-20151130-story.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/sunsentinel.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="We were aired at Telemundo Channel 51. A great interview conducted by Harold Santana">
								<a href="https://www.youtube.com/watch?v=hWueFyL8iMo" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/telemundo.png">
								</a>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-6">
							<div class="portfolio-item tooltip-image" data-toggle="tooltip" data-placement="top" title="What a pleasure been at Diario de Cuba; one of the most informative newspapers related to the island">
								<a href="http://www.diariodecuba.com/cuba/1449255436_18591.html" target="_blank">
									<img class="img-portfolio img-responsive img-thumbnail" src="<?php echo $wwwhttp; ?>/images/media/diariodecuba.png">
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Call to Action -->
	<section id="donate" class="call-to-action bg-customized">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">					
					<h1>Join our crusade</h1>
					<hr class="small">
					<p class="lead">Your donation is changing the lives of those who never had access to the Web; please help us keep this service alive</p>
				</div>

				<div class="col-sm-6 text-center">
					<a id="paymentBtn10" href="#" class="btn btn-lg btn-light"><i class="fa fa-credit-card"></i> Donate $10</a>
					<a id="paymentBtn30" href="#" class="btn btn-lg btn-light"><i class="fa fa-credit-card"></i> Donate $30</a>
					<a id="paymentBtn50" href="#" class="btn btn-lg btn-light"><i class="fa fa-credit-card"></i> Donate $50</a>
					<a id="paymentBtn100" href="#" class="btn btn-lg btn-light"><i class="fa fa-credit-card"></i> Donate $100</a>
					<a id="paymentBtn500" href="#" class="btn btn-lg btn-light"><i class="fa fa-credit-card"></i> Donate $500</a>

					<p style="margin-top:10px;">Please <a class="link-inverted" href="#contact">Contact Us</a> for larger donations to receive personalized benefits</p>
				</div>

				<div class="col-sm-6 hidden-xs">
					<p class="donation-amount">Once you donate you get:</p>
					<ul>
						<li>Your donations are Tax Deductible</li>
						<li>Certificate of appreciation</li>
						<li>Get into our VIP users list</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-12 text-center">
				<p style="margin-top:40px;" class="black">All donations are Tax Deductible</p>
			</div>
		</div>
	</section>

	<!-- Map -->
	<section id="contact" class="map">
		<img style="width:100%;" src="<?php echo $wwwhttp; ?>/images/map.png" alt="We are located at The LAB Miami"/>
	</section>

	<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<h1>Contact Us</h1>
					<hr class="small">
					<p><b>Apretaste</b> at The LAB Miami</p>
					<p>400 Northwest 26th Street<br>Miami, FL 33127</p>
					<ul class="list-unstyled">
						<li><i class="fa fa-phone fa-fw"></i> (305) 457-1656</li>
						<li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:support@apretaste.com">support@apretaste.com</a></li>
					</ul>
					<br>
					<ul class="list-inline">
						<li>
							<a href="https://www.facebook.com/apretaste" target="_blank"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
						</li>
						<li>
							<a href="https://twitter.com/apretaste" target="_blank"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
						</li>
					</ul>
					
					<br/>
					<p class="small">A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES BY CALLING TOLL-FREE WITHIN THE STATE 1-800-HELPFLA, OR VIA THE INTERNET AT WWW.800HELPFLA.COM. REGISTRATION DOES NOT IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY THE STATE.</p>
				</div>
			</div>
		</div>
	</footer>

	<form id="stripePaymentInfo" action="welcome/pay" method="post">
		<input type="hidden" id="stripeAmountInput" name="amount" value="10000" />
		<input type="hidden" id="stripeEmailInput" name="email" value="" />
		<input type="hidden" id="stripeTokenInput" name="stripeToken" value="" />
	</form>

	<!-- jQuery -->
	<script src="<?php echo $wwwhttp; ?>/js/jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="<?php echo $wwwhttp; ?>/js/bootstrap.min.js"></script>

	<!-- Stripe -->
	<script src="https://checkout.stripe.com/checkout.js"></script>

	<!-- Custom Theme JavaScript -->
	<script>
	// Closes the sidebar menu
	$("#menu-close").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Opens the sidebar menu
	$("#menu-toggle").click(function(e) {
		e.preventDefault();
		$("#sidebar-wrapper").toggleClass("active");
	});

	// Scrolls to the selected menu item on the page
	$(function() {
		$('a[href*=#]:not([href=#])').click(function() {
			if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

				var target = $(this.hash);
				target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
				if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 1000);
					return false;
				}
			}
		});

		$('.tooltip-image').tooltip();
	});

	// Starts a payment with Stripe
	var handler = StripeCheckout.configure({
		key: '<?php echo $stripePushibleKey; ?>',
		image: 'https://s3.amazonaws.com/stripe-uploads/acct_16M6gnLYuWaxX6xTmerchant-icon-1436316635694-apretaste.icon.big.png',
		token: function(token) {
			// Using the token and amount to create the charge with a server-side script.
			$('#stripeTokenInput').val(token.id);
			$('#stripeEmailInput').val(token.email);
			$('#stripePaymentInfo').submit();
		}
	});

	// Donate $10
	$('#paymentBtn10').on('click', function(e) {
		$('#stripeAmountInput').val(1000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 1000
		});
		e.preventDefault();
	});

	// Donate $30
	$('#paymentBtn30').on('click', function(e) {
		$('#stripeAmountInput').val(3000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 3000
		});
		e.preventDefault();
	});

	// Donate $50
	$('#paymentBtn50').on('click', function(e) {
		$('#stripeAmountInput').val(5000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 5000
		});
		e.preventDefault();
	});

	// Donate $100
	$('#paymentBtn100').on('click', function(e) {
		$('#stripeAmountInput').val(10000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 10000
		});
		e.preventDefault();
	});

	// Donate $500
	$('#paymentBtn500').on('click', function(e) {
		$('#stripeAmountInput').val(50000);
		handler.open({
			name: 'Apretaste',
			description: 'Donate using our secure form below',
			amount: 50000
		});
		e.preventDefault();
	});

	// Close Checkout on page navigation
	$(window).on('popstate', function() {
		handler.close();
	});
	</script>

	<?php require_once "$wwwroot/lib/googleAnalyticsTracking.php"; ?>
</body>
</html>