<?php if ($message!==false): ?>
	<div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
<?php endif; ?>

<?php if ($person!==false): ?>
<div class="row">
	<div class="col-xs-3">Email:</div>
	<div class="col-xs-9"><b><?php echo $person->email; ?></b></div>
	<div class="col-xs-3">Name:</div>
	<div class="col-xs-9"><b><?php echo $person->full_name; ?></b></div>
	<div class="col-xs-3">Current credit:</div>
	<div class="col-xs-9"><b>$<?php echo number_format($person->credit,2); ?></b></div>
	<div class="col-xs-3">Credit to add:</div>
	<div class="col-xs-9"><b>$<?php echo number_format($credit, 2); ?></b></div>
	<div class="col-xs-3">New credit:</div>
	<div class="col-xs-9"><b>$<?php echo number_format($newcredit,2) ; ?></b></div>
	<div class="col-xs-12">
		<br/>
		<form action="/manage/addcredit" method="POST">
			<input type="hidden" name ="email" value = "<?php echo $person->email;?>">
			<input type="hidden" name ="credit" value = "<?php echo $credit;?>">
			<a class="btn btn-default" href="/manage/addcredit">Cancel</a>
			<button type="submit" class="btn btn-primary" name="confirm">Confirm</button>
		</form>
	</div>
</div>

<?php else: ?>

<form role="form" action="/manage/addcredit" method="POST">
	<div class="form-group">
		<label for="edtEmail">Email address</label><br/>
		<input type="email" class="form-control" id="edtEmail" placeholder="Enter email" name="email">
	</div>
	<div class="form-group">
		<label for="edtCredit">Credit:</label><br/>
		<input type="number" class="form-control" placeholder="Credit" id = "edtCredit" name="credit">
	</div>

	<button type="submit" class="btn btn-default">Add credit</button>
</form>

<?php endif; ?>