<?php 
$pie_charts = array(
        'age' => 'Age',
        'gender' => 'Gender',
        'skin' => 'Skin',
        'province' => 'Province',
        'highest_school_level' => 'Highest school level',
        'marital_status' => 'Marital status',
        'sexual_orientation' => 'Sexual orientation',
        'religion' => 'Religion');
?>
<div class="row">
	<div class="col-xs-12">
		<h2><?php echo $ad->title; ?></h2>
		<p><small><?php echo date("Y-m-d m:i:s"); ?></small></p>
		
		<h2>Weekly impressions/clicks</h2>
		<div id="weeklyImpressions" style="width:900px; height:300px;"></div>
		
		<h2>Monthly impressions/clicks</h2>
		<div id="monthlyImpressions" style="width:900px; height:300px;"></div>
	</div>
</div>

<!-- Pie charts -->
<h3>Demographic</h3>
<div class="row">
  <?php foreach ($pie_charts as $idx => $label): ?>
  <div class="col-xs-8 col-md-4">
  	<div class="thumbnail">
		<div id="<?php echo $idx;?>" style="width: 300px; height: 300px;"></div>
		<center><h3><?php echo $label; ?></h3></center>
	</div>
  </div>
  <?php endforeach;?>
</div>
		
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// Weekly impressions
	google.setOnLoadCallback(weeklyImpressions);
	function weeklyImpressions() {
		var data = google.visualization.arrayToDataTable([
			['Week', 'Impressions', 'Clicks'],
			<?php if (count($weekly)>0): ?>
			<?php foreach ($weekly as $w => $data) { ?>
				['<?php echo $w; ?>',<?php echo $data['impressions']; ?>,<?php echo $data['clicks']; ?>],
			<?php } ?>
			<?php else:?>
			 []
		<?php endif;?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('weeklyImpressions'));
		chart.draw(data, {});
	}

	// Monthly impressions
	google.setOnLoadCallback(monthlyImpressions);
	function monthlyImpressions() {
		var data = google.visualization.arrayToDataTable([
			['Month', 'Impressions', 'Clicks'],
			<?php if (count($monthly)>0): ?>
			     <?php foreach ($monthly as $m => $data): ?>
					['<?php echo $m; ?>',<?php echo $data['impressions']; ?>,<?php echo $data['clicks']; ?>],
			     <?php endforeach; ?>
			<?php else:?>
				 []
			<?php endif;?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyImpressions'));
		chart.draw(data, {});
	}
	
	// Pie charts: usage by X
	google.load("visualization", "1", {packages:["corechart"]});

	<?php foreach ($pie_charts as $idx => $label): ?>
	google.setOnLoadCallback(<?php echo 'pie_'.$idx;?>);
	function <?php echo 'pie_'.$idx; $arr = 'usage_by_'.$idx; ?>() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($$arr as $a=>$t) { ?>
				['<?php echo $a; ?>',<?php echo $t; ?>],
			<?php }?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('<?php echo $idx;?>'));
		chart.draw(data, options);
	}
	<?php endforeach;?>
</script>