<div class="row">
	<div class="col-xs-12">
		<h2>Weekly traffic</h2>
		<div id="weeclyEmails" style="width:900px; height:300px;"></div>
	
		<h2>Monthly traffic</h2>
		<div id="monthlyEmails" style="width:900px; height:300px;"></div>

		<h2>Monthly unique v.s. new traffic</h2>
		<div id="monthlyNewUsers" style="width:900px; height:300px;"></div>

		<h2>Active users this month</h2>
		<p><?php echo $currentNumberOfActiveUsers; ?></p>

		<h2>Total number of users</h2>
		<p><?php echo $currentNumberOfActiveUsers + 21551; ?></p>

		<h2>Services usage (last 30 days)</h2>
		<div id="monthlyServicesUsage" style="width: 300px; height: 300px;"></div>

		<h2>Active domains (last 4 months)</h2>
		<div id="lastFourMonthActiveDomains" style="width: 300px; height: 300px;"></div>

		<h2>Monthly bounce rate</h2>
		<p class="small">Emails received only once a month</p>
		<div id="monthlyBounceRate" style="width:900px; height:300px;"></div>

		<h2>Updated Profiles</h2>
		<div id="updatedProfiles" style="width:900px; height:300px;"></div>

		<h2>Current number of running ads</h2>
		<p><?php echo $currentNumberOfRunningaAds; ?></p>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// Weecly visitors
	google.setOnLoadCallback(weeclyEmails);
	function weeclyEmails() {
		var data = google.visualization.arrayToDataTable([
			['Day of the week', 'Received', 'Sent'],
			<?php foreach ($visitorsWeecly as $data) { ?>
				['<?php echo $data['date']; ?>',<?php echo $data['received']; ?>,<?php echo $data['sent']; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('weeclyEmails'));
		chart.draw(data, {});
	}

	// Monthly visitors
	google.setOnLoadCallback(monthlyEmails);
	function monthlyEmails() {
		var data = google.visualization.arrayToDataTable([
			['Month and Year', 'Received', 'Sent'],
			<?php foreach ($visitorsMonthly as $data) { ?>
				['<?php echo $data['date']; ?>',<?php echo $data['received']; ?>,<?php echo $data['sent']; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyEmails'));
		chart.draw(data, {});
	}

	// Monthly new visitors
	google.setOnLoadCallback(monthlyNewUsers);
	function monthlyNewUsers() {
		var data = google.visualization.arrayToDataTable([
			['Month and Year', 'Unique', 'New'],
			<?php foreach ($newUsers as $data) { ?>
				['<?php echo $data['date']; ?>',<?php echo $data['unique_visitors']; ?>,<?php echo $data['new_visitors']; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyNewUsers'));
		chart.draw(data, {colors:['orange','green']});
	}

	// Monthly services usage
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(monthlyServicesUsage);
	function monthlyServicesUsage() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($servicesUsageMonthly as $data) { ?>
				['<?php echo $data['service']; ?>',<?php echo $data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('monthlyServicesUsage'));
		chart.draw(data, options);
	}

	// Active domains last 4 (four) Month
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(monthlyActiveDomains);
	function monthlyActiveDomains() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($activeDomainsMonthly as $data) { ?>
				['<?php echo $data['domain']; ?>',<?php echo $data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('lastFourMonthActiveDomains'));
		chart.draw(data, options);
	}

	// Monthly Bounce Rate
	google.setOnLoadCallback(monthlyBounceRate);
	function monthlyBounceRate() {
		var data = google.visualization.arrayToDataTable([
			['Year and Month', 'Bounce Rate'],
			<?php foreach ($bounceRateMonthly as $data) { ?>
				['<?php echo $data['date']; ?>',<?php echo $data['bounced']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none', orientation: 'horizontal'};
		var chart = new google.visualization.BarChart(document.getElementById('monthlyBounceRate'));
		chart.draw(data, options);
	}

	// Updated Profiles
	google.setOnLoadCallback(updatedProfiles);
	function updatedProfiles() {
		var data = google.visualization.arrayToDataTable([
			['Year and Month', 'Number of Profiles Updated'],
			<?php foreach ($updatedProfilesMonthly as $data) { ?>
				['<?php echo $data['date']; ?>',<?php echo $data['profiles']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none', orientation: 'horizontal'};
		var chart = new google.visualization.BarChart(document.getElementById('updatedProfiles'));
		chart.draw(data, options);
	}
</script>