<div class="row">
	<div class="col-xs-12">
		<h2>Weecly incoming emails</h2>
		<div id="weeclyIncomingEmails" style="width:900px; height:300px;"></div>
	
		<h2>Monthly incoming emails</h2>
		<div id="monthlyIncomingEmails" style="width:900px; height:300px;"></div>

		<h2>Monthly new users</h2>
		<div id="monthlyNewUsers" style="width:900px; height:300px;"></div>

		<h2>Current number of users</h2>
		<p><?php echo $currentNumberOfActiveUsers; ?></p>

		<h2>Monthly services usage</h2>
		<div id="chart_pie_services" style="width: 300px; height: 300px;"></div>

		<h2>Active domains last 4 (four) Month</h2>
		<div id="chart_pie_domains" style="width: 300px; height: 300px;"></div>

		<h2>Monthly bounce rate</h2>
		<p class="small">Emails received only once a month</p>
		<div id="monthlyBounceRate" style="width:900px; height:300px;"></div>

		<h2>Updated Profiles</h2>
		<div id="updatedProfiles" style="width:900px; height:300px;"></div>

		<h2>Current number of running ads</h2>
		<p><?php echo $currentNumberOfRunningaAds; ?></p>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// Weecly incoming emails
	google.setOnLoadCallback(weeclyIncomingEmails);
	function weeclyIncomingEmails() {
		var data = google.visualization.arrayToDataTable([
			['Day of the week', 'Emails'],
			<?php foreach ($visitorsWeecly as $data) { ?>
				['<?php echo $data['day']; ?>',<?php echo $data['emails']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.AreaChart(document.getElementById('weeclyIncomingEmails'));
		chart.draw(data, options);
	}

	// Monthly incoming emails
	google.setOnLoadCallback(monthlyIncomingEmails);
	function monthlyIncomingEmails() {
		var data = google.visualization.arrayToDataTable([
			['Month', 'Emails'],
			<?php foreach ($visitorsMonthly as $data) { ?>
				['<?php echo $data['month']; ?>',<?php echo $data['emails']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyIncomingEmails'));
		chart.draw(data, options);
	}

	// Monthly new users
	google.setOnLoadCallback(monthlyNewUsers);
	function monthlyNewUsers() {
		var data = google.visualization.arrayToDataTable([
			['Month', 'Emails'],
			<?php foreach ($newUsers as $data) { ?>
				['<?php echo $data['month']; ?>',<?php echo $data['emails']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.AreaChart(document.getElementById('monthlyNewUsers'));
		chart.draw(data, options);
	}

	// Monthly services usage
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(monthlyServicesUsage);
	function monthlyServicesUsage() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($servicesUsageMonthly as $data) { ?>
				['<?php echo $data['service']; ?>',<?php echo $data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('chart_pie_services'));
		chart.draw(data, options);
	}

	// Active domains last 4 (four) Month
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(monthlyActiveDomains);
	function monthlyActiveDomains() {
		var data = google.visualization.arrayToDataTable([
			['Caption', 'Number'],
			<?php foreach ($activeDomainsMonthly as $data) { ?>
				['<?php echo $data['domain']; ?>',<?php echo $data['usage']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none'};
		var chart = new google.visualization.PieChart(document.getElementById('chart_pie_domains'));
		chart.draw(data, options);
	}

	// Monthly Bounce Rate
	google.setOnLoadCallback(monthlyBounceRate);
	function monthlyBounceRate() {
		var data = google.visualization.arrayToDataTable([
			['Month', 'Emails'],
			<?php foreach ($bounceRateMontly as $data) { ?>
				['<?php echo $data['month']; ?>',<?php echo $data['emails']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none', orientation: 'horizontal'};
		var chart = new google.visualization.BarChart(document.getElementById('monthlyBounceRate'));
		chart.draw(data, options);
	}

	// Updated Profiles
	google.setOnLoadCallback(updatedProfiles);
	function updatedProfiles() {
		var data = google.visualization.arrayToDataTable([
			['Month', 'Emails'],
			<?php foreach ($updatedProfilesMontly as $data) { ?>
				['<?php echo $data['month']; ?>',<?php echo $data['emails']; ?>],
			<?php } ?>
		]);
		var options = {legend: 'none', orientation: 'horizontal'};
		var chart = new google.visualization.BarChart(document.getElementById('updatedProfiles'));
		chart.draw(data, options);
	}
</script>