<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($raffleMessage)) { ?>
			<div class="alert alert-success"><?php echo $raffleMessage; ?>. <a href = "/manage/raffles">Check raffles</a></div>
		<?php } ?>

		<?php if( ! empty($raffleError)) { ?>
			<div class="alert alert-danger"><?php echo $raffleError; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<form role="form" action="createraffle" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<label for="picture">Upload the picture</label>
				<p class="help-block">The picture must be a .png file, 600px by 100px with white background</p>
				<input id="picture" type="file" name="picture" required />
			</div>
			
			<div class="form-group">
				<label for="description">Describe the item to raffle</label>
				<input id="description" type="text" class="form-control" name="description" required />
			</div>

			<div class="form-group">
				<label for="startDate">Day the raffle starts</label>
				<input id="startDate" type="date" class="form-control" name="startDate" required />
			</div>

			<div class="form-group">
				<label for="endDate">Day the raffle ends</label>
				<input id="endDate" type=date class="form-control" name="endDate" required />
			</div>

			<div class="form-group">
				<br/>
				<button type="submit" class="btn btn-default">Create Raffle</button>
			</div>
		</form>
	</div>
</div>