<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($adMesssage)) { ?>
			<div class="alert alert-success"><?php echo $adMesssage; ?>. <a href = "/manage/ads">Check ads</a></div>
		<?php } ?>

		<?php if( ! empty($adError)) { ?>
			<div class="alert alert-danger"><?php echo $adError; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<form role="form" action="createad" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<label for="owner">Owner's email</label>
				<input id="owner" type="email" class="form-control" name="owner" placeholder="Owner's email" required />
			</div>

			<div class="form-group">
				<label for="title">Tittle</label>
				<input id="title" type="text" class="form-control" name="title" placeholder="A short, 100 characters summary of your offer" required />
			</div>

			<div class="form-group">
				<label for="description">Description</label>
				<textarea id="description" rows="10" class="form-control" name="description" placeholder="Up to 1000 characters explaining your offer and how to contact you" required></textarea>
			</div>

			<div class="form-group">
				<label for="picture">Upload Picture</label>
				<p class="help-block">The picture must be a .png file, 728px by 90px with white background</p>
				<input id="picture" type="file" name="picture" required />
			</div>	

			<div class="form-group">
				<br/>
				<button type="submit" class="btn btn-default">Create Ad</button>
			</div>
		</form>
	</div>
</div>
