<br/>
<div class="row">
    <div class="col-xs-6">
    	<div class="panel panel-default">
    		<div class="panel-body">
		    	<form action="/manage/delivery" method = "get">
		    		<div class="input-group">
						<input required type="email" class="form-control" name="email" id="email" placeholder="Email" data-error="Bruh, that email address is invalid" title="Insert the email of the user">
						<span class="input-group-btn">
        					<button type="submit" name="btnInsert" class="btn btn-success">Search</button>
     					 </span>	
     					 <div class="help-block with-errors"></div> 
					</div>
		    	</form>
    		</div>
    	</div>
	</div>
</div>
<?php if ($dropped): ?>
	<div class="alert alert-danger" role="alert">
		<i class = "fa fa-trash-o" aria-hidden="true"></i> This user was dropped by the system. <a href="/manage/removeDropped?email=<?php echo $userEmail;?>">Clic here for revert this situation</a>
	</div>
<?php endif;?>
<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-bordered table-hover dataTables-example">
			<thead>
				<tr>
					<th>Delivery</th>
					<th>ID</th>
					<th>Date</th>
					<th>Subject</th>
					<th>Attachments</th>
					<th>Mailbox</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($delivery as $email) { ?>
				<tr>
					<td><?php echo $email->type; ?></td>
					<td><?php echo $email->id; ?></td>
					<td><?php echo date("m/d h:i A", strtotime($email->inserted)); ?></td>
					<td><?php echo $email->subject; ?></td>
					<td><?php echo $email->attachments; ?></td>
					<td><?php echo $email->mailbox; ?></td>
				</tr>
			<?php } ?>
			</tbody>
        </table>
    </div>
</div>
<script>
 $(document).ready(function(){
         $('.dataTables-example').DataTable({
             dom: '<"html5buttons"B>lTfgitp',
             buttons: [
                 { extend: 'copy'},
                 {extend: 'csv'},
                 {extend: 'excel', title: 'ApretasteDeliveryMails'},
                 {extend: 'pdf', title: 'ApretasteDeliveryMails'},
                 {extend: 'print',
                  	customize: function (win){
                         $(win.document.body).addClass('white-bg');
                         $(win.document.body).css('font-size', '10px');

                         $(win.document.body).find('table')
                                 .addClass('compact')
                                 .css('font-size', 'inherit');
                	 }
                 }
             ]

         });
     });
 </script>