<div class="row  border-bottom white-bg dashboard-header">
	<div class="col-sm-12">
		<div class="row text-left">
			<div class="col-xs-4">
				<div class=" m-l-md">
					<span class="h4 font-bold m-t block"><?php echo $totalUsers;?></span> <small class="text-muted m-b block">Total users</small>
				</div>
			</div>
			<div class="col-xs-4">
				<span class="h4 font-bold m-t block">$ <?php echo number_format($sumCredit, 2);?></span> <small class="text-muted m-b block">Total of credit</small>
			</div>
			<div class="col-xs-4">
				<span class="h4 font-bold m-t block"><?php echo $utilization; ?></span> <small class="text-muted m-b block">Utilization</small>
			</div>
		</div>
	</div>
</div>
<br/>
<div class="row">
	<div class="col-xs-4">
		<div class="ibox float-e-margins">
			 <div class="ibox-title">
				<h5><a href="/manage/remarketing">Tasks status</a></h5>
			</div>
			<div class="ibox-content">
				<table class="table table-condensed fullscreen">
					<thead>
						<tr>
							<th>Task</th>
							<th>Days behind</th>
							<th>Delay (sec)</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($tasks as $task) { ?>
						<tr class="<?= $task->days > $task->frequency ? "danger" : "success"?>">
							<td><?= $task->task ?></td>
							<td class="text-center"><?= $task->days ?></td>
							<td class="text-center"><?= $task->delay ?></td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="ibox float-e-margins">
			 <div class="ibox-title">
				<h5><a href="/support/reports">Customer Support</a></h5>
			</div>
			<div class="ibox-content">
				<table class="fullscreen">
					<tr>
						<td>New Tickets</td>
						<td class="text-center"><?=$supportNewCount?></td>
					</tr>
					<tr>
						<td>Pending Tickets</td>
						<td class="text-center"><?=$supportPendingCount?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>

	<div class="col-xs-4">

	</div>
</div>
