<div class="row  border-bottom white-bg dashboard-header">
	<div class="col-sm-3">
		<h2>Welcome Salvi</h2>
		<small>You have 42 messages and 6 notifications.</small>
		<ul class="list-group clear-list m-t">
			<li class="list-group-item fist-item"><span class="pull-right"> 09:00 pm </span> <span class="label label-success">1</span> Please contact me</li>
			<li class="list-group-item"><span class="pull-right"> 10:16 am </span> <span class="label label-info">2</span> Sign a contract</li>
			<li class="list-group-item"><span class="pull-right"> 08:22 pm </span> <span class="label label-primary">3</span> Open new shop</li>
			<li class="list-group-item"><span class="pull-right"> 11:06 pm </span> <span class="label label-default">4</span> Call back to Sylvia</li>
			<li class="list-group-item"><span class="pull-right"> 12:00 am </span> <span class="label label-primary">5</span> Write a letter to Sandra</li>
		</ul>
	</div>
	<div class="col-sm-6">
		<div class="flot-chart dashboard-chart">
			<div class="flot-chart-content" id="flot-dashboard-chart"></div>
		</div>
		<div class="row text-left">
			<div class="col-xs-4">
				<div class=" m-l-md">
					<span class="h4 font-bold m-t block">$ 406,100</span> <small class="text-muted m-b block">Sales marketing report</small>
				</div>
			</div>
			<div class="col-xs-4">
				<span class="h4 font-bold m-t block">$ 150,401</span> <small class="text-muted m-b block">Annual sales revenue</small>
			</div>
			<div class="col-xs-4">
				<span class="h4 font-bold m-t block">$ 16,822</span> <small class="text-muted m-b block">Half-year revenue margin</small>
			</div>

		</div>
	</div>
	<div class="col-sm-3">
		<div class="statistic-box">
			<h4>Project Beta progress</h4>
			<p>You have two project with not compleated task.</p>
			<div class="row text-center">
				<div class="col-lg-6">
					<canvas id="polarChart" width="80" height="80"></canvas>
					<h5>Kolter</h5>
				</div>
				<div class="col-lg-6">
					<canvas id="doughnutChart" width="78" height="78"></canvas>
					<h5>Maxtor</h5>
				</div>
			</div>
			<div class="m-t">
				<small>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
			</div>

		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-4">
		
	</div>

	<div class="col-xs-4">
		

		<div class="panel panel-default">
			<div class="panel-heading">
				<a href="/manage/remarketing">Tasks status</a>
			</div>
			<div class="panel-body">
				<table class="table table-condensed fullscreen">
					<thead>
						<tr>
							<th>Task</th>
							<th>Days behind</th>
							<th>Delay (sec)</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($tasks as $task): ?>
						<tr class="<?= $task->days > $task->frequency ? "danger" : "success"?>">
							<td><?= $task->task ?></td>
							<td class="text-center"><?= $task->days ?></td>
							<td class="text-center"><?= $task->delay ?></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="panel panel-<?= $deliveryFailurePercentage > 2 ? "danger" : "success"; ?>">
			<div class="panel-heading">
				<a href="/manage/dropped">Delivery status</a> <small>(Last 7 days)</small>
			</div>
			<div class="panel-body">
				<table class="fullscreen">
					<tr>
						<td width="50%">delivered: <?= number_format($delivery['delivered']); ?></td>
						<td>hardfail: <?= isset($delivery['hardfail']) ? $delivery['hardfail'] : 0; ?> (<?= $deliveryFailurePercentage; ?>%)</td>
					</tr>
					<tr>
						<td width="50%">hard-bounce: <?= isset($delivery['hard-bounce']) ? $delivery['hard-bounce'] : 0; ?></td>
						<td>soft-bounce: <?= isset($delivery['soft-bounce']) ? $delivery['soft-bounce'] : 0; ?></td>
					</tr>
					<tr>
						<td width="50%">spam: <?= isset($delivery['span']) ? $delivery['span'] : 0; ?></td>
						<td>no-reply: <?= isset($delivery['no-reply']) ? $delivery['no-reply'] : 0; ?></td>
					</tr>
					<tr>
						<td width="50%">loop: <?= isset($delivery['loop']) ? $delivery['loop'] : 0; ?></td>
						<td>temporal: <?= isset($delivery['temporal']) ? $delivery['temporal'] : 0; ?></td>
					</tr>
					<tr>
						<td width="50%">failure: <?= isset($delivery['failure']) ? $delivery['failure'] : 0; ?></td>
						<td>unknown: <?= isset($delivery['unknown']) ? $delivery['unknown'] : 0; ?></td>
					</tr>
				</table>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">Promoters (unpaid)</div>
			<div class="panel-body">
				<table class="table table-condensed fullscreen">
					<thead>
						<tr>
							<th>Promoter</th>
							<th class="text-center">Total</th>
							<th class="text-center">Last</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($promoters as $promoter): ?>
						<?php $daysElapsed = (time() - strtotime($promoter->latest))/60/60/24; ?>
						<tr <?php if($daysElapsed > 31) echo 'class="danger"'; ?>>
							<td><?= $promoter->source ?></td>
							<td class="text-center"><?= $promoter->total ?></td>
							<td class="text-center"><?= date("m/d/y", strtotime($promoter->latest)) ?></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>