<div class="row">
	<div class="col-xs-4">
		<p>Welcome to Apretaste's management tool.</p>
		<br/>
	</div>
</div>

<div class="row">
	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Analytics</div>
			<div class="panel-body">
				<a href="manage/audience">Audience</a><br/>
				<a href="manage/profile">Profile</a><br/>
				<a href="manage/profilesearch">Profile Search</a><br/>
				<a href="manage/raffles">Raffles</a><br/>
				<a href="manage/services">Services</a><br/>
				<a href="manage/ads">Ads</a><br/>
			</div>
		</div>

		<div class="panel panel-success">
			<div class="panel-heading">Developer</div>
			<div class="panel-body">
				<a href="manage/deploy">Deploy</a><br/>
				<a href="data" target="_blank">phpMyAdmin <small><i class="fa fa-external-link"></i></small></a><br/>
				<a href="https://rpm.newrelic.com" target="_blank">New Relic <small><i class="fa fa-external-link"></i></small></a><br/>
				<a href="https://mandrillapp.com" target="_blank">Mandrill <small><i class="fa fa-external-link"></i></small></a><br/>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Admin</div>
			<div class="panel-body">
				<a href="manage/createad">Create ad</a><br/>
				<a href="manage/createraffle">Create raffle</a><br/>
				<a href="manage/jumper">Jumper</a><br/>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="alert alert-<?php echo isset($revolicoCrawler["TimeBehind"]) && $revolicoCrawler["TimeBehind"] < 24 ? "success" : "danger"; ?>" role="alert">
			<p><b>Revolico crawler</b></p>
			<p>Last run: <?php if(isset($revolicoCrawler["LastRun"])) echo $revolicoCrawler["LastRun"]; ?></p>
			<p>Time behind: <?php if(isset($revolicoCrawler["TimeBehind"])) echo $revolicoCrawler["TimeBehind"]; ?> hours</p>
			<p>Running time: <?php if(isset($revolicoCrawler["RuningTime"])) echo $revolicoCrawler["RuningTime"]; ?> minutes</p>
			<p>Posts downloaded: <?php if(isset($revolicoCrawler["PostsDownloaded"])) echo $revolicoCrawler["PostsDownloaded"]; ?></p>
			<p>Memory used: <?php if(isset($revolicoCrawler["RuningMemory"])) echo $revolicoCrawler["RuningMemory"]; ?></p>
		</div>
	</div>
</div>