<div class="row">
	<div class="col-xs-12">
		<table id="adsTable" class="table">
			<thead>
				<tr>
					<th>Email</th>
					<th class="text-center">Last Usage</th>
					<th class="text-center">Emails Sent</th>
					<th class="text-center">Status</th>
					<th class="text-center">Blocked Domains</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($jumperData as $jumper) { ?>
				<tr <?php if($jumper->status == "Inactive") echo 'class="danger"'; ?>>
					<td><?php echo $jumper->email; ?></td>
					<td class="text-center"><?php echo date("Y/m/d H:i:s", strtotime($jumper->last_usage)); ?></td>
					<td class="text-center"><?php echo $jumper->sent_count; ?></td>
					<td class="text-center"><?php echo $jumper->status; ?></td>
					<td><?php echo $jumper->blocked_domains; ?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
