<script src="/js/jquery.flot.js"></script>
<script src="/js/jquery.flot.tooltip.min.js"></script>
<script src="/js/jquery.flot.resize.js"></script>
<script src="/js/jquery.flot.pie.js"></script>
<script src="/js/jquery.flot.time.js"></script>
<div class="row">
	<div class="col-xs-12">
		
			<div id = "weekly" class="panel panel-default" style="width:500px;height:500px;">
			
			</div>
	
	</div>
</div>

<script>
	$(function(){

		var barOptions = {
		        series: {
		            bars: {
		                show: true,
		                barWidth: 0.6,
		                fill: true,
		                fillColor: {
		                    colors: [{
		                        opacity: 0.8
		                    }, {
		                        opacity: 0.8
		                    }]
		                }
		            }
		        },
		        xaxis: {
		            tickDecimals: 0
		        },
		        colors: ["#1ab394"],
		        grid: {
		            color: "#999999",
		            hoverable: true,
		            clickable: true,
		            tickColor: "#D4D4D4",
		            borderWidth:0
		        },
		        legend: {
		            show: false
		        },
		        tooltip: true,
		        tooltipOpts: {
		            content: "x: %x, y: %y"
		        }
		    };
		    var barData = {
		        label: "bar",
		        data: [
		            [1, 34],
		            [2, 25],
		            [3, 19],
		            [4, 34],
		            [5, 32],
		            [6, 44]
		        ]
		    };
		    
		$.plot($("#weekly"), [barData], barOptions);
	});
</script>