<div class="row">
	<div class="col-xs-12">
	<?php if (isset($message)):?>
	<?php if ($message!==false): ?>
		<div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
		<?php endif;?>
	<?php endif;?>
	</div>
	
	<!-- New product -->
	<button type="button" class="btn btn-success" onclick="$('#newProductForm-modal').modal('show');">
		<span class="glyphicon glyphicon-plus"></span> New product
	</button>
	
	<!-- Filtering -->
	<button type="button" class="btn btn-default" onclick="$('.product-active').show();$('.product-non-active').show();">
		<span class="glyphicon glyphicon-asterisk"></span> All
	</button>
	<button type="button" class="btn btn-default" onclick="$('.product-active').show();$('.product-non-active').hide();">
		<span class="glyphicon glyphicon-check"></span> Actives
	</button>
	<button type="button" class="btn btn-default" onclick="$('.product-active').hide();$('.product-non-active').show();">
		<span class="glyphicon glyphicon-unchecked"></span> Non actives
	</button>
	
	
	<!-- New product modal form -->
	<div class="modal fade tooltips" id="newProductForm-modal" tabindex="-1" role="dialog" aria-labelledby="newProductForm-label" aria-hidden="true"> 
		<div class="modal-dialog" style="width:500px;"> 
			<div class="modal-content"> 
				<div class="modal-header"> 
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button> 
					<h4 class="modal-title" id="newProductForm-label">New product</h4>
				</div>
				<div class="modal-body"> 
					<form role="form" action = "/manage/marketNewProduct" method = "post" id="newProductForm" enctype="multipart" data-toggle="validator">
					
						<div class="form-group">
							<label for="edtName">Name</label>
							<input required type="text" class="form-control text" name="edtName" id="edtName" placeholder="name of the product" title="Insert name of the product">						
						</div>
						
						<div class="form-group">
							<label for="edtDesc">Description</label>
							<textarea class="form-control" name="edtDesc" id="edtDesc"></textarea>						
						</div>
						
						<div class="form-group">
							<label for="edtCategory">Category</label>
							<select required class="form-control" name="edtCategory" id="edtCategory">
								<option value="mobile">Mobile</option>
								<option value="accessory">Accessory</option>
								<option value="computer">Computer</option>
								<option value="peripheral">Peripheral</option>
								<option value="clothe">Clothe</option>
								<option value="service">Service</option>
							</select>						
						</div>
						<div class="form-group">
							<label for="edtPrice">Pricing</label>
							<table>
								<tr>
									<td><span>Price:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtPrice" id="edtPrice"></td>
									<td><span>&nbsp;Shipping:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtShippingPrice" id="edtShippingPrice"></td>
									<td><span>&nbsp;Credits:</span>&nbsp;</td><td><input required type="text" class="form-control text" name="edtCredits" id="edtCredits"></td>
							</table>
						</div>
						
						<div class="form-group">
							<label for="edtAgency">Agency</label>
							<input required type="text" class="form-control text" name="edtAgency" id="edtAgency" placeholder="name of the agency" title="Insert name of the product">						
						</div>
						
						<div class="form-group">
							<label for="edtOwner" class="control-label">Owner</label>
							<input required type="email" class="form-control" name="edtOwner" id="edtOwner"placeholder="Email" data-error="Bruh, that email address is invalid" title="Insert the email of the product's owner">
							<div class="help-block with-errors"></div> 						
						</div>
					</div>
					<div class="modal-footer"> 
						<button type="submit" name="btnInsert" class="btn btn-success">Insert</button>
						<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button> 
					</div> 
				</form>
			</div>
		</div>
	</div>
	
 
	<table id="marketTable" class="table">
		<thead>
			<tr>
				<th>Active</th>
				<th>Code</th>
				<th>Name</th>
				<th>Price</th>
				<th>Shipping price</th>
				<th>Credits</th>
				<th>Agency</th>
				<th>Owner</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($products as $product): ?>
				<tr id = "<?php echo $product->code; ?>" <?php if ($product->active == '1'):?> class = "product-active" <?php else: ?> class = "product-non-active" <?php endif;?>>
					<?php if ($product->active == '1'):?>
					<td ><button onclick="toggleActivation('<?php echo $product->code;?>');" class="btn btn-default"><span class="toggle-active-icon glyphicon glyphicon-check"></span></button></td>
					<?php else:?>
					<td><button onclick="toggleActivation('<?php echo $product->code;?>');" class="btn btn-default"><span class="toggle-active-icon glyphicon glyphicon-unchecked"></span></button></td>
					<?php endif;?>
					<td><?php echo $product->code; ?></td>
					<td><?php echo $product->name; ?></td>
					<td><?php echo $product->price; ?></td>
					<td><?php echo $product->shipping_price; ?></td>
					<td><?php echo $product->credits; ?></td>
					<td><?php echo $product->agency; ?></td>
					<td><a href="mailto:<?php echo $product->owner;?>"><?php echo $product->owner;?></a></td>
					<td>
						<a href="/manage/marketDetail/<?php echo $product->code;?>" class="btn btn-success"><span class="glyphicon glyphicon-edit"></span></a>
						<a onclick ="return confirm('Are you sure?');" href="/manage/marketDelete/<?php echo $product->code;?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
					
				</tr>
			<?php endforeach;?>
		</tbody>
</div>

<script>
	function toggleActivation(code)
	{
		jQuery.ajax({
			url: "/manage/marketToggleActivation",
			type: "POST",
			async: false,
			data: {code: code},
			complete: function(res, status){
		       	 if ( status == "success" || status == "notmodified" ){
		           	 if (res.responseText == '1')
		           	 {
		       		 	$("#"+code+" span.toggle-active-icon").attr('class', 'glyphicon glyphicon-check');
		       		 	$("#"+code).attr('class', 'product-active');
		       		 	$.notify({
			       		 	icon: 'glyphicon glyphicon-check', 
			       		 	message: 'The product <b>'+ code + '</b> was activated'
				       	},
				       	{
					       	type: 'success',
					       	animate: {
				       				enter: 'animated fadeInDown',
				       				exit: 'animated fadeOutUp'
			       			}
		       			});
		           	 }
		           	 else
		           	 {
		           		$("#"+code+" span.toggle-active-icon").attr('class', 'glyphicon glyphicon-unchecked');
		           		$("#"+code).attr('class', 'product-non-active');
		           		$.notify({
			           		icon: 'glyphicon glyphicon-unchecked', 
			           		message: 'The product  <b>'+ code + '</b> was deactivated'
				        },
				        {
					        type: 'success',
					       	animate: {
			       				enter: 'animated fadeInDown',
			       				exit: 'animated fadeOutUp'
		       				}
	       				});
		           	 }
		           	
		           	
		       	 }
	        }
		});
	}
</script>