<div class="row">
	<div class="col-xs-12">
	<?php if (isset($message)):?>
	<?php if ($message!==false): ?>
		<div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
		<?php endif;?>
	<?php endif;?>
	</div>
	<table id="marketTable" class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Product</th>
				<th>User</th>
				<th>Date</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($orders as $order): ?>
				<tr>
				<td><?php echo $order->id; ?></td>
				<td><a href= "#" onclick = "showProduct('<?php echo $order->product; ?>');"><?php echo $order->product_name; ?></a></td>
				<td><?php echo $order->email; ?></td>
				<td><?php echo $order->inserted_date; ?></td>
				<td>
					<a href="/manage/marketDestination/<?php echo $order->id; ?>" class="btn btn-info">Destination</a>
				</td>
				
			</tr>
		<?php endforeach;?>
	</tbody>
</div>

<!-- product modal -->
<div class="modal fade tooltips" id="product-modal" tabindex="-1" role="dialog" aria-labelledby="product-name" aria-hidden="true"> 
	<div class="modal-dialog" style="width:600px;"> 
		<div class="modal-content"> 
			<div class="modal-header"> 
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button> 
				<h4 class="modal-title" id="product-name"></h4>
			</div>
			<div class="modal-body"> 
				<div class = "row">
					<div class = "col-md-5">
						<img style="margin: 5px;" src="/products/code" id ="product-picture">
					</div>
					<div class = "col-md-7">
						<p>Price: <br/>
						<span id="product-price"></span><br/>
						Shipping price: <br/>
						<span id="product-shipping"></span><br/>
						Credits: <br/>
						<span id="product-credits"></span><br/>
						Agency: <br/>
						<span id="product-agency"></span><br/>
						</p>
					</div>
				</div>
			</div>
			<div class="modal-footer"> 
				<button type="button" class="btn btn-success" data-dismiss="modal">Close</button> 
			</div> 
		</div>
	</div>
</div>

<style>
	#product-modal span{
		font-weight: bold;
	}
</style>
<script>
	function showProduct(code)
	{
		$("#product-modal").modal('show');
		$("#product-picture").attr('src', "/products/" + code);

		var product = {};
		
		jQuery.ajax({
			url: "/ajax/getMarketProduct",
			type: "POST",
			async: false,
			data: {code: code},
			complete: function(res, status){
		       	 if ( status == "success" || status == "notmodified" ){
		           	var result = {};
	           		eval('result = ' + res.responseText + ';');
	           		product = result.product; 
	           		$("#product-price").html(product.price_friendly);
	           		$("#product-shipping").html(product.shipping_price_friendly);
	           		$("#product-credits").html(product.credits_friendly);
	           		$("#product-name").html(product.name);
	           		$("#product-agency").html(product.agency);
		         }
			}
		});
		
	}
</Script>