<style type="text/css">
	.form-group{
		margin-top: 20px;
	}
</style>

<div class="row">
	<div class="col-xs-12">
		<form id="form" role="form" action="newCampaignSubmit" method="POST">
			<!-- Subject of the email -->
			<div class="form-group">
				<label for="subject">Subject</label>
				<input id="subject" type="text" class="form-control" name="subject" required />
			</div>

			<!-- Date to send the email -->
			<div class="form-group">
				<label for="date">Day and time to send the campaign</label>
				<input id="date" type="datetime-local" value="<?=$date?>" class="form-control" name="date" required />
			</div>

			<!-- Create the editor container -->
			<div class="form-group">
				<label for="content">Content of the email</label>
				<p>Available tags: {{APRETASTE_EMAIL}} {{APRETASTE_NAME}}</p>
				<textarea id="content" name="content"><?=$layout?></textarea>
			</div>

			<!-- Test the email before sending -->
			<div class="form-group">
				<label for="test">Test the email before sending</label>
				<div class="input-group">
					<input id="test" type="email" value="salvi@apretaste.com" class="form-control" />
					<span class="input-group-btn">
						<button type="button" onclick="testEmail();" class="btn btn-default">Test</button>
					</span>
				</div>
				<p id="sent" style="color:green; font-size:small; display:none;"></p>
			</div>

			<div class="form-group">
				<a class="btn btn-default" href="campaigns">Cancel</a>
				<button class="btn btn-primary" type="submit" onclick="return confirm('Do you want to create this campaign?');">Create campaign</button>
			</div>
		</form>
	</div>
</div>

<!-- Initialize the editor -->
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
	tinymce.init({
		selector: '#content',
		height: 500,
		theme: 'modern',
		plugins: [
			'advlist autolink lists link image charmap print preview hr anchor pagebreak',
			'searchreplace wordcount visualblocks visualchars code fullscreen',
			'insertdatetime media nonbreaking save table contextmenu directionality',
			'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
		],
		toolbar1: 'undo redo | insert | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link emoticons codesample'
	});

	function testEmail(){
		var email = $('#test').val();
		var subject = $('#subject').val();
		var content = $('#content').val();

		$.ajax({
			url: "testCampaignAsync",
			method: "POST",
			variables: {"email":email, "subject":subject, "content":content},
			async: false
		}).done(function(data) {
			$("#sent").html('Text email sent to '+email).show();
		});
	}
</script>
