<div class="row">
	<div class="col-xs-12">
		<h2>Emails sent</h2>
		<div id="remarketSent" style="width:100%; height:400px;"></div>

		<h2>Emails opened</h2>
		<div id="remarketOpened" style="width:100%; height:400px;"></div>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	google.load("visualization", "1", {packages:["corechart"]});

	// emails sent
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['day','reminder1','reminder2','excluded','invited','autoinvited','survey','error'],
			<?php foreach ($sent as $data) { ?>
			['<?php echo date("D j", strtotime($data->moment)); ?>',
				<?php echo $data->reminder1; ?>,
				<?php echo $data->reminder2; ?>,
				<?php echo $data->excluded; ?>,
				<?php echo $data->invite; ?>,
				<?php echo $data->autoinvite; ?>,
				<?php echo $data->survey; ?>,
				<?php echo $data->error; ?>],
				<?php } ?>
			]);
		var chart = new google.visualization.AreaChart(document.getElementById('remarketSent'));
		chart.draw(data, {});
	});

	// emails opened
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['day','reminder1','reminder2','excluded','invited','autoinvited','survey','error'],
			<?php foreach ($opened as $data) { ?>
				['<?php echo date("D j", strtotime($data->moment)); ?>',
				<?php echo $data->reminder1; ?>,
				<?php echo $data->reminder2; ?>,
				<?php echo $data->excluded; ?>,
				<?php echo $data->invite; ?>,
				<?php echo $data->autoinvite; ?>,
				<?php echo $data->survey; ?>,
				<?php echo $data->error; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('remarketOpened'));
		chart.draw(data, {});
	});
</script>