<div class="row">
	<div class="col-xs-12">
		<h2>Returning users per day</h2>
		<div id="remarket" style="width:900px; height:300px;"></div>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['Remarket', 'Emails'],
			<?php foreach ($remarketed as $data) { ?>
				['<?php echo $data->date; ?>', <?php echo $data->number; ?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('remarket'));
		var options = {legend: 'none'};
		chart.draw(data, options);
	});
</script>