<br/>
<?php if ($message!==false): ?>
	<div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
<?php endif;?>
<br/>
<div class="row">
    <div class="col-xs-6">
    	<div class="panel panel-default">
    		<div class="panel-body">
		    	<form action="/manage/removeDropped" method = "get">
		    		<div class="input-group">
						<input required type="email" class="form-control" name="email" id="email" placeholder="Email" data-error="Bruh, that email address is invalid" title="Insert the email of the user">
						<span class="input-group-btn">
        					<button type="submit" name="btnInsert" class="btn btn-success">Search & Remove</button>
     					 </span>	
     					 <div class="help-block with-errors"></div> 
					</div>
		    	</form>
    		</div>
    	</div>
	</div>
</div>