<div class="row">
    <div class="col-xs-12">
        <br/>
        <?php if ($message !== false): ?>
            <div class="alert alert-<?php echo $message_type; ?>" role="alert"><?php echo $message; ?></div>
        <?php endif; ?>
        <br/>
        <p align="right"><a class="btn btn-default" href="/manage/schoolTeachers"><i class="fa fa-user-secret fa-2x" aria-hidden="true"></i><br/>Teachers</a></p>
        <br/>
        <div class="panel">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Teachers</h5>
                    <div class="ibox-tools">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="/manage/schoolNewChapter?type=CAPITULO&course=<?php echo $course->id; ?>"><span class="glyphicon glyphicon-plus"></span> New chapter</a>
                            </li>
                            <li>
                                <a href="/manage/schoolNewChapter?type=PRUEBA&course=<?php echo $course->id; ?>"><span class="glyphicon glyphicon-plus"></span> New test</a>                
                            </li>
                        </ul>
                        <a class="close-link">
                            &nbsp;
                        </a>
                    </div>
                </div>
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <table id="marketTable" class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Teacher</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($courses as $course): ?>
                                    <tr>
                                <form action="/manage/school?option=set&id=<?php echo $course->id; ?>" method="post">
                                    <td width="50"><?php echo $course->id; ?></td>
                                    <td><input class="form-control" name="courseTitle" placeholder="Course title" value ="<?php echo $course->title; ?>"></td>
                                    <td>
                                        <select class="form-control" name="courseTeacher">
                                            <?php foreach ($teachers as $teacher): ?>
                                                <option value ="<?php echo $teacher->id; ?>" <?php echo $course->teacher == $teacher->id ? 'selected' : ''; ?>><?php echo $teacher->name . ', ' . $teacher->title; ?></options>
                                                <?php endforeach; ?>
                                        </select>
                                    </td>
                                    <td><button class="btn btn-default" type="submit" name="courseSubmit"><i class="fa fa-floppy-o" aria-hidden="true"></i></button></td>
                                </form>

                                <td><a href="/manage/schoolChapters?course=<?php echo $course->id; ?>" class="btn btn-default" >Chapters</a></td>
                                <td>
                                    <?php if ($course->active . '' == '1'): ?>
                                        <a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/school?option=disable&id=<?php echo $course->id; ?>">Disable</a>
                                    <?php else: ?>
                                        <a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/school?option=enable&id=<?php echo $course->id; ?>">Enable</a>
                                    <?php endif; ?>
                                </td>
                                <td><a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/school?option=del&id=<?php echo $course->id; ?>"><span class="glyphicon glyphicon-trash"></span></a></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <button type="button" class="btn btn-primary" onclick="$('#newCourseForm-modal').modal('show');">
                        <span class="glyphicon glyphicon-plus"></span> New course
                    </button>

                    <!-- New course modal form -->
                    <div class="modal fade tooltips" id="newCourseForm-modal" tabindex="-1" role="dialog" aria-labelledby="newCourseForm-label" aria-hidden="true"> 
                        <div class="modal-dialog" style="width:500px;"> 
                            <div class="modal-content"> 
                                <div class="modal-header"> 
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button> 
                                    <h4 class="modal-title" id="newCourseForm-label"><i class="fa fa-book fa-1x" aria-hidden="true"></i> New course</h4>
                                </div>
                                <div class="modal-body"> 
                                    <form role="form" action = "/manage/school?option=add" method = "post" id="newCourseForm" enctype="multipart" data-toggle="validator">
                                        <div class="form-group">
                                            <label for="courseTitle">Title</label>
                                            <input required type="text" class="form-control text" name="courseTitle" id="courseTitle" placeholder="title of the course" title="Insert title of the course">						
                                        </div>

                                        <div class="form-group">
                                            <label for="courseTeacher">Teacher</label>
                                            <select required class="form-control" name="courseTeacher" id ="courseTeacher">
                                                <?php foreach ($teachers as $teacher): ?>
                                                    <option value ="<?php echo $teacher->id; ?>"><?php echo $teacher->name . ', ' . $teacher->title; ?></options>
                                                    <?php endforeach; ?>
                                            </select>
                                        </div>     

                                        <div class="form-group">								
                                            <label for="courseContent">Resume</label>
                                            <textarea class="form-control" name="courseContent" id="courseContent"></textarea>
                                        </div>
                                        <div class="modal-footer"> 
                                            <button type="submit" name="btnInsert" class="btn btn-success">Insert</button>
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button> 
                                        </div> 
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.dataTables-example').DataTable({
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                {extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ApretasteSchoolChapters'},
                {extend: 'pdf', title: 'ApretasteSchoolChapters'},
                {extend: 'print',
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ]
        });
    });
</script>

