<style type="text/css">
    .form-group{
        margin-top: 20px;
    }
</style>
<div class="row">
    <div class="col-xs-12">
    <?php if ($message!==false): ?>
        <div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
    <?php endif;?>
    <br/>
    <div class="panel">
        <div class="panel-body">
            <form action ="/manage/schoolNewChapterPost?course=<?php echo $course->id; ?>" method="POST">
                <input type="hidden" value="<?php echo $type; ?>" name="type">
                <div class="form-group">
                    <label for="title">Title:</label>
                    <input required type="text" class="form-control text" name="title" id="title" placeholder="title" title="Insert title">						
                </div>
                <div class="form-group">
                    <label for="content">
                        <?php echo $type=='CAPITULO'? 'Content of the chapter' : 'Explanation'; ?>
                    </label><br/>
                    <textarea id="content" name="content"></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-default" type="submit" onclick="return getcontent();">Save</button>
                    <a class="btn btn-default" href="/manage/schoolChapters?course=<?php echo $course->id; ?>">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="/js/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: '#content',
        height: 500,
        theme: 'modern',
        plugins: [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc bdesk_photo'
        ],
        toolbar1: 'undo redo | insert | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link emoticons codesample'
    });
</script>
