<div class="row">
	<div class="col-xs-12"> 
		<table id="servicesTable" class="table">
			<thead>
				<tr>
					<th>Details</th>
					<th>Description</th>
					<th class="text-center">Deploy Key</th>
					<th class="text-center">Inserted</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($services as $service) { ?>
				<tr>
					<td>
						<b><?php echo $service->name; ?></b> 
						<span class="label label-primary"><?php echo $service->category; ?></span><br/>
						<?php echo $service->creator_email; ?><br/>
					</td>
					<td><?php echo $service->description; ?></td>
					<td class="text-center"><?php echo $service->deploy_key; ?></td>
					<td class="text-center"><?php echo date("Y/m/d H:i:s", strtotime($service->insertion_date)); ?></td>
					<td class="text-center">
						<a class="btn btn-default" target="_blank" href="/run/display?subject=<?php echo $service->name; ?>">Run</a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>