<div class="row">
	<div class="col-xs-12">
		<table id="servicesTable" class="table">
			<thead>
				<tr>
					<th>Details</th>
					<th>Description</th>
					<th class="text-center">Group</th>
					<th class="text-center">Category</th>
					<th class="text-center" style="text-decoration: underline;" title="Last 30 days">Usage</th>
					<th class="text-center" style="text-decoration: underline;" title="Average of the last 30 days, in seconds">Latency</th>
					<th class="text-center">Inserted</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach ($services as $service) {
					// set the color for the latency alert
					$latencyWarning = "";
					if($service->avg_latency > 5) $latencyWarning = "warning";
					if($service->avg_latency > 10) $latencyWarning = "danger";
				?>
				<tr>
					<td>
						<b><?=$service->name?></b>
						<?php if( ! $service->listed) { ?><span class="label label-default">hidden</span><?php } ?>
						<br/>
						<?=$service->creator_email?>
					</td>
					<td><?=$service->description?></td>
					<td class="text-center"><div id="group_<?=$service->name?>"><?=$service->group?></div></td>
					<td class="text-center"><?=$service->category?></td>
					<td class="text-center"><?=$service->times_used?></td>
					<td class="text-center <?=$latencyWarning?>"><?=number_format($service->avg_latency, 2)?></td>
					<td class="text-center"><?=date("Y/m/d H:i:s", strtotime($service->insertion_date))?></td>
					<td class="text-center">
						<nobr>
						<a class="btn btn-default" target="_blank" href="/run/display?subject=<?=$service->name?>">Run</a>
						<a class="btn btn-default" href="#" onclick="editService('<?=$service->name?>');"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
						</nobr>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal for add a new list -->
<div id="editService" class="modal fade" role="dialog">
	<form action="/manage/editServiceSubmit" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Edit service</h4>
				</div>
				<div class="modal-body">
					<!-- GROUP -->
					<div class="form-group">
						<label for="group">Group name</label>
						<input id="group" type="text" name="group" class="form-control" required />
					</div>
				</div>
				<div class="modal-footer">
					<input id="name" type="hidden" name="name" value=""/>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Submit"/>
				</div>
			</div>
		</div>
	</form>
</div>

<script type="text/javascript">
	function editService(name){
		var group = $('#group_'+name).html();
		$('#group').val(group);
		$('#name').val(name);
		$('#editService').modal('show');
	}
</script>
