<?php
	$trans = array(
		'LA HABANA' => 'CH',
		'PINAR DEL RIO' => 'PR',
		'MATANZAS' => 'MA',
		'MAYABEQUE' => 'MY',
		'ARTEMISA' => 'AR',
		'VILLA CLARA' => 'VC',
		'SANCTI SPIRITUS' => 'SS',
		'CIEGO DE AVILA' => 'CA',
		'CIENFUEGOS' => 'CF',
		'CAMAGUEY' => 'CM',
		'LAS TUNAS' => 'LT',
		'HOLGUIN' => 'HL',
		'GRANMA' => 'GR',
		'SANTIAGO DE CUBA' => 'SC',
		'GUANTANAMO' => 'GU',
		'ISLA DE LA JUVENTUD' => 'IJ'
	);
?>

<div class="row">
	<div class="col-xs-10">
		<h2 style="margin: 0px 0px 20px 0px;"><?php echo $survey->title; ?></h2>
	</div>
	<div class="col-xs-2 text-right">
		<a href="/manage/surveyReportPDF/<?php echo $survey->id; ?>" class="btn btn-default">Download as PDF</a>
		<a href="/manage/surveyResultsCSV/<?php echo $survey->id; ?>" class="btn btn-default">Download as CSV</a>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		Legend: 
		<?php foreach ($results as $field => $result): ?>
			<a class="btn btn-small" href="#<?php echo $field;?>"><?php echo $result['label']; ?></a>
		<?php endforeach;?>
	</div>
	<div class="col-xs-12">
		<?php foreach ($results as $field => $result): ?>
			<h3 id="<?php echo $field; ?>"><?php echo strtoupper($result['label']); ?></h3>
			<div class="panel panel-default">
				<table class="table table-fixedheader table-bordered table-striped">
					<thead>
						<th width="25%"></th>
						<th width="50" class="text-center">Total</th>
						<th width="50" class="text-center">%</th>
							<?php foreach ($result['pivots'] as $pivot => $label): ?>
								<th width="50" class="text-center" title="<?php echo $label; ?>"><?php echo isset($trans[$label])?$trans[$label]:$label; ?></th>
							<?php endforeach;?>
					</thead>
					<tbody>
						<?php foreach($result['results'] as $question): ?>
							<tr class="success">
								<td id="q<?php echo $question['i']; ?>" colspan="<?php echo count($result['pivots']) + 3;?>"><b><?php echo $question['t']; ?></b></td>
							</tr>
							<?php foreach($question['a'] as $ans): ?>
								<tr>
									<td bgcolor="#eeeeee"><?php echo $ans['t']; ?></td>
									<td bgcolor="#eeeeee" align="right" <?php if ( $result['totals'][$ans['i']]*1 === 0):?> style="color: red;" <?php endif;?>><?php echo $result['totals'][$ans['i']]; ?></td>
									<td bgcolor="#eeeeee" align="right"><?php if (isset($quetion['total'])) echo $question['total'] !== 0?number_format($result['totals'][$ans['i']] / $question['total'] * 100, 1):0; ?>%</td>
									<?php foreach ($result['pivots'] as $pivot => $label): ?>
										<td align="right">
											<?php if (!isset($ans['p'][$pivot])): ?> 
												<?php echo "0.0%"; ?>
											<?php else: ?> 
												<?php echo $result['totals'][$ans['i']] == 0?"0.0":number_format($ans['p'][$pivot] / $result['totals'][$ans['i']] * 100, 1); ?>%
											<?php endif; ?>
										</td>
									<?php endforeach;?>
								</tr>
							<?php endforeach;?>
						<?php endforeach;?>
					</tbody>
				</table>
			</div>
		<?php endforeach; ?>
	</div>
</div>

