<div class="row">
	<div class="col-xs-12">
	<h2><?php echo $survey->title; ?></h2>
	<p>Total questions: <?php echo $results[0]->total; ?></p>
		<table id="servicesTable" class="table">
		<tr><th>Email</th><th>Questions answered</th><th>Completion</th></tr>
		<?php foreach($results as $item): ?>
		<tr><td><?php echo $item->email;?></td><td><?php echo $item->choosen; ?></td>
		<td>
		<div class="progress">
		<?php $p = number_format($item->choosen/$item->total*100,1); ?>
           <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?php echo $p; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $p;?>%">
            <span><?php echo $p;?>%</span>
          </div>
        </div>
        </tr>
		<?php endforeach;?>
		</table>
	</div>
</div>
