<div class="row">
	<div class="col-xs-12">
	<?php if ($message!==false): ?>
	<div class="alert alert-<?php echo $message_type;?>" role="alert"><?php echo $message;?></div>
	<?php endif;?>
		<table id="servicesTable" class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Survey</th>
					<th>Customer</th>
					<th>Deadline</th>
				</tr>
			</thead>
			<tbody>
			<?php
foreach ($surveys as $survey) {
    ?>
				<tr>
					<form action="/manage/surveys?option=setSurvey&id=<?php echo $survey->id; ?>" method="post">
						<td width="50"><?php echo $survey->id; ?></td>
						<td><input class="form-control" name="surveyTitle" placeholder="Survey title" value ="<?php echo $survey->title;?>"></td>
						<td><input class="form-control" name="surveyCustomer" placeholder="Customer email" value ="<?php echo $survey->customer;?>"></td>
						<td><input class="form-control" name="surveyDeadline" placeholder="Dead line date" value ="<?php echo date("Y/m/d", strtotime($survey->deadline)); ?>"></td>
						<td><input class="btn btn-default" type="submit" name="surveySubmit" value="Set"></td>
					</form>
					
					<td>
						<a href="/manage/surveyQuestions?survey=<?php echo $survey->id; ?>">Questions</a>
					</td>
					<td>
						<?php if ($survey->active.''=='1'):?>
						<a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/surveys?option=disable&id=<?php echo $survey->id; ?>">Disable</a>
						<?php else:?>
						<a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/surveys?option=enable&id=<?php echo $survey->id; ?>">Enable</a>
						<?php endif;?>
					</td>
					<td>
						<a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/manage/surveys?option=delSurvey&id=<?php echo $survey->id; ?>"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
					<td>
						<a class="btn btn-default" href="/manage/surveyReport/<?php echo $survey->id; ?>">Report</a>
					</td>
					<td>
						<a class="btn btn-default" href="/manage/surveyWhoUnfinished/<?php echo $survey->id; ?>">Status</a>
					</td>
				</tr>
			<?php } ?>
			<tr>
					<form action="/manage/surveys?option=addSurvey" method="post">
					<td><span class="glyphicon glyphicon-asterisk"></span></td>
						<td><input class="form-control" name="surveyTitle" placeholder="Survey title"></td>
						<td><input class="form-control" name="surveyCustomer" placeholder="Customer email"></td>
						<td><input class="form-control" name="surveyDeadline" placeholder="Dead line date"></td>
						<td><input class="btn btn-default" type="submit" name="surveySubmit" value="+"></td>
					</form>
				</tr>
			</tbody>
		</table>
	</div>
</div>

