<div class="row">
	<div class="col-xs-12">
		<h3><small>Search user by email and add the credit:</h3> 
		<div class="panel panel-default">
			<div class="panel-body">
        		<form class="navbar-form navbar-left" role="search" action="/manage/userCredit" method="POST">
                  <div class="form-group">
                   Email:
                    <input type="text" class="form-control" placeholder="Email"  value="" name="email">
                  </div>
                  <div class="form-group">
                   Add credit: <input name="creditplus">
                  </div>
                  <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
        </div>
	</div>
</div>
<?php if ($person!==false): ?>
<div class="row">
	<div class="col-xs-12">
    	<h3><small>Please, confirm</h3>
    	<div class="panel panel-default">
        	<div class="panel-body">
        	Email: <b><?php echo $person->email; ?></b><br/>
        	Name: <b><?php echo $person->full_name; ?></b><br/>
        	Current credit: <b><?php echo $person->credit; ?></b>
        	New credit: <b><?php echo $newcredit ; ?></b>
        	<hr/>
        	<form action="/manage/userCredit" method="POST">
                  <div class="form-group">
                  	<input type="hidden" name ="email" value = "<?php echo $person->email;?>">
                  	<input type="hidden" name ="credit" value = "<?php echo $credit;?>">
                  	<button type="submit" class="btn btn-default" name="confirm">Confirm</button>
                  </div>
            </form>
        	</div>
    	</div>
	</div>
</div>
<?php endif;?>