<div class="row">
    <div class="col-xs-12">
        <form action="/developer/alerts" method="POST">
            <div class="input-group">
                <input required class="form-control" name="filter" value="<?=$query?>" placeholder="type text here...">
                <span class="input-group-btn">
					<button type="submit" class="btn btn-success">Search</button>
				</span>
            </div>
        </form>
        <br/>
    </div>

        <form action="/developer/alerts" method="POST">
            <input type="hidden" name="filter" id="filter" class="form-control" value="<?=$query?>">
            <table id="servicesTable" class="table">
                <thead>
                <tr>
                    <th width="50" class="text-center"><input type="checkbox" onclick="$('.chkFix').click();"></th>
                    <th>Date</th>
                    <th class="text-center">Text</th>
                </tr>
                </thead>
                <tbody>
                <?php if ($no_results): ?>
                    <div role="alert" class="alert alert-danger"><span>No alerts<?php if (!empty($query)): ?> for <b><?=$query?></b><?php endif; ?>.</span></div>
                <?php endif; ?>

                <?php foreach ($alerts as $alert) {
                    ?>
                    <tr>

                        <td class="text-center" valign="middle"><input type="checkbox" name="fixed[]" class="chkFix" value="<?=$alert->id?>"></td>
                        <td valign="middle"><?= date("m/d H:i", strtotime($alert->created)) ?></td>
                        <td class="text-left"><?=$alert->text?></td>
                    </tr>
                <?php } ?>
                <tr>
                    <td colspan="2"><input type="submit" class="btn btn-primary" value="Fix all checked" onclick="return confirm('Are you sure?');"></td>
                    <td></td>
                    
                </tr>
                </tbody>
            </table>
        </form>
	</div>
</div>
