<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($deployingMesssage)) { ?>
			<div class="alert alert-success"><?php echo $deployingMesssage; ?></div>
		<?php } ?>

		<?php if( ! empty($deployingError)) { ?>
			<div class="alert alert-danger"><?php echo $deployingError; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<form role="form" action="deploy" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<label for="service">Service file</label>
				<p class="help-block">Must be a .zip file less than 1 MB</p>
				<input id="service" type="file" name="service" required />
			</div>

			<div class="form-group">
				<br/>
				<button type="submit" class="btn btn-default">Add/Update service</button>
			</div>
		</form>
	</div>
</div>