<div class="row">
	<div class="col-xs-12">
		<br/>
		<?php if ($message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Teacher</th>
					<th>Category</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($courses as $course) { ?>
				<tr>
					<td><a href="/school/schoolChapters?course=<?= $course->id ?>"><?= $course->title ?></a></td>
					<td><?= $course->name . ', ' . $course->grade ?></td>
					<td><?= $course->category ?></td>
					<td class="text-right">
						<?php if ($course->active) { ?>
							<a class="btn btn-xs btn-default" href="/school?option=disable&id=<?= $course->id ?>"><span class="glyphicon glyphicon-pause"></span> Disable</a>
						<?php } else { ?>
							<a class="btn btn-xs btn-default" href="/school?option=enable&id=<?= $course->id ?>"><span class="glyphicon glyphicon-play"></span> Enable</a>
						<?php } ?>

						<a class="btn btn-xs btn-default" onclick="editCourse(<?= $course->id ?>);"><span class="glyphicon glyphicon-edit"></span></a>

						<a class="btn btn-xs btn-default" onclick ="return confirm('Are you sure?');" href="/school?option=del&id=<?= $course->id ?>"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>


<!-- New course modal form -->
<div class="modal fade tooltips" id="newCourseForm-modal" tabindex="-1" role="dialog" aria-labelledby="newCourseForm-label" aria-hidden="true">
	<div class="modal-dialog" style="width:500px;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
				<h4 class="modal-title" id="newCourseForm-label"><i class="fa fa-book fa-1x" aria-hidden="true"></i> <span id ="formCaption">New course</span></h4>
			</div>
			<div class="modal-body">
				<form role="form" action = "/school?option=add" method = "post" id="newCourseForm" enctype="multipart" data-toggle="validator">
					<div class="form-group">
						<label for="courseTitle">Title</label>
						<input required type="text" class="form-control text" name="courseTitle" id="courseTitle" placeholder="title of the course" title="Insert title of the course">
					</div>

					<div class="form-group">
						<label for="courseTeacher">Teacher</label>
						<select required class="form-control" name="courseTeacher" id ="courseTeacher">
							<?php foreach ($teachers as $teacher) { ?>
								<option value ="<?= $teacher->id ?>"><?= $teacher->name . ', ' . $teacher->title ?></option>
								<?php } ?>
						</select>
					</div>

					<div class="form-group">
						<label for="courseCategory">Category</label>
						<select required class="form-control" name="courseCategory" id ="courseCategory">
							<?php foreach (array('SOCIEDAD','NEGOCIOS','MEDICINA','INFORMATICA','INGENIERIA','LETRAS','ARTES','FILOSOFIA','SALUD','POLITICA','TECNICA','OTRO') as $category) { ?>
								<option value ="<?= $category ?>"><?= ucfirst(strtolower($category)) ?></option>
							<?php } ?>
						</select>
					</div>

					<div class="form-group">
						<label for="courseContent">Summary</label>
						<textarea class="form-control" name="courseContent" id="courseContent"></textarea>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="submit" name="btnInsert" class="btn btn-primary">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
	function newCourse()
	{
		$('#newCourseForm-modal').modal('show');
		$('#courseTitle').val('');
		$('#courseContent').val('');
		$('#newCourseForm').attr('action','/school?option=add');
		$('#courseCategory').val('');
		$('#formCaption').html('New course');
	}

	function editCourse(course_id)
	{
		$('#newCourseForm-modal').modal('show');
		$('#courseTitle').val($('#courseTitle-' + course_id).val());
		$('#courseContent').val($('#courseContent-' + course_id).val());
		$('#courseTeacher').val($('#courseTeacher-' + course_id).val());
		$('#courseCategory').val($('#courseCategory-' + course_id).val());
		$('#newCourseForm').attr('action','/school?option=set&id=' + course_id)
		$('#formCaption').html('Edit course');
	}
</script>
