<div class="row">
	<div class="col-xs-12">
		<?php if ($message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table id="servicesTable" class="table">
			<tbody>
				<?php foreach ($questions as $question): ?>
				<tr style="border-top:4px solid gray;">
				<form action="/school/schoolQuestions?option=setQuestion&chapter=<?= $chapter->id ?>&id=<?= $question->id ?>" method="post">
					<input type="hidden" name="chapter" value="<?= $chapter->id ?>">
					<input id="question-answer-<?= $question->id ?>" type="hidden" name="answer" value="<?= $question->answer ?>">
					<td>
						 <div class="input-group">
						<span class="input-group-addon" style="border: none;" >
						<i class="fa fa-question-circle fa-2x"></i>
						</span>
						<input class="form-control" name="chapterQuestionTitle" value="<?= $question->title ?>" style="border: none; font-size: 14px; font-weight: bold;">
						 </div>
					</td>
					<td width="32" class="text-center"><button class="btn btn-default" type="submit" name="chapterSubmit"><i class="fa fa-save"></i></button></td>
				</form>
				</td>
				<td width="32" class="text-center"><a class="btn btn-default" href="/school/schoolQuestions?option=delQuestion&id=<?= $question->id ?>&chapter=<?= $chapter->id ?>" onclick="return confirm('Are you sure?');"><span class="glyphicon glyphicon-trash"></a>
				</td>

				</tr>
				<?php foreach ($question->answers as $answer): ?>
					<tr>
					<form action="/school/schoolQuestions?option=setAnswer&chapter=<?= $chapter->id ?>&id=<?= $answer->id ?>" method="post">
						<td>
							<div class="input-group">
								&nbsp;&nbsp;<span class="input-group-addon" style="border: none;" >
									<input id = "answer-<?= $answer->id ?>"
										   class="question-<?= $question->id ?>"
										   type="radio"
										   aria-label="..."
										   <?php if ($answer->id == $question->answer) echo 'checked=""' ?>
										   onclick="setRightAnswer(<?= $question->id ?>,<?= $answer->id ?>);">
								</span>
								<input style="border: none;" class="form-control" name="chapterAnswerTitle" placeholder="New answer title" value="<?= $answer->title ?>">
								</td>
							</div>
						<td width="32" class="text-center">
							<button class="btn btn-default" type="submit" name="answerSubmit" value="Set"><i class="fa fa-save"></i></button>
						</td>
					</form>
					<td width="32" class="text-center"><a class="btn btn-default" href="/school/schoolQuestions?option=delAnswer&id=<?= $answer->id ?>&chapter=<?= $chapter->id ?>" onclick="return confirm('Are you sure?');"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
					</tr>
				<?php endforeach ?>
				<tr>
				<form action="/school/schoolQuestions?option=addAnswer&chapter=<?= $chapter->id ?>" method="post">
					<input type="hidden" name="question" value="<?= $question->id ?>">
					<td>
						<div class="input-group">
							 &nbsp;&nbsp;<span style="border: none;" class="input-group-addon"> <input type="radio" aria-label="..." disabled="true"></span>
							 <input style="border: none;"  class="form-control" name="chapterAnswerTitle" placeholder="New answer">
						</div>
					</td>
					<td class="text-center"><input class="btn btn-default" type="submit" name="chapterSubmit" value="+"></td>
				</form>
				</tr>
			<?php endforeach ?>
			<tr style="border-top:4px solid gray;">
			<form action="/school/schoolQuestions?option=addQuestion&chapter=<?= $chapter->id ?>" method="post">
				<input type="hidden" name="chapter" value="<?= $chapter->id ?>">
				<td><div class="input-group">
						<span class="input-group-addon" id="basic-addon3">New question:</span> <input class="form-control" name="chapterQuestionTitle"></td>
					</div>
				<td class="text-center"><input class="btn btn-default" type="submit" name="chapterSubmit" value="+"></td>
			</form>
			</tr>
			</tbody>
		</table>
	</div>
</div>

<script>
	function setRightAnswer(question, answer)
	{
		$("#answer-"+answer).removeClass('question-'+question);
		$(".question-"+question).attr('checked', false);
		$("#answer-"+answer).addClass('question-' + question);
		$("#question-answer-"+question).val(answer);
	}

	$(function(){
		<?php foreach ($questions as $question): ?>
		setRightAnswer(<?= $question->id ?>, <?= $question->answer ?>);
		<?php endforeach ?>
	});
</script>
