<div class="ibox float-e-margins">
    <br/>
    <a class="btn btn-default" href="/manage/schoolChapters?course=<?php echo $chapter->course; ?>">Chapters</a>
    <br/>
    <div class="ibox-title">
		<h5><?php echo $chapter->title; ?></h5>
	</div>
    <div class="ibox-content">
        <p>
        <?php echo $chapter->content; ?><br/>
        </p>
    </div>
    <br/>
    <a class="btn btn-default" href="/manage/schoolEditChapter/<?php echo $chapter->id; ?>">Edit</a>
</div>
