<div class="row">
	<div class="col-xs-12">
		<?php if ($message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Type</th>
					<th>Order</th>
					<th>Title</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($chapters as $chapter) { ?>
					<tr>
						<td width="10"><?= $chapter->xtype ?></td>

						<td width="10" class="text-center"><?= $chapter->xorder ?></td>

						<td><?= $chapter->title ?></td>

						<td width="50">
							<nobr>
							<?php if ($chapter->xtype == 'PRUEBA') { ?>
								<a class="btn btn-xs btn-default" href="/school/schoolQuestions?chapter=<?= $chapter->id ?>">Questions <span class="label label-info"><?= $chapter->questions ?></span></a>
							<?php } ?>
							<a class="btn btn-xs btn-default" href="/school/schoolEditChapter/<?= $chapter->id ?>"><span class="glyphicon glyphicon-pencil"></span></a>
							<a class="btn btn-xs btn-default" href="/school/schoolChapters?option=up&course=<?= $chapter->course ?>&id=<?= $chapter->id ?>"><span class="glyphicon glyphicon-arrow-up"></span></a>
							<a class="btn btn-xs btn-default" href="/school/schoolChapters?option=down&course=<?= $chapter->course ?>&id=<?= $chapter->id ?>"><span class="glyphicon glyphicon-arrow-down"></span></a>
							<a class="btn btn-xs btn-default" onclick ="return confirm('Are you sure?');" href="/school/schoolChapters?option=del&course=<?= $chapter->course ?>&id=<?= $chapter->id ?>"><span class="glyphicon glyphicon-trash"></span></a>
						</nobr>
						</td>
					</tr>
				<?php } ?>
		</table>
	</div>
</div>
