<div class="row">
	<div class="col-xs-12">
		<?php if ($message) { ?>
			<div class="alert alert-<?= $message_type ?>" role="alert"><?= $message ?></div>
		<?php } ?>

		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Title</th>
					<th>Email</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($teachers as $teacher) { ?>
				<form action="#" method="post">
					<input type="hidden" name="option" value="set">
					<input type="hidden" name="id" value="<?= $teacher->id ?>">
					<tr>
						<td><input class="form-control" name="techerName" placeholder="teacher name" value ="<?= $teacher->name ?>"></td>
						<td><input class="form-control" name="techerTitle" placeholder="teacher title" value ="<?= $teacher->title ?>"></td>
						<td><input class="form-control" name="techerEmail" placeholder="teacher email" value ="<?= $teacher->email ?>"></td>
						<td class="text-right">
							<button class="btn btn-default" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
							<a class="btn btn-default" onclick ="return confirm('Are you sure?');" href="/school/schoolTeachers?option=del&id=<?= $teacher->id ?>"><span class="glyphicon glyphicon-trash"></span></a>
						</td>
					</tr>
				</form>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- New course modal form -->
<div class="modal fade tooltips" id="newTeacherForm-modal" tabindex="-1" role="dialog" aria-labelledby="newCourseForm-label" aria-hidden="true">
	<div class="modal-dialog" style="width:500px;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
				<h4 class="modal-title" id="newTeacherForm-label">New teacher</h4>
			</div>
			<div class="modal-body">
				<form role="form" action = "/school/schoolTeachers?option=add" method = "post" id="newTeacherForm" enctype="multipart" data-toggle="validator">
					<div class="form-group">
						<label for="courseTitle">Full name:</label>
						<input required type="text" class="form-control text" name="teacherName" id="teacherName" placeholder="name of the teacher" title="Insert the name of the teacher">
					</div>

					<div class="form-group">
						<label for="courseTitle">Title:</label>
						<input required type="text" class="form-control text" name="teacherTitle" id="teacherTitle" placeholder="title of the teacher" title="Insert the title of the teacher">
					</div>

					<div class="form-group">
						<label for="courseTitle">Email:</label>
						<input required type="text" class="form-control text" name="teacherEmail" id="teacherEmail" placeholder="email of the teacher" title="Insert the email of the teacher">
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="submit" name="btnInsert" class="btn btn-primary">Insert</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
