<div class="row">
	<br/>
	<div class="col-xs-12">
		<?php if ($message !== false): ?>
			<div class="alert alert-<?php echo $message_type; ?>" role="alert"><?php echo $message; ?></div>
		<?php endif; ?>
		<div class="panel">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Teachers (<?php echo count($teachers); ?>)</h5>
					<div class="ibox-tools">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<i class="fa fa-wrench"></i>
						</a>
						<ul class="dropdown-menu dropdown-user">
							<li>
								<a href="#" onclick="$('#newTeacherForm-modal').modal('show');"><span class="glyphicon glyphicon-plus"></span> New teacher</a>
							</li>
							<a class="close-link">
								&nbsp;
							</a>
					</div>
				</div>
				<div class="ibox float-e-margins">
					<div class="ibox-content">
						<div class="" style="text-align:right">
							<button type="button" class="btn btn-primary" onclick="$('#newTeacherForm-modal').modal('show');">
								<span class="glyphicon glyphicon-plus"></span> New teacher
							</button>
						</div>
						<table id="marketTable" class="table table-striped table-bordered table-hover dataTables-example">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Title</th>
									<th>Email</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($teachers as $teacher): ?>

								<form action="/school/schoolTeachers?option=setTeacher&id=<?php echo $course->id; ?>" method="post">
									<tr>
										<td width="50"><?php echo $teacher->id; ?></td>
										<td><input class="form-control" name="techerName" placeholder="teacher name" value ="<?php echo $teacher->name; ?>"></td>
										<td><input class="form-control" name="techerTitle" placeholder="teacher title" value ="<?php echo $teacher->title; ?>"></td>
										<td><input class="form-control" name="techerEmail" placeholder="teacher email" value ="<?php echo $teacher->email; ?>"></td>
										<td width="90">
											<button class="btn btn-primary" type="submit" name="teacherSubmit"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
											<a class="btn btn-danger" onclick ="return confirm('Are you sure?');" href="/school/schoolTeachers?option=del&id=<?php echo $teacher->id; ?>"><span class="glyphicon glyphicon-trash"></span></a>
										</td>
									</tr>
								</form>


							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<!-- New course modal form -->
			<div class="modal fade tooltips" id="newTeacherForm-modal" tabindex="-1" role="dialog" aria-labelledby="newCourseForm-label" aria-hidden="true">
				<div class="modal-dialog" style="width:500px;">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
							<h4 class="modal-title" id="newTeacherForm-label">New teacher</h4>
						</div>
						<div class="modal-body">
							<form role="form" action = "/school/schoolTeachers?option=add" method = "post" id="newTeacherForm" enctype="multipart" data-toggle="validator">
								<div class="form-group">
									<label for="courseTitle">Full name:</label>
									<input required type="text" class="form-control text" name="teacherName" id="teacherName" placeholder="name of the teacher" title="Insert the name of the teacher">
								</div>

								<div class="form-group">
									<label for="courseTitle">Title:</label>
									<input required type="text" class="form-control text" name="teacherTitle" id="teacherTitle" placeholder="title of the teacher" title="Insert the title of the teacher">
								</div>

								<div class="form-group">
									<label for="courseTitle">Email:</label>
									<input required type="text" class="form-control text" name="teacherEmail" id="teacherEmail" placeholder="email of the teacher" title="Insert the email of the teacher">
								</div>

								<div class="modal-footer">
									<button type="submit" name="btnInsert" class="btn btn-success">Insert</button>
									<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function () {
		$('.dataTables-example').DataTable({
			dom: '<"html5buttons"B>lTfgitp',
			buttons: [
				{extend: 'copy'},
				{extend: 'csv'},
				{extend: 'excel', title: 'ApretasteSchoolChapters'},
				{extend: 'pdf', title: 'ApretasteSchoolChapters'},
				{extend: 'print',
					customize: function (win) {
						$(win.document.body).addClass('white-bg');
						$(win.document.body).css('font-size', '10px');
						$(win.document.body).find('table')
								.addClass('compact')
								.css('font-size', 'inherit');
					}
				}
			]
		});
	});
</script>
