<div class="row">
	<div class="col-xs-12">
		<?php if( ! empty($deployingError)) { ?>
			<br/>
			<div class="alert alert-danger"><?php echo $deployingError; ?></div>
		<?php } ?>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<h1>Deploy a service</h1>

		<form role="form" action="submit" method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<h2>Deploy key</h2>
				<input type="text" id="deploykey" name="deploykey" class="form-control" placeholder="i.e.: 4599c5a25e33fccb5b915ed99266d37e" />
				<p class="help-block">Insert deploy key when updating your service. Leave this field in blank for new deployments</p>
			</div>
	
			<div class="form-group">
				<h2>File input</h2>
				<input type="file" id="service" name="service" >
				<p class="help-block">Attach the service zip file (1 MB max)</p>
			</div>
		
			<button type="submit" class="btn btn-default">Add/Update service</button>
		</form>
	</div>
</div>