<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Analytics</title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Home-Made Analytics system and management tools for Apretaste">
		<meta name="author" content="Salvi Pascual">
		<meta name="author" content="hCarras">

		<link rel="icon" href="https://apretaste.com/static/images/apretaste.icon.png">

		<!-- Bootstrap Core CSS -->
		<link href="https://apretaste.com/static/css/bootstrap.min.css" rel="stylesheet">
		<script src="https://apretaste.com/static/js/bootstrap.min.js"></script>

		<!-- Custom stylesheets -->
		<link href="../css/basics.css" rel="stylesheet">

		<!-- jQuery -->
		<script src="https://apretaste.com/static/js/jquery.js"></script>
	</head>

	<body>
		<div class="container">
			<?php echo $this->getContent(); ?>
		</div>
	</body>
</html>