<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Inicia tu sesion</title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Inicia tu sesion en Apretaste">
		<meta name="author" content="Salvi Pascual">

		<link rel="icon" href="images/apretaste.icon.png">
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<script src="/js/jquery.js"></script>
		<script src="/js/jquery-ui.min.js"></script>
		<link href="/css/jquery-ui.min.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row" style="margin-top:100px;">
				<div class="col-xs-12 text-center">
					<img src="<?=$icon?>" alt="logo">
					<br/><br/><br/>

					<form id="shake" action="/login/<?=$phase?>Submit" method="get">
						<input type="hidden" name="email" value="<?=$email?>">
						<input type="hidden" name="redirect" value="<?=$redirect?>">

						<?php if($phase == "email") { ?>
							<label for="email">ESCRIBA SU EMAIL</label><br/>
							<input id="email" type="email" name="email" value="<?=$email?>" class="form-control input-lg" placeholder="email@apretaste.com" required/>
							<br/><br/>
							<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-menu-right"></span></button>
						<?php } ?>

						<?php if($phase == "code") { ?>
							<label for="pin">ESCRIBA EL CODIGO</label><br/>
							<input id="pin" type="text" name="pin" class="form-control input-lg text-center" style="letter-spacing:16px;" maxlength="4" placeholder="****" required/>
							<br/>
							<small>Le mandamos el c&oacute;digo a <?=$email?></small>
							<br/><br/>
							<a class="btn btn-default" href="/login?email=<?=$email?>&redirect=<?=$redirect?>"><span class="glyphicon glyphicon-menu-left"></span></a>
							<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-menu-right"></span></button>
						<?php } ?>
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

<style>
	body:after { /*hack for the bgimage to work on mobile*/
		content:"";
		position:fixed;
		top:0;
		height:100vh;
		left:0;
		right:0;
		z-index:-1;
		background: #E3E7D0 url('/images/background3.jpg') no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}

	.form-control {
		max-width: 350px;
		display: inline-block;
	}
</style>

<script>
	$(document).ready(function(){
		$('.form-control').focus();

		<?php if($shake == "true") { ?>
			$('#shake').effect('shake');
		<?php } ?>
	});
</script>
