<?php 
	$wwwhttp = $this->di->get('path')['http'];
	$environment = $this->di->get('environment');
	$home = isset($home) ? $home : "/manage";
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?= isset($title) ? $title : "Manage"; ?></title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Home-Made Analytics system and management tools for Apretaste">
		<meta name="author" content="Salvi Pascual">
		<meta name="author" content="hCarras">
		<link rel="icon" href="<?= $wwwhttp; ?>/images/apretaste.icon.png">

		<!-- jQuery -->
		<script src="<?= $wwwhttp; ?>/js/jquery.js"></script>
		<link href="<?= $wwwhttp; ?>/css/jquery-ui.min.css" rel="stylesheet">
		
		<!-- Bootstrap Core CSS -->
		<link href="<?= $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap.min.js"></script>

		<!-- Bootstrap plugins -->
		<script src="<?= $wwwhttp; ?>/js/validator.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/fileinput.min.js"></script>
		<link href="<?= $wwwhttp; ?>/css/fileinput.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap-notify.min.js"></script>
		
		<link href="<?= $wwwhttp; ?>/css/animate.css" rel="stylesheet">
    	    
		<!-- Font awesome -->
		<link rel="stylesheet" href="<?= $wwwhttp; ?>/font-awesome/css/font-awesome.min.css">

		<!-- Custom stylesheets -->
		<link href="<?= $wwwhttp; ?>/css/basics.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/manage.css" rel="stylesheet">
		
		<!-- Toastr style -->
	    <link href="/css/toastr.min.css" rel="stylesheet">
	
	</head>

	<body class="gray-bg">
		
		<div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>
				<img src = "/images/apretaste.logo.big.transp.png" width="300">
            </div>
            <h3>Management tool</h3>
            <form class="m-t" role="form" method="post" action="/manage">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Username" required="" name="email">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="" name="password">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
            </form>
        </div>
    </div>
		<!-- Mainly scripts -->
    <script src="/js/jquery.metisMenu.js"></script>
    <script src="/js/jquery.slimscroll.min.js"></script>

    <!-- Peity -->
    <script src="/js/jquery.peity.min.js"></script>
    <!--  <script src="js/demo/peity-demo.js"></script>  -->

    <!-- Custom and plugin javascript -->
    <script src="/js/manage.js"></script>
    <script src="/js/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="/js/jquery-ui.min.js"></script>

    <!-- GITTER -->
    <script src="/js/jquery.gritter.min.js"></script>

    	
	</body>
	
	<!-- Mainly scripts -->
    <script src="/js/jquery.metisMenu.js"></script>
    <script src="/js/jquery.slimscroll.min.js"></script>

    <!-- Peity -->
    <script src="/js/jquery.peity.min.js"></script>
    <!--  <script src="js/demo/peity-demo.js"></script>  -->

    <!-- Custom and plugin javascript -->
    <script src="/js/manage.js"></script>
    <script src="/js/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="/js/jquery-ui.min.js"></script>

    <!-- GITTER -->
    <script src="/js/jquery.gritter.min.js"></script>

    <!-- Sparkline -->
     <script src="/js/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <!-- <script src="js/demo/sparkline-demo.js"></script>  -->

    <!-- ChartJS-->
    <!-- <script src="js/plugins/chartJs/Chart.min.js"></script>  -->

    <!-- Toastr -->
    <script src="/js/toastr.min.js"></script>
   
	<script>
	<?php if ($loginFail): ?>
	 $(document).ready(function() {

        	 toastr.options = {
        			  "closeButton": true,
        			  "debug": false,
        			  "progressBar": true,
        			  "preventDuplicates": false,
        			  "positionClass": "toast-top-right",
        			  "onclick": null,
        			  "showDuration": "400",
        			  "hideDuration": "1000",
        			  "timeOut": "7000",
        			  "extendedTimeOut": "1000",
        			  "showEasing": "swing",
        			  "hideEasing": "linear",
        			  "showMethod": "fadeIn",
        			  "hideMethod": "fadeOut"
        	}
             
            toastr.error('Wrong user and password', 'Access denied');

	 });
	 <?php endif;?>
	</script>
</html>