<?php 
	$wwwhttp = $this->di->get('path')['http'];
	$environment = $this->di->get('environment');
	$home = isset($home) ? $home : "/manage";
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?= isset($title) ? $title : "Manage"; ?></title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Home-Made Analytics system and management tools for Apretaste">
		<meta name="author" content="Salvi Pascual">
		<meta name="author" content="hCarras">
		<link rel="icon" href="<?= $wwwhttp; ?>/images/apretaste.icon.png">

		<!-- jQuery -->
		<script src="<?= $wwwhttp; ?>/js/jquery.js"></script>

		<!-- Bootstrap Core CSS -->
		<link href="<?= $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap.min.js"></script>

		<!-- Bootstrap plugins -->
		<script src="<?= $wwwhttp; ?>/js/validator.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/fileinput.min.js"></script>
		<link href="<?= $wwwhttp; ?>/css/fileinput.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap-notify.min.js"></script>
		
		<link href="<?= $wwwhttp; ?>/css/animate.css" rel="stylesheet">
       
		<!-- Font awesome -->
		<link rel="stylesheet" href="<?= $wwwhttp; ?>/font-awesome/css/font-awesome.min.css">

		<!-- Custom stylesheets -->
		<link href="<?= $wwwhttp; ?>/css/basics.css" rel="stylesheet">
	</head>

	<body>
		<?php if($environment=="sandbox") { ?>
			<div style="color:white; background-color:red; font-weight:bold; display:inline-block; padding:5px; position:absolute; bottom:10px; right:10px; z-index:99; opacity: 0.5;">SANDBOX</div>
		<?php } ?>

		<nav class="navbar navbar-inverse" style="border-radius:0px; -webkit-border-radius:0px; -moz-border-radius:0px;">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand"style="text-transform: uppercase;"><?php if(isset($title)) echo $title; ?></span>
				</div>
				<div class="navbar-right hidden-xs">
					<a href="<?= $home ?>" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a>
					<?php if (isset($menu)): ?>
						<?php foreach($menu as $item):?>
							<a href="<?php echo $item['href'];?>" class="btn btn-default navbar-btn">
								<?php if (isset($item['icon'])): ?><span class="glyphicon glyphicon-<?php echo $item['icon']; ?>"></span>
								<?php endif;?><?php echo $item['caption'];?>
							</a>
						<?php endforeach;?>
				<?php endif;?>
				</div>
			</div>
		</nav>

		<div class="container">
			<?= $this->getContent(); ?>
		</div>
	</body>
</html>