<?php
	$wwwhttp = $this->di->get('path')['http'];
	$security = new Security();
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?= isset($title) ? strip_tags($title) : "Manage"; ?></title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Conectando miles de cubanos a la Web por vias efectivas, accesibles y legales">
		<meta name="author" content="Salvi Pascual">
		<link rel="icon" href="<?= $wwwhttp; ?>/images/apretaste.icon.png">

		<!-- jQuery -->
		<script src="<?= $wwwhttp; ?>/js/jquery-2.1.1.js"></script>
		<link href="<?= $wwwhttp; ?>/css/jquery-ui.min.css" rel="stylesheet">

		<!-- Bootstrap Core CSS -->
		<link href="<?= $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">
		<script src="<?= $wwwhttp; ?>/js/bootstrap.min.js"></script>

		<!-- Bootstrap plugins -->
		<link href="<?= $wwwhttp; ?>/css/fileinput.min.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/animate.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/font-awesome/css/font-awesome.min.css" rel="stylesheet" >
		<link href="<?= $wwwhttp; ?>/css/basics.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/manage.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/toastr.min.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/jquery.gritter.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/datatables.min.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/jasny-bootstrap.min.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/css/iCheck/custom.css" rel="stylesheet">
		<link href="<?= $wwwhttp; ?>/js/summernote/summernote.css" rel="stylesheet">
	</head>

	<body>
		<div id="wrapper">
			<nav class="navbar-default navbar-static-side" role="navigation">
				<div class="sidebar-collapse">
					<ul class="nav metismenu" id="side-menu">
						<!-- APRETASTE LOGO -->
						<li class="nav-header">
							<div class="dropdown profile-element">
								<img alt="image" src="/images/apretaste.logo.big.transp.png" width="100"/>
							</div>
						</li>

						<!-- DASHBOARD -->
						<?php if($security->checkAccess("manage")) { ?>
						<li>
							<a href="/manage"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
						</li>
						<?php } ?>

						<!-- AUDIENCE -->
						<?php if($security->checkAccess("manage")) { ?>
						<li>
							<a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Analytics</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/manage/audience">Audience</a></li>
								<li><a href="/manage/profile">Profile</a></li>
								<li><a href="/manage/profilesearch">Profile search</a></li>
								<li><a href="/manage/remarketing">Remarketing</a></li>
								<li><a href="/manage/raffles">Raffles</a></li>
								<li><a href="/manage/services">List of services</a></li>
								<li><a href="/manage/ads">List of ads</a></li>
								<li><a href="/manage/dropped">Dropped emails</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- ADMIN -->
						<?php if($security->checkAccess("admin")) { ?>
						<li>
							<a href="#"><i class="fa fa-wrench"></i> <span class="nav-label">Admin</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/manage/createad">Create ad</a></li>
								<li><a href="/manage/createraffle">Create raffle</a></li>
								<li><a href="/manage/addcredit">Add credit</a></li>
								<li><a href="/admin/synonyms">Synonyms</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- NODES -->
						<?php if($security->checkAccess("nodes")) { ?>
						<li>
							<a href="#"><i class="fa fa-heartbeat"></i> <span class="nav-label">Emails</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/nodes">Output emails</a></li>
								<li><a href="/nodes/input">Input emails</a></li>
								<li><a href="/nodes/queque">Waiting queque</a></li>
								<li><a href="/nodes/delivery">Delivery</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- SURVEY -->
						<?php if($security->checkAccess("manage")) { ?>
						<li>
							<a href="/manage/surveys"><i class="fa fa-pie-chart"></i> <span class="nav-label">Surveys</span></a>
						</li>
						<?php } ?>

						<!-- MARKET -->
						<?php if($security->checkAccess("manage")) { ?>
						<li>
							<a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Market</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/manage/market">Products</a></li>
								<li><a href="/manage/marketOrders">Orders</a></li>
								<li><a href="/manage/marketStats">Stats</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- SCHOOL -->
						<?php if($security->checkAccess("school")) { ?>
						<li>
							<a href="#"><i class="fa fa-book"></i> <span class="nav-label">School</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/school">Courses</a></li>
								<li><a href="/schoolTeachers">Teachers</a></li>
							</ul>
						</li>
						<?php } ?>

                        <!-- CONTESTS -->
                        <?php if($security->checkAccess("contests")): ?>
                            <li>
                                <a href="#"><i class="fa fa-book"></i> <span class="nav-label">Contest</span> <span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li><a href="/contests">All contests</a></li>
                                </ul>
                            </li>
                        <?php endif; ?>

						<!-- CAMPAIGNS -->
						<?php if($security->checkAccess("campaigns")) { ?>
						<li>
							<a href="#"><i class="fa fa-envelope-o"></i> <span class="nav-label">Campaigns</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/campaigns">All Campaigns</a></li>
								<li><a href="/campaigns/lists">Lists</a></li>
								<li><a href="/campaigns/reports">Reports</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- SUPPORT -->
						<?php if($security->checkAccess("support")) { ?>
						<li>
							<a href="#"><i class="fa fa-support"></i> <span class="nav-label">Support</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/support">Open tickets</a></li>
								<li><a href="/support/cans">Can responses</a></li>
								<li><a href="/support/reports">Reports</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- DEVELOPER -->
						<?php if($security->checkAccess("manage")) { ?>
						<li>
							<a href="#"><i class="fa fa-laptop"></i> <span class="nav-label">Developers</span> <span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
								<li><a href="/manage/deploy">Deploy</a></li>
								<li><a href="/manage/errors">Errors log</a></li>
								<li><a href="/manage/sandbox">Test a service</a></li>
								<li><a target="_blank" href="/data">phpMyAdmin</a></li>
								<li><a target="_blank" href="https://admin.google.com/pragres.com">Google Admin Console</a></li>
								<li><a target="_blank" href="https://lightsail.aws.amazon.com">Amazon Lightsail</a></li>
								<li><a target="_blank" href="https://console.firebase.google.com/">Google Firebase</a></li>
								<li><a target="_blank" href="https://app.mailerlite.com/">Mailer Lite</a></li>
								<li><a target="_blank" href="https://www.email-validator.net/dashboard/index.html">Email Validator</a></li>
								<li><a target="_blank" href="https://pushcrew.com/admin/dashboard.php">Push Crew</a></li>
							</ul>
						</li>
						<?php } ?>

						<!-- LOGOUT -->
						<li><a href="/login/logout">Logout</a></li>
					</ul>
				</div>
			</nav>

			<div id="page-wrapper" class="gray-bg dashbard-1">
				<?php if(isset($title)): ?>
					<div class="row wrapper border-bottom white-bg page-heading">
						<h2><?php  echo $title; ?></h2>

						<ol class="breadcrumb">
							<li><a href="/manage">Home</a></li>
							<?php if (isset($breadcrumb)): ?>
								<?php foreach ($breadcrumb as $path => $caption): ?>
								<?php $active = false;?>
								<?php if (substr($caption, 0, 1 )== '*') {$caption = substr($caption,1); $active = true;}?>
								<li <?php if ($active) echo 'class="active"';?>>
										<a href="<?php if ($path[0] != "/") echo "/manage/"; ?><?php echo $path; ?>"><?php echo $caption; ?></a>
								</li>
								<?php endforeach;?>
							<?php endif;?>
						</ol>
					</div>
				<?php endif;?>
				<?php echo $this->getContent(); ?>
			</div>
		</div>

		<script src="<?= $wwwhttp; ?>/js/jquery.metisMenu.js"></script>
		<script src="<?= $wwwhttp; ?>/js/jquery.slimscroll.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/jquery.peity.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/manage.js"></script>
		<script src="<?= $wwwhttp; ?>/js/pace.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/jquery.gritter.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/jquery.sparkline.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/toastr.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/datatables.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/jasny-bootstrap.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/validator.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/fileinput.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/bootstrap-notify.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/icheck.min.js"></script>
		<script src="<?= $wwwhttp; ?>/js/summernote/summernote.js"></script>
	</body>
</html>
