<?php 
	$environment = $this->di->get('environment');
	$home = isset($home) ? $home : "/manage";
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?= isset($title) ? $title : "Manage"; ?></title>
		<link rel="icon" href="/images/apretaste_icon_16x16.png" sizes="16x16" type="image/png"/>
		<link rel="icon" href="/images/apretaste_icon_32x32.png" sizes="32x32" type="image/png"/>
		<link rel="icon" href="/images/apretaste_icon_64x64.png" sizes="64x64" type="image/png"/>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Home-Made Analytics system and management tools for Apretaste">
		<meta name="author" content="Salvi Pascual">
		<meta name="author" content="hCarras">

		<!-- jQuery -->
		<script src="/js/jquery.js"></script>

		<!-- Bootstrap Core CSS -->
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<script src="/js/bootstrap.min.js"></script>

		<!-- Bootstrap plugins -->
		<script src="/js/validator.min.js"></script>

		<!-- Font awesome -->
		<link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">

		<!-- Custom stylesheets -->
		<link href="/css/basics.css" rel="stylesheet">
	</head>

	<body>
		<?php if($environment=="sandbox") { ?>
			<div style="color:white; background-color:red; font-weight:bold; display:inline-block; padding:5px; position:absolute; top:10px; right:10px; z-index:99">SANDBOX</div>
		<?php } ?>

		<nav class="navbar navbar-inverse" style="border-radius:0px; -webkit-border-radius:0px; -moz-border-radius:0px;">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand"style="text-transform: uppercase;"><?php if(isset($title)) echo $title; ?></span>
				</div>
				<div class="navbar-right hidden-xs">
					<a href="<?= $home ?>" class="btn btn-default navbar-btn">Home</a>
				</div>
			</div>
		</nav>

		<div class="container">
			<?= $this->getContent(); ?>
		</div>
	</body>
</html>