<!-- modal window for request sent -->
<div id="modalRequestSent" class="modal">
	<div class="body">
		<div class="loader"></div>
	</div>
</div>

<!-- modal window asking for extra data -->
<div id="modalRequestMoreData" class="modal">
	<div class="body">
		<div id="modalRequestMoreDataBody" class="modal-body"></div>
		<button type="button" onclick="modalClose('modalRequestMoreData');">Cerrar</button>
		<button type="button" class="green" onclick="apretaste.sendMoreData();">Enviar</button>
	</div>
</div>

<!-- modal window to attach a file -->
<div id="modalUploadFile" class="modal">
	<div class="body">
		<div style="text-align:left; margin-bottom:20px;">
			<small><label for="attachment"></label></small>
			<input id="attachment" type="file" name="attachment"/>
		</div>
		<button type="button" onclick="modalClose('modalUploadFile');">Cerrar</button>
		<button type="button" class="green" onclick="apretaste.uploadFile();">Enviar</button>
	</div>
</div>

<style type="text/css">
	body {
		padding: 10px 0px;
		background: #E3E7D0 url('/images/background3.jpg') no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}

	.dropdown {
		background-color: #E6E6E6;
		border:1px solid #CCCCCC;
		color: #000000;
		border-radius: 3px;
		height: 22px;
		font-size: 12px;
		line-height:20px;
		text-align: center;
		text-decoration:none;
		min-width: 82px;
	}

	.modal {
		visibility: hidden;
		position: fixed;
		left: 0px;
		top: 0px;
		width:100%;
		height:100%;
		text-align:center;
		z-index: 1000;
		background: rgba(0, 0, 0, 0.8);

		display: -webkit-flex;
		display: -ms-flexbox;
		display: flex;
		-webkit-justify-content: center;
		-ms-flex-pack: center;
		justify-content: center;
		-webkit-align-items: center;
		-ms-flex-align: center;
		align-items: center;
	}

	.modal .body {
		width:300px;
		margin: auto;
		background-color: #fff;
		border:1px solid #000;
		padding:20px;
		text-align:center;
		border-radius: 5px;
	}

	button {
		border: none;
		cursor: pointer;
	}

	button.green {
		color: white;
		background-color: #5EBB47;
	}

	.loader {
		border: 16px solid #f3f3f3;
		border-top: 16px solid #5EBB47;
		border-radius: 50%;
		margin: auto;
		width: 50px;
		height: 50px;
		animation: spin 2s linear infinite;
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
</style>

<script src="/js/jquery-2.1.1.js"></script>
<script type="text/javascript">
	var apretaste = {
		url: "",
		wait: false,

		doaction: function (href, popup, desc, wait) {
			apretaste.url = "/run/display?subject=" + href;
			apretaste.wait = Boolean(wait);

			if(popup == "upload") {
				$('#modalUploadFile label').html(desc);
				modalOpen('modalUploadFile');
			}
			else if(Boolean(popup)) {
				$('#modalRequestMoreDataBody').empty();
				$.each(desc.split("|"), function(i, val) {
					var isTextArea = val.indexOf('textarea:') > -1;
					var isDropDown = val.indexOf('[');
					var html = '<div style="text-align:left; margin-bottom:15px;"><small>';

					if(isDropDown > -1)
					{
						var label = val.substring(0, val.lastIndexOf('['));
						var elements = val.substring(isDropDown+1, val.lastIndexOf(']')).split(',');
						html += '<label for="field'+i+'">'+label+'</label></small><br/>';
						html += '<select id="field'+i+'" class="input" style="width:100%;">';
						for (var i = 0; i < elements.length; i++) {
							var element = elements[i].trim();
							html += '<option value="'+element+'">'+element+'</option>';
						}
						html += '</selects>';
					}
					else if(isTextArea)
					{
						var label = val.substring(9);
						html += '<label for="field'+i+'">'+label+'</label></small><br/>';
						html += '<textarea id="field'+i+'" style="width:100%;" rows="4" class="input"></textarea>';
					}
					else
					{
						html += '<label for="field'+i+'">'+val+'</label></small><br/>';
						html += '<input id="field'+i+'" onkeyup="apretaste.onEnter(event);" style="width:100%;" type="text" class="input"/>';
					}

					$('#modalRequestMoreDataBody').append(html+'</div>');
				});
				modalOpen('modalRequestMoreData');
				$('#field0').focus();
			}
			else apretaste.send();
		},

		sendMoreData: function() {
			var params = "";
			var redirect = true;
			$('#modalRequestMoreDataBody .input').each(function(){
				$(this).css("border", "1px solid #A9A9A9");
				var value = this.value.trim();
				if(value == "") {
					$(this).css("border", "1px solid red");
					redirect = false;
				}
				params += encodeURIComponent(value) + " ";
			});

			if(redirect) {
				apretaste.url += " " + params;
				modalClose('modalRequestMoreData');
				apretaste.send();
			}
		},

		uploadFile: function() {
			var file = $("#attachment").prop("files")[0];
			var form = new FormData();
			form.append("file", file);

			$.ajax({
				url: "/api/upload",
				dataType: 'json',
				cache: false,
				contentType: false,
				processData: false,
				data: form,
				type: 'post',
				success: function(data) {
					if(data.code == "ok") {
						apretaste.url += " " + data.message;
						modalClose('modalUploadFile');
						apretaste.send();
					}
				}
			});
		},

		send: function() {
			if(apretaste.wait) {
				window.location = apretaste.url;
			}else{
				$.get(apretaste.url, function(data) {
					modalOpen('modalRequestSent');
					location.reload();
				});
			}
		},

		onSelect: function(href) {
			apretaste.wait = false;
			apretaste.url = "/run/display?subject=" + href;
			apretaste.send();
		},

		onEnter: function(e) {
			if(e.keyCode === 13) {
				e.preventDefault();
				apretaste.sendMoreData();
			}
			if (e.keyCode == 27) {
				modalClose('modalRequestMoreData');
			}
		}
	};

	function modalOpen(id) {
		$('#'+id).css('visibility', 'visible');
	}

	function modalClose(id) {
		$('#'+id).css('visibility', 'hidden');
	}
</script>

<!-- web push notifications -->
<script type="text/javascript">
	(function(p,u,s,h){
		p._pcq=p._pcq||[];
		p._pcq.push(['_currentTime',Date.now()]);
		s=u.createElement('script');
		s.type='text/javascript';
		s.async=true;
		s.src='https://cdn.pushcrew.com/js/d011951882e811830fa7e51f1fec62d7.js';
		h=u.getElementsByTagName('script')[0];
		h.parentNode.insertBefore(s,h);
	})(window,document);

	_pcq.push(['APIReady', function (){
		$.ajax({url: "/api/saveAppId?email={$USER_EMAIL}&appid="+pushcrew.subscriberId});
	}]);
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-49715278-1"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'UA-49715278-1', {
		'custom_map': {'dimension1': 'service'}
	});
	gtag('event', 'push_service', {'service': '{$APRETASTE_SERVICE_NAME}'});
</script>
