<!-- modal window for request sent -->
<div id="modalRequestSent" class="modal">
	<div class="body">
		<div class="loader"></div>
	</div>
</div>

<!-- modal window asking for extra data -->
<div id="modalRequestMoreData" class="modal">
	<div class="body">
		<div id="modalRequestMoreDataBody" class="modal-body"></div>
		<button type="button" onclick="modalClose('modalRequestMoreData');">Cerrar</button>
		<button type="button" class="green" onclick="apretaste.sendMoreData();">Enviar</button>
	</div>
</div>

<link rel="stylesheet" type="text/css" href="../css/materialize.min.css"/>
<link rel="stylesheet" type="text/css" href="../css/materializeicons.css"/>

<script src="/js/jquery-3.3.1.js"></script>
<script src="/js/materialize-1.0.0.js"></script>
<script src="/js/ejs.js"></script>
<script type="text/javascript">
	var apretaste = {
		url: "",
		wait: false,
		callback: false,

		doaction: function (href, popup, desc, wait, callback) {
			apretaste.url = "/run/display?subject=" + href;
			apretaste.wait = Boolean(wait);
			apretaste.callback = callback;

			if(Boolean(popup)) {
				$('#modalRequestMoreDataBody').empty();

				$.each(desc.split("|"), function(i, val) {
					var type = "t";
					var label = val;

					var p = val.split(":");
					if(p.length == 2) {
						type = p[0];
						label = p[1];
					}

					var required = label.endsWith("*") ? 'required' : '';
					var html = '<div style="text-align:left; margin-bottom:15px;">';

					if($.inArray(type, ['t','d','n','e','p','u','c']) >= 0) {
						if(type=='t') type = 'text';
						if(type=='d') type = 'date';
						if(type=='n') type = 'number';
						if(type=='e') type = 'email';
						if(type=='p') type = 'password';
						if(type=='u') type = 'file';
						if(type=='c') type = 'checkbox';
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<input id="field'+i+'" onkeyup="apretaste.onEnter(event);" type="'+type+'" class="input" '+required+'/>';
					}

					if(type=="m") {
						label = label.substring(0, label.lastIndexOf('['));
						var options = val.substring(val.indexOf('[')+1, val.lastIndexOf(']')).split(',');
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<select id="field'+i+'" class="input" '+required+'><option value=""></option>';
						for (var i = 0; i < options.length; i++) {
							var option = options[i].trim();
							html += '<option value="'+option+'">'+option+'</option>';
						}
						html += '</selects>';
					}

					if(type=="a") {
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<textarea id="field'+i+'" onkeyup="apretaste.onControlPlusEnter(event);" rows="4" class="input" '+required+'></textarea>';
					}

					$('#modalRequestMoreDataBody').append(html+'</div>');
				});
				modalOpen('modalRequestMoreData');
				$('#field0').focus();
			}
			else apretaste.send();
		},

		sendMoreData: function() {
			var params = "";
			var paramsArr = [];
			var toSend = true;

			$('#modalRequestMoreDataBody .input').each(function(){
				$(this).css("border", "1px solid #A9A9A9");

				var type = $(this).attr('type');
				var required = $(this).attr('required');
				var value = $(this).val().trim();

				var invalid = false;
				if(type=='email') invalid = !isEmail(value);
				if(type=='checkbox') invalid = !this.checked;

				if(invalid || (required && value == "")) {
					$(this).css("border", "1px solid red");
					toSend = false;
					return false;
				}

				if(type=='file') {
					var id = $(this).attr('id');
					apretaste.uploadFile(id);
					modalClose('modalRequestMoreData');
					toSend = false;
				}

				if(type=='checkbox') value="";

				params += encodeURIComponent(value) + "|";
				paramsArr.push(value);
			});

			if(toSend) {
				apretaste.url += " " + params.replace(/\|$/, "");
				modalClose('modalRequestMoreData');
				apretaste.send(paramsArr);
			}
		},

		uploadFile: function(id) {
			modalOpen('modalRequestSent');

			apretaste.wait = false;
			var file = $('#'+id).prop("files")[0];
			var form = new FormData();
			form.append("file", file);

			$.ajax({
				url:'/api/upload',
				dataType:'json',
				cache:false,
				contentType:false,
				processData:false,
				data: form,
				type: 'post',
				success: function(data) {
					if(data.code != 'ok') return false;
					apretaste.url += " " + data.message;
					apretaste.send([data.message]);
				},
				error: function(jqXHR, str) {
					console.log(str);
				}
			});
		},

		send: function(values=[]) {
			modalOpen('modalRequestSent');

			if(apretaste.wait) {
				window.location = apretaste.url;
			}else{
				$.get(apretaste.url, function(data) {
					if(apretaste.callback) {
						var arr = apretaste.callback.split(':');
						var funct = arr[0];
						arr.shift();
						window[funct](values.concat(arr));
					}
				});
			}

			modalClose('modalRequestSent');
		},

		onSelect: function(href) {
			apretaste.wait = false;
			apretaste.url = "/run/display?subject=" + href;
			apretaste.send([href]);
		},

		onControlPlusEnter: function(e) {
			if(e.ctrlKey && e.keyCode === 13) {
				apretaste.onEnter(e);
			}
		},

		onEnter: function(e) {
			if(e.keyCode === 13) {
				e.preventDefault();
				apretaste.sendMoreData();
			}
			if (e.keyCode == 27) {
				modalClose('modalRequestMoreData');
			}
		}
	};

	function modalOpen(id) {
		$('#'+id).css('visibility', 'visible');
	}

	function modalClose(id) {
		$('#'+id).css('visibility', 'hidden');
	}

	function isEmail(email) {
		const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
		return re.test(email);
	};
</script>

<!-- web push notifications -->
<script type="text/javascript">
	(function(p,u,s,h){
		p._pcq=p._pcq||[];
		p._pcq.push(['_currentTime',Date.now()]);
		s=u.createElement('script');
		s.type='text/javascript';
		s.async=true;
		s.src='https://cdn.pushcrew.com/js/d011951882e811830fa7e51f1fec62d7.js';
		h=u.getElementsByTagName('script')[0];
		h.parentNode.insertBefore(s,h);
	})(window,document);

	_pcq.push(['APIReady', function (){
		$.ajax({url: "/api/saveAppId?email={$USER_EMAIL}&appid="+pushcrew.subscriberId});
	}]);
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-49715278-1"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'UA-49715278-1', {
		'custom_map': {'dimension1': 'service'}
	});
	gtag('event', 'push_service', {'service': '{$APRETASTE_SERVICE_NAME}'});
</script>

<!--EJS Template Render-->
<script id="ejs">
	let template = `{$RAW_TEMPLATE}`;
	let data = {$JSON_DATA};
	$('#tpl-output').html(ejs.render(template,data));
</script>
<script>$('#ejs').remove();</script>