<!-- modal window for request sent -->
<div id="modalRequestSent" class="modal">
	<div class="body">
		<div class="loader"></div>
	</div>
</div>

<!-- modal window asking for extra data -->
<div id="modalRequestMoreData" class="modal">
	<div class="body">
		<div id="modalRequestMoreDataBody" class="modal-body"></div>
		<button type="button" onclick="modalClose('modalRequestMoreData');">Cerrar</button>
		<button type="button" class="green" onclick="apretaste.sendMoreData();">Enviar</button>
	</div>
</div>

<style type="text/css">
	body {
		padding: 10px 0px;
		background: #E3E7D0 url('/images/background3.jpg') no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}

	.dropdown {
		background-color: #E6E6E6;
		border:1px solid #CCCCCC;
		color: #000000;
		border-radius: 3px;
		height: 22px;
		font-size: 12px;
		line-height:20px;
		text-align: center;
		text-decoration:none;
		min-width: 82px;
	}

	.modal {
		visibility: hidden;
		position: fixed;
		left: 0px;
		top: 0px;
		width:100%;
		height:100%;
		text-align:center;
		z-index: 1000;
		background: rgba(0, 0, 0, 0.8);

		display: -webkit-flex;
		display: -ms-flexbox;
		display: flex;
		-webkit-justify-content: center;
		-ms-flex-pack: center;
		justify-content: center;
		-webkit-align-items: center;
		-ms-flex-align: center;
		align-items: center;
	}

	.modal .body {
		width:300px;
		margin: auto;
		background-color: #fff;
		border:1px solid #000;
		padding:20px;
		text-align:center;
		border-radius: 5px;
	}

	#modalRequestMoreDataBody label {
		font-size: small;
	}

	.input {
		width: 100%;
	}

	button {
		border: none;
		cursor: pointer;
	}

	button.green {
		color: white;
		background-color: #5EBB47;
	}

	.loader {
		border: 16px solid #f3f3f3;
		border-top: 16px solid #5EBB47;
		border-radius: 50%;
		margin: auto;
		width: 50px;
		height: 50px;
		animation: spin 2s linear infinite;
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
</style>

<script src="/js/jquery-2.1.1.js"></script>
<script type="text/javascript">
	var apretaste = {
		url: "",
		wait: false,

		doaction: function (href, popup, desc, wait) {
			apretaste.url = "/run/display?subject=" + href;
			apretaste.wait = Boolean(wait);

			if(Boolean(popup)) {
				$('#modalRequestMoreDataBody').empty();

				$.each(desc.split("|"), function(i, val) {
					var type = "t";
					var label = val;

					var p = val.split(":");
					if(p.length == 2) {
						type = p[0];
						label = p[1];
					}

					var required = label.endsWith("*") ? 'required' : '';
					var html = '<div style="text-align:left; margin-bottom:15px;">';

					if($.inArray(type, ['t','d','n','e','p','u']) >= 0) {
						if(type=='t') type = 'text';
						if(type=='d') type = 'date';
						if(type=='n') type = 'number';
						if(type=='e') type = 'email';
						if(type=='p') type = 'password';
						if(type=='u') type = 'file';
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<input id="field'+i+'" onkeyup="apretaste.onEnter(event);" type="'+type+'" class="input" '+required+'/>';
					}

					if(type=="m") {
						label = label.substring(0, label.lastIndexOf('['));
						var options = val.substring(val.indexOf('[')+1, val.lastIndexOf(']')).split(',');
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<select id="field'+i+'" class="input" '+required+'><option value=""></option>';
						for (var i = 0; i < options.length; i++) {
							var option = options[i].trim();
							html += '<option value="'+option+'">'+option+'</option>';
						}
						html += '</selects>';
					}

					if(type=="a") {
						html += '<label for="field'+i+'">'+label+'</label><br/>';
						html += '<textarea id="field'+i+'" onkeyup="apretaste.onControlPlusEnter(event);" rows="4" class="input" '+required+'></textarea>';
					}

					$('#modalRequestMoreDataBody').append(html+'</div>');
				});
				modalOpen('modalRequestMoreData');
				$('#field0').focus();
			}
			else apretaste.send();
		},

		sendMoreData: function() {
			var params = "";
			var redirect = true;
			$('#modalRequestMoreDataBody .input').each(function(){
				$(this).css("border", "1px solid #A9A9A9");

				var type = $(this).attr('type');
				var required = $(this).attr('required');
				var value = $(this).val().trim();

				var invalid = false;
				if(type=='email') invalid = !isEmail(value);

				if(invalid || (required && value == "")) {
					$(this).css("border", "1px solid red");
					redirect = false;
					return false;
				}

				if(type=='file') {
					var id = $(this).attr('id');
					value = apretaste.uploadFile(id);
				}

				params += encodeURIComponent(value) + " ";
			});

			if(redirect) {
				apretaste.url += " " + params;
				modalClose('modalRequestMoreData');
				apretaste.send();
			}
		},

		uploadFile: function(id) {
			var file = $('#'+id).prop("files")[0];
			var form = new FormData();
			form.append("file", file);

			var ret = "";
			$.ajax({
				url:'/api/upload',
				dataType:'json',
				cache:false,
				contentType:false,
				processData:false,
				async:false,
				data: form,
				type: 'post',
				success: function(data) {
					if(data.code=='ok') ret = data.message;
				}
			});
			return ret;
		},

		send: function() {
			if(apretaste.wait) {
				window.location = apretaste.url;
			}else{
				$.get(apretaste.url, function(data) {
					modalOpen('modalRequestSent');
					location.reload();
				});
			}
		},

		onSelect: function(href) {
			apretaste.wait = false;
			apretaste.url = "/run/display?subject=" + href;
			apretaste.send();
		},

		onControlPlusEnter: function(e) {
			if(e.ctrlKey && e.keyCode === 13) {
				apretaste.onEnter(e);
			}
		},

		onEnter: function(e) {
			if(e.keyCode === 13) {
				e.preventDefault();
				apretaste.sendMoreData();
			}
			if (e.keyCode == 27) {
				modalClose('modalRequestMoreData');
			}
		}
	};

	function modalOpen(id) {
		$('#'+id).css('visibility', 'visible');
	}

	function modalClose(id) {
		$('#'+id).css('visibility', 'hidden');
	}

	function isEmail(email) {
		const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
		return re.test(email);
	};
</script>

<!-- web push notifications -->
<script type="text/javascript">
	(function(p,u,s,h){
		p._pcq=p._pcq||[];
		p._pcq.push(['_currentTime',Date.now()]);
		s=u.createElement('script');
		s.type='text/javascript';
		s.async=true;
		s.src='https://cdn.pushcrew.com/js/d011951882e811830fa7e51f1fec62d7.js';
		h=u.getElementsByTagName('script')[0];
		h.parentNode.insertBefore(s,h);
	})(window,document);

	_pcq.push(['APIReady', function (){
		$.ajax({url: "/api/saveAppId?email={$USER_EMAIL}&appid="+pushcrew.subscriberId});
	}]);
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-49715278-1"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'UA-49715278-1', {
		'custom_map': {'dimension1': 'service'}
	});
	gtag('event', 'push_service', {'service': '{$APRETASTE_SERVICE_NAME}'});
</script>
