<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Analytics</title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Home-Made Analytics system and management tools for Apretaste">
		<meta name="author" content="Salvi Pascual">
		<meta name="author" content="hCarras">

		<link rel="icon" href="https://apretaste.com/static/images/apretaste.icon.png">

		<!-- jQuery -->
		<script src="https://apretaste.com/static/js/jquery.js"></script>

		<!-- Bootstrap Core CSS -->
		<link href="https://apretaste.com/static/css/bootstrap.min.css" rel="stylesheet">
		<script src="https://apretaste.com/static/js/bootstrap.min.js"></script>

		<!-- Custom stylesheets -->
		<link href="../css/basics.css" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	</head>

	<body>
		<nav class="navbar navbar-inverse" style="border-radius:0px; -webkit-border-radius:0px; -moz-border-radius:0px;">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand"><?php if(isset($title)) echo $title; ?></span>
				</div>
				<div class="navbar-right">
					<button type="button" class="btn btn-default navbar-btn"><i class="fa fa-home"></i> Home</button>
				</div>
			</div>
		</nav>

		<div class="container">
			<?php echo $this->getContent(); ?>
		</div>
	</body>
</html>