<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" href="/campaigns/new"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Campaign</a>
		<a class="btn btn-small btn-default" href="/campaigns/lists">Lists</a>
		<a class="btn btn-small btn-default" href="/campaigns/reports">Reports</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Scheduled</th>
					<th class="text-center">Status</th>
					<th class="text-center">List</th>
					<th class="text-center">Subject</th>
					<th class="text-center">Sent</th>
					<th class="text-center">Bounced</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($campaigns as $campaign) {
				$failure = round(($campaign->bounced*100)/$campaign->sent, 2); ?>
				<tr>
					<td class="text-center"><?=date("M d h:i A", strtotime($campaign->sending_date))?></td>
					<td class="text-center"><?=$campaign->status?></td>
					<td class="text-center"><?=$campaign->list?></td>
					<td><?=$campaign->subject?></td>
					<td class="text-center"><?=$campaign->sent?></td>
					<td class="text-center"><?=$campaign->bounced?> (<?=$failure?>%)</td>
					<td class="text-center">
						<nobr>
							<a class="btn btn-xs btn-default" target="_blank" href="/campaigns/view?id=<?=$campaign->id?>"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
							<?php if($campaign->status == "WAITING") { ?>
								<a class="btn btn-xs btn-default" href="/campaigns/update?id=<?=$campaign->id?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
								<a class="btn btn-xs btn-danger" onclick="return confirm('Are you sure? There is no way back!');" href="/campaigns/removeCampaignSubmit?id=<?=$campaign->id?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
							<?php } ?>
						</nobr>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
