<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" data-toggle="modal" data-target="#newList"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New List</a>
		<a class="btn btn-small btn-default" href="campaignReports">Reports</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Name</th>
					<th class="text-center">Group</th>
					<th class="text-center">Subscribers</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($lists as $list) { ?>
				<tr>
					<td class="text-center"><?=$list->name?></td>
					<td class="text-center"><?=$list->group?></td>
					<td class="text-center"><?=$list->subscribers?></td>
					<td class="text-center">
						<nobr>
							<?php if($list->id > 2) { ?>
								<a class="btn btn-xs btn-default" href="/campaigns/subscribers?id=<?=$list->id?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
								<a class="btn btn-xs btn-danger"  onclick="return confirm('Are you sure? This will remove all the subscribers too!');" href="/campaigns/deleteListSubmit?id=<?=$list->id?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
							<?php } ?>
						</nobr>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal for add a new list -->
<div id="newList" class="modal fade" role="dialog">
	<form action="/campaigns/newListSubmit" method="POST">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add subscribers</h4>
				</div>
				<div class="modal-body">
					<!-- name for the list -->
					<div class="form-group">
						<label for="name">Name of the list</label>
						<input id="name" type="text" name="name" class="form-control" required />
					</div>

					<!-- subscribers -->
					<div class="form-group">
						<label for="emails">Add a list of emails one per line</label>
						<textarea id="emails" name="emails" style="width:100%; height:300px;" required></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Add"/>
				</div>
			</div>
		</div>
	</form>
</div>
