<div class="row">
	<div class="col-xs-12">
		<form id="form" role="form" action="newSubmit" method="POST">
			<!-- Subject of the email -->
			<div class="form-group">
				<label for="subject">Subject of the email</label>
				<input id="subject" type="text" class="form-control" name="subject" required />
			</div>

			<!-- Create the editor container -->
			<div class="form-group">
				<label for="content">Content of the email</label>
				<textarea id="content" name="content" class="form-control" rows="20" required></textarea>
			</div>

			<!-- List where to send the email -->
			<div class="form-group">
				<label for="list">Test the email before sending</label>
				<div class="input-group">
					<input id="test" type="email" value="<?= $testEmail ?>" class="form-control" />
					<span class="input-group-btn">
						<button type="button" onclick="testEmail();" class="btn btn-default">Test</button>
					</span>
				</div>
				<p id="sent" style="color:green; font-size:small; display:none;"></p>
			</div>

			<div class="form-group">
				<a class="btn btn-default" href="/campaigns">Cancel</a>
				<button class="btn btn-primary" type="submit">Send!</button>
			</div>
		</form>
	</div>
</div>


<!-- SCRIPTS -->

<script type="text/javascipt">
	function testEmail(){
		var email = $('#test').val();
		var subject = "TEST " + $('#subject').val();
		var content = tinyMCE.activeEditor.getContent();

		$.ajax({
			url: "/campaigns/testAsync",
			method: "POST",
			data: {"email":email, "subject":subject, "content":content},
			async: false
		}).done(function(data) {
			$("#sent").html('Text email sent to '+email).show();
		});
	}
</script>
