<div class="row">
	<div class="col-xs-12">
		<h1>Campaigns sent</h1>
		<div id="sentCampaignsChart" style="width:100%; height:400px;"></div>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// visualize the graph
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['Day sent','sent','opened','bounced'],
			<?php foreach ($campaigns as $campaign) { ?>
				['<?=date("m/d", strtotime($campaign->sending_date))?>\n<?=$campaign->subject?>',
				<?=$campaign->sent?>,
				<?=$campaign->opened?>,
				<?=$campaign->bounced?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('sentCampaignsChart'));
		chart.draw(data, {});
	});
</script>
