<div class="row">
	<div class="col-xs-12 text-right">
		<a class="btn btn-small btn-default" data-toggle="modal" data-target="#addSubscribers"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Subscribers</a>
		<a class="btn btn-small btn-default" href="/campaigns/lists">Lists</a>
		<br/><br/>
	</div>

	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Email</th>
					<th class="text-center">Name</th>
					<th class="text-center">Inserted</th>
					<th class="text-center">Status</th>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($subscribers as $subscriber) { ?>
				<tr>
					<td class="text-center"><?=$subscriber->email?></td>
					<td class="text-center"><?=$subscriber->name?></td>
					<td class="text-center"><?=$subscriber->inserted?></td>
					<td class="text-center"><?=$subscriber->status?></td>
					<td class="text-center">
						<a class="btn btn-xs btn-default" href="/campaigns/deleteSubscribersSubmit?list=<?=$subscriber->list?>&id=<?=$subscriber->id?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal for add subscribers -->
<div id="addSubscribers" class="modal fade" role="dialog">
	<form action="/campaigns/addSubscribersSubmit" method="POST">
		<input type="hidden" name="list" value="<?=$campaignId?>"/>
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add subscribers</h4>
				</div>
				<div class="modal-body">
					<!-- subscribers -->
					<div class="form-group">
						<label for="emails">Add a list of emails one per line</label>
						<textarea id="emails" name="emails" style="width:100%; height:300px;" required></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Add"/>
				</div>
			</div>
		</div>
	</form>
</div>
