<div class="row">
	<div class="col-xs-12">
		<table class="table">
			<thead>
				<tr>
					<th class="text-center">Id</th>
					<th class="text-center">Email</th>
					<th class="text-center">Last note</th>
					<th class="text-center"></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($notes as $note) { ?>
				<tr>
					<td class="text-center"><?=$note->id?></td>
					<td class="text-center"><?=$note->email?></td>
					<td class="text-center nobr"><?=date("m/d/Y h:i A", strtotime($note->last_chat))?></td>
					<td class="text-center"><a class="btn btn-xs btn-primary" href="conversation?id=<?=$note->id?>">Chat</a></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
