<div class="row">
	<div class="col-xs-6">
		<h1>New tickets: <?=$newCount?></h1>
	</div>

	<div class="col-xs-6">
		<h1>Pending tickets: <?=$pendingCount?></h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div id="ticketsChart" style="width:100%; height:400px;"></div>
	</div>
</div>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	// visualize the graph
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(function () {
		var data = google.visualization.arrayToDataTable([
			['Day','New','Responded','Closed'],
			<?php foreach ($tickets as $ticket) { ?>
				['<?=date("m/d", strtotime($ticket->inserted))?>',
				<?=$ticket->new_count?>,
				<?=$ticket->response_count?>,
				<?=$ticket->closed_count?>],
			<?php } ?>
		]);
		var chart = new google.visualization.AreaChart(document.getElementById('ticketsChart'));
		chart.draw(data, {});
	});
</script>
